### ISSUE TITLE
Generate PHP project coverage in real time without ending the program running.

### ISSUE THREAD

**Issue by kreamyu** [sebastianbergmann/php-code-coverage#1017]
I'm sorry to bother you, I want to test the coverage of a php web application. 
I need to get the coverage in real time while the program is running, like nyc or jacoco. 
Instead of getting it when ending the program, or writing it in advance in the program. 
Can php-code-coverage be implemented? I have read all the documents, but I still don’t know how to implement it. thank you

**Comment by sebastianbergmann** [comment]
This is outside the scope of this project.
