### ISSUE TITLE
Single line method is ignored

### ISSUE THREAD

**Issue by mvorisek** [sebastianbergmann/php-code-coverage#1020]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 9.2.29
| PHP version               | 8.2.12
| Driver                    | Xdebug
| PCOV version (if used)    | n/a
| Xdebug version (if used)  | 3.2.2
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 9.6.13

repro code:
```
class InitializerTraitTest extends TestCase
{
    public function testInitDeclaredPublicException(): void
    {
        $m = new class() extends AbstractInitializerMock {
            public function init(): void {}
        };
    }
}
```

(full source code: https://github.com/atk4/core/blob/5.0.0/tests/InitializerTraitTest.php#L72)

when the code above is modified like:

```diff
+            #[\Override]
             public function init(): void {}
```

then the coverage is collected. It seems this lib does not account for single line methods (methods starting and ending at the same line, even a method attribute on another line is enough to enable coverage).

![image](https://github.com/sebastianbergmann/php-code-coverage/assets/2228672/d64ee165-2b8c-4ff1-a566-b1cfb557533e)

**Comment by sebastianbergmann** [comment]
CC @Slamdunk

**Comment by Slamdunk** [comment]
Looking at here:

https://github.com/atk4/core/blob/9bc701001c6c7959d12b1a66cdeea5d618735abb/src/InitializerTrait.php#L46-L50

It seems to me that the CC is correctly corrected both times:

1. when the method is `public`, `init()` is **not** called so it's red
2. when the method is `protected`, `init()` **is** called so it's green

The `#[\Override]` attribute has nothing to do with this.

I see no bug here :shrug:

**Comment by sebastianbergmann** [comment]
@Slamdunk Thank you!

**Comment by Slamdunk** [comment]
@mvorisek now it makes mor sense: fix proposed in https://github.com/sebastianbergmann/php-code-coverage/pull/1021
