### ISSUE TITLE
Bump php-parser to version 4.19.1

### ISSUE THREAD

**Issue by alecpl** [sebastianbergmann/php-code-coverage#1043]
Coming from https://github.com/nikic/PHP-Parser/issues/1017

I'm looking to have a phpunit package that works on PHP 8.1-8.4. I'm using phpunit 9. It look like it might work, but...

There's one problem with that. nikic/php-parser 4.19.1 is required for PHP 8.4 support.

Any chance php-code-coverage 9.2 would bump required php-parser version to `^4.19.1`?

**Comment by sebastianbergmann** [comment]
Bumped in 2681df11ccc4d3553c973ecf348acbdd0e7b7415.
