### ISSUE TITLE
Code coverage report HTMLs not rendering properly on OSX

### ISSUE THREAD

**Issue by woganmay** [sebastianbergmann/php-code-coverage#1047]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 11.0.3
| PHP version               | 8.3.12
| Driver                    | Xdebug
| Xdebug version  | 3.3.2
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version  | 11.1.2

In short: The --coverage-html does its job, renders HTML, and it renders 100% fine using Chrome on Windows:

![image](https://github.com/user-attachments/assets/aeca50b5-823c-4927-9ff0-4f39498500f2)

And despite all the CSS and JS loading, no console/network errors, etc, it fails to apply the CSS styling using Safari on Mac:

![image](https://github.com/user-attachments/assets/d5d53a8b-0413-4a84-91d7-c870c29e3070)

Any ideas?

**Comment by sebastianbergmann** [comment]
It renders fine for me on macOS with both Firefox and Safari.

**Comment by woganmay** [comment]
Thanks @sebastianbergmann ! I've got 2x OSX users on my side using Safari that it does not render for, which is strange! Any suggestions on troubleshooting this?

**Comment by sebastianbergmann** [comment]
Safari 18.0.1 (20619.1.26.31.7) renders the report just fine for me on macOS Sequoia (15.0.1). I am sorry, but I do not think that I can help you.

**Comment by woganmay** [comment]
Yeah it's looking like a weird edge case possibly involving Cloudflare Tunnels messing up MIME types @sebastianbergmann - I'll resolve this one in the rare event someone else comes across this.
