### ISSUE TITLE
Usability: Change hover to click in html report

### ISSUE THREAD

**Issue by uncaught** [sebastianbergmann/php-code-coverage#1053]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 11.0.z

I like the html report a lot, but it is not usable for us with javascript enabled. The popover displaying the covering lines is unreadable because it is so huge and is not scrollable. And also scrolling through the page itself with the mouse inside is very annoying due to the constant popup blocking the view.

<img src="https://github.com/user-attachments/assets/ee0d3236-5f0e-4070-9f44-ecff23e290b9" width="50px">

I would like to ask if we could change the `mouseenter`/`mouseleave`  events in `src/Report/Html/Renderer/Template/js/file.js` to toggle with a `click` event instead. Then I hope the popover will stay open, allows to scroll it, and doesn't come in the way when browsing a page.

I would create a PR if this was acceptable.

**Comment by sebastianbergmann** [comment]
> I would create a PR if this was acceptable

Yes, please.
