### ISSUE TITLE
break / continue statements not being seen as covered

### ISSUE THREAD

**Issue by zodeus** [sebastianbergmann/php-code-coverage#129]
Staring a new project and trying to reach 100% coverage and this is the last edge case I'm trying to figure out.

Having this style of code anywhere ,in any test always results in the break / continue statements not being covered. 

Current setup is
- Zend Server - 5.6.0+b311
- PHP - 5.3.14
- PHPUnit  - 3.7.8
- PHP_CodeCoverage  - 1.2.6
- Xdebug -  2.1.2

![Broken Test](http://i.imgur.com/6AHqw.png)

Also a side note abstract methods are also not being marked as covered even though there is a concrete class that is being tested, the concrete class has full coverage.

**Comment by fotografi** [comment]
>
