### ISSUE TITLE
Refactor how ignored lines are handled

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/php-code-coverage#139]
Ignored lines are currently handled for each report that is generated.

The respective filter (currently implemented in `PHP_CodeCoverage_Util::getLinesToBeIgnored()` should be applied once during code coverage data collection instead.

**Comment by mindplay-dk** [comment]
My test suite just went from about 2 seconds to over a minute execution time, when I switched from PHP 5.3 to 5.6 - turning off code coverage brings it back under one second.

I read through the related issues and I do not understand the problem.

I doubt I'm using "process isolation" - I'm not using php-unit, just php-code-coverage, and my test-suite is [painfully simple](https://github.com/mindplay-dk/stockpile/blob/master/test/test.php).

Can somebody please explain?

Why is this only a problem on my Windows system with PHP 5.6? Under Linux with PHP 5.3, 5.4, 5.5 and 5.6, tests complete in a few seconds, like they always have.

What am I doing wrong? Can I fix it?

**Comment by sebastianbergmann** [comment]
Please do not report a new issue by commenting on an old issue, @mindplay-dk.

**Comment by mindplay-dk** [comment]
I'm sorry, I thought this was the same issue. I will open a new one.
