### ISSUE TITLE
mapTestClassNameToCoveredClassName has no effects

### ISSUE THREAD

**Issue by jg-development** [sebastianbergmann/php-code-coverage#260]
We are using the phpunit.xml class with the option mapTestClassNameToCoveredClassName.
With 4.1.4 it does not have any effect? Is this still an option?

We have the intention to autocover the related Class (and only the related class).
Example:
forceCoversAnnotation=true
mapTestClassNameToCoveredClassName=true

ClassName:
Date
TestName:
DateTest

It seems this is currently not possible? 
We decided to implement a getter in the CodeCoverage.php and changed the "getLinesToBeCovered" method. Is a pull request an option?

Greeting Jan

**Comment by Maks3w** [comment]
This feature is expected to be implemented on PHPUnit code base https://github.com/sebastianbergmann/phpunit/issues/1936

This issue could be closed.
