### ISSUE TITLE
Undefined offset: 17 in /home/vendor/phpunit/php-code-coverage/src/CodeCoverage.php on line 733

### ISSUE THREAD

**Issue by megapo** [sebastianbergmann/php-code-coverage#278]
[exec] PHPUnit 4.2.5 by Sebastian Bergmann.
     [exec] 
     [exec] Configuration read from /var/lib/jenkins/jobs/test_03_short/workspace/phpunit.xml
     [exec] 
     [exec] Time: 15.46 seconds, Memory: 3.50Mb
     [exec] 
     [exec] PHP Notice:  Undefined offset: 17 in /home/vendor/phpunit/php-code-coverage/src/CodeCoverage.php on line 733
     [exec] PHP Stack trace:
     [exec] PHP   1. {main}() /home/vendor/phpunit/phpunit/phpunit:0
     [exec] PHP   2. PHPUnit_TextUI_Command::main() /home/vendor/phpunit/phpunit/phpunit:54
     [exec] PHP   3. PHPUnit_TextUI_Command->run() /home/vendor/phpunit/phpunit/src/TextUI/Command.php:138
     [exec] PHP   4. PHPUnit_TextUI_TestRunner->doRun() /home/vendor/phpunit/phpunit/src/TextUI/Command.php:186
     [exec] PHP   5. PHP_CodeCoverage_Report_Clover->process() /home/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:439
     [exec] PHP   6. PHP_CodeCoverage->getReport() /home/vendor/phpunit/php-code-coverage/src/CodeCoverage/Report/Clover.php:84
     [exec] PHP   7. PHP_CodeCoverage_Report_Factory->create() /home/vendor/phpunit/php-code-coverage/src/CodeCoverage.php:165
     [exec] PHP   8. PHP_CodeCoverage->getData() /home/vendor/phpunit/php-code-coverage/src/CodeCoverage/Report/Factory.php:64
     [exec] PHP   9. PHP_CodeCoverage->addUncoveredFilesFromWhitelist() /home/vendor/phpunit/php-code-coverage/src/CodeCoverage.php:199
     [exec] PHP  10. PHP_CodeCoverage->append() /home/vendor/phpunit/php-code-coverage/src/CodeCoverage.php:631
     [exec] PHP  11. PHP_CodeCoverage->applyIgnoredLinesFilter() /home/vendor/phpunit/php-code-coverage/src/CodeCoverage.php:323
     [exec] PHP  12. PHP_CodeCoverage->getLinesToBeIgnored() /home/vendor/phpunit/php-code-coverage/src/CodeCoverage.php:571
     [exec] PHP Notice:  Undefined offset: 127 in /home/vendor/phpunit/php-code-coverage/src/CodeCoverage.php on line 733

phpunit.xml
[code] I delete  begin <
phpunit bootstrap="src/test/unit/autoload.php" backupGlobals="false"
backupStaticAttributes="false" strict="true" verbose="true">
testsuite name="XXX">
directory suffix="Test.php">src/tests/unit</directory>
/testsuite>
  logging>
    log type="coverage-html" target="build/coverage" title="XXX"/>
    log type="coverage-clover" target="build/logs/clover.xml"/>
    log type="coverage-crap4j" target="build/logs/crap4j.xml"/>
    log type="junit" target="build/logs/junit.xml" logIncompleteSkipped="true"/>

  /logging>
  filter>
    whitelist addUncoveredFilesFromWhitelist="true">
      directory suffix=".php">src</directory>
      exclude>
        file>src/autoload.php</file>
      /exclude>
    /whitelist>
  /filter>
/phpunit>
[/code]

**Comment by lserni** [comment]
I believe this might be the same problem I'm having (same error, slightly different line of the same file). The line is this:

 if (0 === strpos($_token, '/*') && '*/' === substr(trim($lines[$i-1]), -2)) {

where $lines[$i-1] is not defined, hence giving an invalid offset.

and the error is caused by a PHP file ending with double // comment, e.g.

<?php
....
// This is the next to last line of the file
// This is the last line of the file, even if PSR-2 says it should be empty

Once the PHP files get fixed adding an empty line at the end, CodeCoverage no longer has issues.
