### ISSUE TITLE
Code coverage html is not being generated

### ISSUE THREAD

**Issue by acasanova** [sebastianbergmann/php-code-coverage#282]
I used to be able to generate code coverage html by adding a log node to the phpunit.xml file
````
<logging>
      <log type="coverage-html" target="storage/work/report" charset="UTF-8"
       highlight="false" lowUpperBound="35" highLowerBound="70"/>
      <log type="testdox-html" target="./storage/work/report/testdox.html"/>
    </logging>
````
I used to install phpunit via pear. I understand that has changed now and I use the new installation method from the phar file(v4.2). With xdebug, php 5.4.32, php-fpm  I haven't been able to generate the coverage html files.  Looking at the readme for this project I see that you can leverage the code_coverage api but I'm not sure if I can still run tests against a phpunit config file and still generate html files. The file permissions are fine since I see that the testdox.html file is generated.

Thanks in advanced

**Comment by sebastianbergmann** [comment]
No feedback, closing.
