### ISSUE TITLE
XML report ignores whitelist filter (2.0.11)

### ISSUE THREAD

**Issue by Beanow** [sebastianbergmann/php-code-coverage#285]
Using the following as my settings, all files are still output instead of just the whitelisted ones.
They are properly filtered for other outputs, such as php or html output.

```xml
<phpunit bootstrap="./bootstrap.php">
  <testsuites>
    <testsuite>
      <directory>./src</directory>
    </testsuite>
  </testsuites>
  <filter>
    <whitelist processUncoveredFilesFromWhitelist="true">
      <directory>../../src</directory>
    </whitelist>
  </filter>
</phpunit>
```

**Comment by sebastianbergmann** [comment]
Should have been fixed by f15cfc19bfe09e01095afca6793c39881e6622dc. Please open a new ticket if the problem persists.
