### ISSUE TITLE
Code Coverage reporting marked lines not executed even when they are

### ISSUE THREAD

**Issue by ralphbtp** [sebastianbergmann/php-code-coverage#293]
The generated HTML report says that lines on my codes where not executed even whey are. The tests are selenium webdriver RC and I have not have problems before except for this weird case when I use @depends on a test case and expect that the previous test is on the right web page. The the issue occurs for those test cases that does not call the method $this->open() will show in the code coverage report that the lines are not executed.

**Comment by sebastianbergmann** [comment]
Please open a new ticket (and include a minimal, self-contained, reproducing test case) if this problem still exists in the current version of PHP_CodeCoverage.
