### ISSUE TITLE
Fix for code coverage not report on certain lines

### ISSUE THREAD

**Issue by tarlabs** [sebastianbergmann/php-code-coverage#295]
Hi @sebastianbergmann 

I have created a patch for the issue and it is in the below file

https://github.com/tarlabs/php-code-coverage/blob/master/src/CodeCoverage.php

I am not sure but when I create a pull request it should be 21 files changed. Though my commit only changes one. Can you please get this file patched in the master branch?

Regards,
Tarun

**Comment by sebastianbergmann** [comment]
Closing in favor of #296.
