### ISSUE TITLE
Code coverage report issue with SonarQube and "empty" classes

### ISSUE THREAD

**Issue by laimoncijus** [sebastianbergmann/php-code-coverage#313]
Hello,

We are experiencing issue with SonarQube, where it reports "empty" classes as being not covered by tests and therefore the overall project test coverage is calculated wrong. The issue comes due the fact, that "empty" classes are not showing up in the report at all (as stated in #265).

Would it not make still make sense to include such files in the report with metrics like "lines to cover" (which would be 0 in this case) and not exclude it completely? Skipping file from the report may cause problems with the latter result interpretation -  e.g. SonarQube tries "approximate the number of missing uncovered lines" because the "empty" class is not listed in the report (for more details please see original thread at http://markmail.org/message/xpf7avbz7ox46zcq)

Maybe you could give a statement/your position regarding this problem?

Thanks!

**Comment by JacksonGit** [comment]
Hi, we´re dealing with the same issue and we´re wondering if this is a SonarQube or php-code-coverage issue?

Thank

**Comment by sebastianbergmann** [comment]
I cannot reproduce this issue with PHPUnit 4.6.9 and PHP_CodeCoverage 2.1.2.
