### ISSUE TITLE
Travis HHVM Coverage

### ISSUE THREAD

**Issue by sagikazarmark** [sebastianbergmann/php-code-coverage#315]
I am trying to set up hhvm with coverage on travis, but I get the following notice:

`notice: Calling fb_enable_code_coverage from a nested VM instance may cause unpredicable results`

**Comment by sebastianbergmann** [comment]
Closing because of  #324 and 672248f49a25fcca46aa6c73612d6731d6b83c4a. Please open a new ticket if the problem persists.

**Comment by sagikazarmark** [comment]
Thanks
