### ISSUE TITLE
Add a way to output *.cov files for use with phpcov

### ISSUE THREAD

**Issue by bskendig** [sebastianbergmann/php-code-coverage#318]
Please add a way for the PHP_CodeCoverage class to write its output in the form of a *.cov file which the command-line "phpcov" tool can then use.

If this is already possible, then please update README.md to show how to export a *.cov file.

**Comment by sebastianbergmann** [comment]
This functionality is implemented in the `PHP_CodeCoverage_Report_PHP` class and available in PHPUnit via the `--coverage-php` commandline option.

**Comment by bskendig** [comment]
I'm not using phpunit in this case. I am trying to directly use php-code-coverage in my PHP application so that I can see what lines of code are executed in real-world use. (I'm not profiling; my goal is to find dead lines of code.)

Thank you for explaining that PHP_CodeCoverage_Report_PHP is what I want. I hadn't been able to find anything that says that PHP_CodeCoverage_Report_PHP's output is what phpcov reads.
