### ISSUE TITLE
Code coverage not displayed in Netbeans

### ISSUE THREAD

**Issue by Henk8** [sebastianbergmann/php-code-coverage#319]
I want to use Code Coverage on my project using PHPUnit and xdebug. The xdebugger is installed and a single test on a file is working correctly, with passed and failed percentage.

But if I want to test my entire project to see the code coverage, the coverage is 0,00%. The report state: no data -- have you run your code yet?

Netbeans creates a xml report (nb-phpunit-coverage.xml).  The result of the xml report is:

metrics coveredelements="0" elements="0" coveredstatements="0" statements="0" coveredconditionals="0" conditionals="0" coveredmethods="0" methods="0" classes="0" ncloc="0" loc="0" files="0"

Netbeans is installed on my c: drive and my project is on a mapped network drive p:. And I think that is the problem. If I have my project and Netbeans on the same drive (c or p) code coverage is working fine.

Is this a know issue and is there anything I could do about it?

**Comment by sebastianbergmann** [comment]
Please open a new ticket (and include a minimal, self-contained, reproducing test case) if this problem still exists in the current version of PHP_CodeCoverage.
