### ISSUE TITLE
Ignore @codeCoverageIgnore

### ISSUE THREAD

**Issue by bskendig** [sebastianbergmann/php-code-coverage#320]
I would like a way to tell PHP_CodeCoverage to ignore "@codeCoverageIgnore" (and "...Start" and "...End") annotations.

I am using php-code-coverage with phpcov to tell me what lines of code are (and aren't) hit during normal usage of my codebase, to help me find dead code. However, I also run phpunit on the codebase, and some code is marked with @codeCoverageIgnore so that it will be skipped by unit tests. I don't want this code to be ignored by php-code-coverage when I'm running my code normally, but I don't want to have to keep deleting and restoring the @codeCoverageIgnore annotations.

**Comment by sebastianbergmann** [comment]
This was implemented for this component a while ago. It could be that the functionality is not exposed in PHPUnit yet.

**Comment by CJDennis** [comment]
@sebastianbergmann Since this functionality is implemented, how do you use it? I have exactly the same use case: I've had to mark a lot of unused/unreachable code as `@codeCoverageIgnore*` but I'd like to periodically check if it's still true that the marked code is unused/unreachable.

**Comment by dvdoug** [comment]
@CJDennis [`--disable-coverage-ignore`](https://phpunit.readthedocs.io/en/9.5/textui.html?highlight=disable#command-line-options)
