### ISSUE TITLE
xml addUncoveredFilesFromWhitelist=false not working in 2.0.16

### ISSUE THREAD

**Issue by jpd4nt** [sebastianbergmann/php-code-coverage#325]
Hi updated to 2.0.16 from 2.0.15 and its not logging in the output files which should be excluded, like phpunit bootstrap.php.  Rollback and it works as expected.

I added the the bootstrap file to the blacklist and it still was included in the output, so it seems like all uncovered files were being added despite being blacklisted.

php 5.6.7
xdebug 2.3.2

**Comment by sebastianbergmann** [comment]
Are you sure that this is related to php-code-coverage 2.0.16 and not to this change https://github.com/sebastianbergmann/phpunit/commit/2d4c02c71520d9348b7921e13112c9d8cb2a5612 in PHPUnit 4.6.4?

**Comment by jpd4nt** [comment]
OK:

PHPUnit 4.6.3 + php-code-coverage 2.0.15 = works as expected
PHPUnit 4.6.3 + php-code-coverage 2.0.16 = bootstrap included in output

PHPUnit 4.6.4 + php-code-coverage 2.0.15 = works as expected
PHPUnit 4.6.4 + php-code-coverage 2.0.16 = bootstrap included in output

Do you require any more details?

**Comment by sebastianbergmann** [comment]
A minimal reproducing example would be nice.

PS: Is this the same (or similar to) as #326?

**Comment by jpd4nt** [comment]
It does look similar as #326

Will see if I can get some time to provide an example.

**Comment by sebastianbergmann** [comment]
Please check whether this problem persists with PHP_CodeCoverage 2.0.17 (bundled with PHPUnit 4.6.7 PHAR). Thanks!

**Comment by sebastianbergmann** [comment]
No feedback after 8 days, closing. Please open a new ticket if this problem persists.
