### ISSUE TITLE
Method definitions gets reported as uncovered after upgrade from 2.0.15 to 2.0.16.

### ISSUE THREAD

**Issue by IvanChepurnyi** [sebastianbergmann/php-code-coverage#326]
After upgrading to a new version, all my builds gets coverage drop by 25%, because of this issue. Here is an example of wrongly reported coverage:
https://coveralls.io/files/627501251

**Comment by sebastianbergmann** [comment]
Are you sure that this is related to php-code-coverage 2.0.16 and not to this change https://github.com/sebastianbergmann/phpunit/commit/2d4c02c71520d9348b7921e13112c9d8cb2a5612 in PHPUnit 4.6.4?

**Comment by IvanChepurnyi** [comment]
Hello Sebastian, the version of PHPUnit used for deployment is 4.1.6, not 4.6.x. Also after downgrading composer dependency to 2.0.15 the issue is not reproduced. Only 2.0.16 provides such a strange behaviour.

**Comment by sebastianbergmann** [comment]
A minimal reproducing example would be nice.

PS: Is this the same (or similar to) as #325?

**Comment by sebastianbergmann** [comment]
Please check whether this problem persists with PHP_CodeCoverage 2.0.17 (bundled with PHPUnit 4.6.7 PHAR). Thanks!

**Comment by sebastianbergmann** [comment]
No feedback after 8 days, closing. Please open a new ticket if this problem persists.
