### ISSUE TITLE
Ignorres whitelist-exclude in 2.0.16

### ISSUE THREAD

**Issue by white-gecko** [sebastianbergmann/php-code-coverage#328]
Since version 2.0.16 the code coverage report seams to ignore my whitelist-exclude configuration in [phpunit.xml](https://github.com/SaftIng/Saft/blob/e661a20a67ff61d9f4905eaedd210970167f2fe3/phpunit.xml) and also includes the test classes them self. While everything is fine if using codecoverage 2.0.15.

**Comment by sebastianbergmann** [comment]
Please check whether this problem persists with PHP_CodeCoverage 2.0.17 (bundled with PHPUnit 4.6.7 PHAR). Thanks!

**Comment by white-gecko** [comment]
Thank you, everything is fine again :-)
