### ISSUE TITLE
Last line of array gets uncovered in some circumstances

### ISSUE THREAD

**Issue by OndraM** [sebastianbergmann/php-code-coverage#329]
Hi,
I use PHP_CodeCoverage 2.0.16, PHP 5.6.8 and PHPUnit 4.6.4.

The last line of this code (the `];` line) is always shown as uncovered (even though the previous and also following lines are covered):

```php
$ban[$baz] = (object) [
    'foo' => 'bar',
];
```
however, everything is covered if there is not the object typecasting:
```php
$ban[$baz] = [
    'foo' => 'bar',
];
```
it is also OK if the value is not being associated to an array:
```php
$ban = (object) [
    'foo' => 'bar',
];
```
Any thoughts what could be wrong?

**Comment by sebastianbergmann** [comment]
Probably an Xdebug issue. @derickr?

**Comment by OndraM** [comment]
Maybe...? The xdebug version is 2.3.2. Should I rather report the issue there?

**Comment by sebastianbergmann** [comment]
Likely not a PHP_CodeCoverage issue, please open a ticket with Xdebug.
