### ISSUE TITLE
How to cover separate process

### ISSUE THREAD

**Issue by euoia** [sebastianbergmann/php-code-coverage#339]
Is it possible to get code coverage for a separate process? I would like to see coverage for a suite of functional tests which make requests to my application using Selenium. This seems equivalent to the following which produces a report showing 0 covered code:
```
phpcov execute --clover coverage.xml coverage
```

Where coverage is simply a script which makes a `wget` request to my application.

Could you explain please a bit about how this can be done?

**Comment by sebastianbergmann** [comment]
This is possible, however there is not really a generic way to do it. https://github.com/sebastianbergmann/php-code-coverage/blob/master/scripts/auto_prepend.php and https://github.com/sebastianbergmann/php-code-coverage/blob/master/scripts/auto_append.php are good starting points, though.
