### ISSUE TITLE
Source file with weird characters trips up HTML renderer

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/php-code-coverage#340]
```php
<?php
class Foo
{
    /**
     * ü
     */
    public function bar()
    {
    }
}
```

    $ hexdump -C Foo.php                                               
    00000000  3c 3f 70 68 70 0a 63 6c  61 73 73 20 46 6f 6f 0a  |<?php.class Foo.|
    00000010  7b 0a 20 20 20 20 2f 2a  2a 0a 20 20 20 20 20 2a  |{.    /**.     *|
    00000020  20 fc 0a 20 20 20 20 20  2a 2f 0a 20 20 20 20 70  | ..     */.    p|
    00000030  75 62 6c 69 63 20 66 75  6e 63 74 69 6f 6e 20 62  |ublic function b|
    00000040  61 72 28 29 0a 20 20 20  20 7b 0a 20 20 20 20 7d  |ar().    {.    }|
    00000050  0a 7d 0a 0a                                       |.}..|
    00000054

## Actual
![actual](https://cloud.githubusercontent.com/assets/25218/7889632/04df4fa8-0641-11e5-8530-8cced6f788e3.png)

## Expected
![expected](https://cloud.githubusercontent.com/assets/25218/7889640/0ed29da8-0641-11e5-9ba2-cde85c35d778.png)

**Comment by fpietka** [comment]
Related to file encoding here in ISO, and PHP `htmlspecialchars()` default to UTF-8.

**Comment by matueranet** [comment]
This fix uses ENT_SUBSTITUTE as one of the htmlspecialchars flags, which is only available since PHP 5.4, generating a lot of notices when running on PHP 5.3.

**Comment by sebastianbergmann** [comment]
Fixed in https://github.com/sebastianbergmann/php-code-coverage/commit/c43ad52e723b6311f644eeab34b4beebb72012ee

Thanks!

**Comment by fpietka** [comment]
Nice catch
