### ISSUE TITLE
Code coverage analysis slow under Windows with PHP 5.6

### ISSUE THREAD

**Issue by mindplay-dk** [sebastianbergmann/php-code-coverage#342]
I have the following [very simple test-suite](https://github.com/mindplay-dk/stockpile/blob/master/test/test.php) which uses php-code-coverage, but not php-unit.

When I switched from PHP 5.3 to 5.6, the time it takes to run this test-suite went from about 2 seconds to over a minute - simply turning off code coverage brings it back down to under one second.

This appears to occur only on Windows with PHP 5.6 - other versions from 5.3 up to 5.5 do not display this issue, and on Linux under PHP 5.6 there is no issue either.

I thought the issue might be related to #139, though I I'm not doing anything to try to create process isolation.

Am I doing something wrong?

**Comment by sebastianbergmann** [comment]
Is the version of PHP the only difference? For instance, maybe you use Xdebug 2.2 with PHP < 5.6 and Xdebug 2.3 with PHP 5.6. I am asking because of http://bugs.xdebug.org/view.php?id=1123

**Comment by mindplay-dk** [comment]
Confirmed - I just downgraded to xdebug 2.2.7 (latest 2.2 release) and the problem vanished. I guess I will continue to run with 2.2 until they sort out the issue with 2.3...

**Comment by sebastianbergmann** [comment]
Thanks for investigating this further.
