### ISSUE TITLE
Empty code coverage report if project is not on the same harddrive as IDE

### ISSUE THREAD

**Issue by Henk8** [sebastianbergmann/php-code-coverage#344]
I want to use Code Coverage on my project using PHPUnit and xdebug. The xdebugger is installed and a single test on a file is working correctly, with passed and failed percentage.

But if I want to test my entire project to see the code coverage, the coverage is 0,00%. The report state: no data -- have you run your code yet?

Netbeans creates a xml report (nb-phpunit-coverage.xml). The result of the xml report is:

metrics coveredelements="0" elements="0" coveredstatements="0" statements="0" coveredconditionals="0" conditionals="0" coveredmethods="0" methods="0" classes="0" ncloc="0" loc="0" files="0"

Netbeans is installed on my c: drive and my project is on a mapped network drive p:. And I think that is the problem. If I have my project and Netbeans on the same drive (c or p) code coverage is working fine.

See also #319 and #1698

I have a sample project but cannot include this, only PNG, GIF, JPG.

How do I update the code coverage that I have installed on Windows?
I have the lattest version of phpunit.phar.

**Comment by sebastianbergmann** [comment]
I cannot investigate this issue as I neither use Windows nor Netbeans.
