### ISSUE TITLE
Private Empty Constructor Coverage

### ISSUE THREAD

**Issue by tklever** [sebastianbergmann/php-code-coverage#346]
Found an inconsistency when using private constructors

```php
final class Demo
{
    private function __construct(){}
    
    public static function returnTrue()
    {
        return true;
    }
}
```

vs.

```php
final class Demo
{
    private function __construct()
    {
    }
    
    public static function returnTrue()
    {
        return true;
    }
}
```

Assuming the static function is covered, the first formatting shows 100%, all lines covered. The second formatting shows two uncovered lines (3 and 5 to be specific). No other changes to the file or tests, just two extra carriage returns.

**Comment by sebastianbergmann** [comment]
I cannot reproduce this.

![screenshot from 2015-06-19 14-04-23](https://cloud.githubusercontent.com/assets/25218/8253065/2dc04502-168c-11e5-8bac-71ac722aa549.png)
