### ISSUE TITLE
Make @deprecated an alias for @codeCoverageIgnore

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/php-code-coverage#351]

**Comment by l-x** [comment]
Dear Sebastian,

could you please explain the intention for this change? I personally cannot see any reason, why deprecated classes and methods should be excluded from coverage analysis.

Thanks in advance,

Alexander

**Comment by sebastianbergmann** [comment]
The intention is simple: if I mark something as deprecated then I don't care about it anymore.

I am considering making this optional (and off by default), though.

**Comment by l-x** [comment]
When you think in libraries you *might* be right. But when I think in an application, I will never ever not care about code that might be in production use but is deprecated.

Making this optional would be a great help.

Thanks a lot and best regards,

Alexander

**Comment by Maks3w** [comment]
@sebastianbergmann :+1: to off by default.

Library providers still having a contract for provide usable code even if marked as deprecated until is finally removed.

**Comment by sebastianbergmann** [comment]
Changed in 3.0.2.

**Comment by Krinkle** [comment]
@sebastianbergmann It became optional and disabled by default. I imagine, as creator of this option (and initially turned on by default), it's something you'd want to use when generating a coverage report from PHPUnit. However, I can't seem to find any way to turn this on from PHPUnit. TestRunner doesn't expose the setter?

**Comment by sebastianbergmann** [comment]
Looks like I forgot add handling of that option to PHPUnit.

**Comment by Krinkle** [comment]
Thanks! 🌟

**Comment by jarednova** [comment]
For future searchers add `ignoreDeprecatedCodeUnitsFromCodeCoverage="true"` to your `<phpunit` tag in `phpunit.xml` ex:

```xml
<phpunit
	bootstrap="tests/bootstrap.php"
	backupGlobals="false"
	colors="true"
	convertErrorsToExceptions="true"
	convertNoticesToExceptions="true"
	convertWarningsToExceptions="true"
	ignoreDeprecatedCodeUnitsFromCodeCoverage="true"
	>
	<testsuites>
```
