### ISSUE TITLE
generated html report has broken paths.

### ISSUE THREAD

**Issue by dogmatic69** [sebastianbergmann/php-code-coverage#353]
The paths for test coverage reports are messed up and have been for a while.. not sure exactly when I noticed it.

After running the tests this is the index.html page ![](http://i.imgur.com/Uuu4oLc.png)

To get to view anything I have to click dashboard and then one of the files in that report, then I can navigate the rest.
![](http://i.imgur.com/1SLhdeE.png)

The path is strange though, `///mnt/win/...` and the url is `___mnt_win_...` 

This is happening with my .xml config and just doing a simple run with `--coverage-html=some/path`

**Comment by sebastianbergmann** [comment]
Neither PHPUnit 3.7 nor PHP_CodeCoverage 1.2 are supported anymore.

**Comment by dogmatic69** [comment]
For the record, I found the commit that broke this

```
diff --git a/composer.json b/composer.json
index 8701db1..706e134 100644
--- a/composer.json
+++ b/composer.json
@@ -24,8 +24,8 @@
         "php": ">=5.3.3",
         "phpunit/php-file-iterator": ">=1.3.1",
         "phpunit/php-text-template": ">=1.1.1",
-        "phpunit/php-code-coverage": ">=1.2.1",
-        "phpunit/php-timer": ">=1.0.2",
+        "phpunit/php-code-coverage": ">=1.2.1,<1.3.0",
+        "phpunit/php-timer": ">=1.0.2,<1.1.0",
         "phpunit/phpunit-mock-objects": ">=1.2.0,<1.3.0",
         "symfony/yaml": ">=2.1.0,<2.2.0",
         "ext-dom": "*",
```

**Comment by sebastianbergmann** [comment]
You lost me. That does not have anything to do with what I said earlier: Neither PHPUnit 3.7 nor PHP_CodeCoverage 1.2 are supported anymore.

Are you experiencing the same problem with a current version of PHPUnit / PHP_CodeCoverage?

**Comment by dogmatic69** [comment]
I get that it is not supported, but that does not change the fact that its broken. 

I am using a framework that only supports the 3.7.x branch of PHPUnit so I don't have an option to use a later version.

What was the point of restricting the version to < 1.3 on coverage when the 2.x branch works fine with 3.7?

**Comment by GrahamCampbell** [comment]
> What was the point of restricting the version to < 1.3 on coverage when the 2.x branch works fine with 3.7?

That wasn't known at the time though. It might not have done.

**Comment by sebastianbergmann** [comment]
I highly doubt that PHP_CodeCoverage 2.x works with PHPUnit 3.7.

**Comment by dogmatic69** [comment]
Well I can set my composer to install 3.7.14 PHPUnit which will install coverage v2.1.7 which works just fine. tests run, coverage shows and UI is not broken as described above

**Comment by GrahamCampbell** [comment]
What you mean is the small feature set you've tried to use seems to be working ok?

**Comment by dogmatic69** [comment]
> What you mean is the small feature set you've tried to use seems to be working ok?

Sure

**Comment by sebastianbergmann** [comment]
Be that as it may, there will not be a new PHPUnit 3.7 release.
