### ISSUE TITLE
Prevent any code coverage collection during single test

### ISSUE THREAD

**Issue by PatrickRose** [sebastianbergmann/php-code-coverage#354]
Hi,

I have a long running test (~4minutes) which then shoots up to 45 minutes when I start to collect code coverage. Is it possible to switch _off_ code coverage for a single test? I don't think @coversNothing does what I want (it seems to still collect the code coverage, but discard it at the end)

**Comment by sebastianbergmann** [comment]
No, `@coversNothing` does not do what you want. But maybe it should. Thanks for opening this ticket.

**Comment by sebastianbergmann** [comment]
This was implemented in https://github.com/sebastianbergmann/phpunit/commit/5487acb683b8a6bdafaa9f79bb3bc7776ef5a984.
