### ISSUE TITLE
PHP Fatal error Generating code coverage report in PHP format

### ISSUE THREAD

**Issue by abeeskau** [sebastianbergmann/php-code-coverage#358]
Our integration testsuite has increased to a point now that we are encountering memory issues.  Short of continuing to increase the memory (> 4 gig), are there recommendations to resolve this issue?:
> Generating code coverage report in PHP format ...PHP Fatal error:  Allowed memory size of 4294967296 bytes exhausted (tried to allocate 339738614 bytes) in /opt/bamboo/agents/agent1/xml-data/build-dir/acbsnip/vendor/phpunit/php-code-coverage/src/CodeCoverage/Report/PHP.php on line 38

**Comment by staabm** [comment]
@abeeskau could you provide a blackfire.io profile which shows which parts of the generation take that much memory?

**Comment by GrahamCampbell** [comment]
Sounds like maybe you're including the vendor folder by mistake?

**Comment by sebastianbergmann** [comment]
I don't have an answer for this, sorry.
