### ISSUE TITLE
Support coverage for application's annotations (e.g. Symfony2's annotation)

### ISSUE THREAD

**Issue by moroine** [sebastianbergmann/php-code-coverage#369]
Hi, 

I have a Symfony2 application using a lot of annotations to add features. In my case I have some serializations annotation who help me to quickly handle serialization feature. 

I expose an API, and returns format stability is essential. Thus I had written some unit tests to avoid regressions. I would like my code coverage report knows that I'm testing this feature.

I didn't found this is possible.

Thank you,

**Comment by sebastianbergmann** [comment]
This does not make sense to me, sorry.
