### ISSUE TITLE
Confusing statistics for source file that declares a class without methods

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/php-code-coverage#370]
![screenshot from 2015-08-12 09-04-43](https://cloud.githubusercontent.com/assets/25218/9218286/70cca0ba-40d1-11e5-9ec9-688bff3f0b8d.png)

![screenshot from 2015-08-12 09-05-50](https://cloud.githubusercontent.com/assets/25218/9218288/744428b2-40d1-11e5-92ec-07c2570a4b36.png)

**Comment by sebastianbergmann** [comment]
Instead of empty boxes `0 / 0` lines etc. should be shown.

**Comment by kelunik** [comment]
:+1:
