### ISSUE TITLE
Call to undefined method Runtime::isPHPDBG() in CodeCoverage.php on line 913

### ISSUE THREAD

**Issue by MatTheCat** [sebastianbergmann/php-code-coverage#376]
Since release 2.2.0 I cannot run any coverage as I get the error message above.

I run PHP on Ubuntu 15.04 and `php -v` returns

```
PHP 5.6.4-4ubuntu6.2 (cli) (built: Jul  2 2015 15:29:28) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2014, by Zend Technologies
    with Xdebug v2.2.6, Copyright (c) 2002-2014, by Derick Rethans
```

It's really weird because I can see in my vendor files `SebastianBergmann\Environment\Runtime::isPHPDBG()` exists.

Any idea?

**Comment by sebastianbergmann** [comment]
Maybe you haven an older, globally installed PHPUnit that interferes?

**Comment by MatTheCat** [comment]
You're right, phpunit 4.2.6 was globally installed. My bad -_-

**Comment by peterchaula** [comment]
I ran "php vendor/bin/phpunit" in my composer project root and everything works
