### ISSUE TITLE
Use function includes imported function in report

### ISSUE THREAD

**Issue by kelunik** [sebastianbergmann/php-code-coverage#378]
``` php
<?php

namespace Foo;

use function Amp\pipe;

class Foo {
    // ...
}
```

This displays `Amp\pipe` in the classes coverage report although it's just imported, not defined there.

![Coverage Report](http://i.imgur.com/CuHwiyR.png)

**Comment by sebastianbergmann** [comment]
php-token-stream interprets the `function` part of `use function` as the beginning of a function declaration.

**Comment by sebastianbergmann** [comment]
Should be fixed by https://github.com/sebastianbergmann/php-token-stream/commit/cab6c6fefee93d7b7c3a01292a0fe0884ea66644

**Comment by sebastianbergmann** [comment]
Okay, it's not fixed. This is what I get with a minimal, self-contained example:

![screenshot from 2015-09-23 17-14-59](https://cloud.githubusercontent.com/assets/25218/10049193/b4fe9322-6216-11e5-9c30-97b1b3d127f0.png)

**Comment by sebastianbergmann** [comment]
I can no longer reproduce this:

![screenshot from 2017-11-27 05-00-47](https://user-images.githubusercontent.com/25218/33250338-351c02c4-d330-11e7-8c40-32ca05b937a0.png)

![screenshot from 2017-11-27 05-00-31](https://user-images.githubusercontent.com/25218/33250339-388f15e0-d330-11e7-858e-ecd7c1a8abe7.png)
