### ISSUE TITLE
test coverage tool doesn't report code coverage for the target production code. It reports for the test code instead.

### ISSUE THREAD

**Issue by HappyRay** [sebastianbergmann/php-code-coverage#379]
e.g 
Testing this test file

I got:

php ~/phar/phpunit.phar --coverage-text /Users/ryang/github/TestScribe/tests/Unit/Utils/ClassNameUtilGenTest.php
PHPUnit 4.8.4 by Sebastian Bergmann and contributors.

Runtime: PHP 5.4.37 with Xdebug 2.2.3
Configuration: /Users/ryang/github/TestScribe/phpunit.xml

..

Time: 345 ms, Memory: 19.00Mb

OK (2 tests, 2 assertions)

Code Coverage Report:
2015-08-18 10:28:56

Summary:
Classes: 0.00% (0/122)
Methods: 0.00% (0/328)
Lines: 0.00% (0/5080)

If I remove @cover annotations I got

php ~/phar/phpunit.phar --coverage-text /Users/ryang/github/TestScribe/tests/Unit/Utils/ClassNameUtilGenTest.php
PHPUnit 4.8.4 by Sebastian Bergmann and contributors.

Runtime: PHP 5.4.37 with Xdebug 2.2.3
Configuration: /Users/ryang/github/TestScribe/phpunit.xml

..

Time: 324 ms, Memory: 19.00Mb

OK (2 tests, 2 assertions)

Code Coverage Report:
2015-08-18 10:30:42

Summary:
Classes: 0.82% (1/122)
Methods: 0.61% (2/328)
Lines: 0.28% (14/5080)

\Box\TestScribe\Utils::ClassNameUtilGenTest
Methods: 100.00% ( 2/ 2) Lines: 100.00% ( 14/ 14)

Notice that the file getting covered is the test file itself.

I reproduced the same with phpunit 4.5.1 too.

**Comment by sebastianbergmann** [comment]
Sorry to say this, but your report does not make sense to me.

**Comment by HappyRay** [comment]
Let me try to explain in more detail.

[This](https://github.com/box/TestScribe/blob/master/tests/Unit/Utils/ClassNameUtilGenTest.php) is the unit test I used in the example. 

The tests are designed to test the production code [here](https://github.com/box/TestScribe/blob/master/src/Utils/ClassNameUtil.php).

When I ran 
php ~/phar/phpunit.phar --coverage-text tests/Unit/Utils/ClassNameUtilGenTest.php

I expect to see the production code to be covered. Instead I either see no coverage or a report of the test code lines in ClassNameUtilGenTest being covered when I remove @cover annotations from the test code.  Notice that the test code has Test at the end of the file name.

Thanks
