### ISSUE TITLE
Generate Code Coverage Badge

### ISSUE THREAD

**Issue by voycey** [sebastianbergmann/php-code-coverage#381]
It would be great to have code coverage badges generated through this tool, that would mean we could host these on our own CI server without having to use secondary services like coveralls.io

**Comment by sebastianbergmann** [comment]
I don't see how this fits in this project.

**Comment by voycey** [comment]
This project generates a HTML report showing code coverage - surely this would fit this project perfectly? 
````
$writer = new PHP_CodeCoverage_Report_HTML;
$writer->process($coverage, '/tmp/code-coverage-report');
````
I use this as part of my CI stack to generate code coverage reports but as of yet unless I use something like coveralls there is no way of having a self hosted coverage badge (that I am aware of?)
