### ISSUE TITLE
PHP Fatal error: Cannot use Foo\Bar as Bar because the name is already in use

### ISSUE THREAD

**Issue by jankorichter** [sebastianbergmann/php-code-coverage#383]
```php
/*
 * Example:
 */

// in src/Model/Entity/Foo.php
namespace Model\Entity;

class Foo {
}

// in src/Model/Service/Foo.php
namespace Model\Service;

class Foo {
}

// in src/Model/Service/Bar.php
namespace Model\Service;

use Model\Entity\Foo; // raises fatal error with phpunit

class Bar {
}
```

This code is executable by PHP. PHP seems to prefer the use statement in ```src/Model/Service/Bar.php```, but PHPUnit code coverage evaluates namespace first.

**Comment by GrahamCampbell** [comment]
This doesn't work on php either? https://3v4l.org/oH9aK

**Comment by GrahamCampbell** [comment]
You need to alias `use Model\Entity\Foo;` when you import it because it conflicts with an exisiting class. The only reason you might not see the error in php is if that other class hasn't been autoloaded yet.

**Comment by jankorichter** [comment]
Yes it runs. I forget to mention the classes are autoloaded via ```spl_autoload_register```. The problem is, it is a large project, PHPUnit runs well. But now we introduced code coverage and we have to rewrite a lot to use class aliases. It is strange, that no IDE or tool has been warned about this potential problem before. :(

**Comment by jankorichter** [comment]
BTW, the main problem is: I start PHPUnit with code coverage. It takes a long time to run (without errors). But code coverage crashes with the first detected error. So I have to fix it with class aliases and wait for the next error and so on. It is very annoying and takes a lot of time :(

**Comment by sebastianbergmann** [comment]
This does not look like a bug to me.
