### ISSUE TITLE
[RFC] Remove blacklist and make whitelist mandatory

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/php-code-coverage#385]
Triggered by #384, I started thinking about how complex (and perceived by many users as complicated) the blacklist and whitelist functionality of PHPUnit and PHP_CodeCoverage is.

A radical approach to make this simpler, both for those working on PHP_CodeCoverage and those that use PHPUnit, could be to remove the blacklist and make the whitelist mandatory. Current versions of PHPUnit already emit a warning when code coverage is activated but no whitelist is configured.

Thoughts?

**Comment by michaelmoussa** [comment]
:+1: I would like this. The first thing I do in any new `phpunit.xml` is blacklist the entire project and then whitelist what I want anyway. I suspect that is the case for the overwhelming majority of projects these days.

**Comment by stof** [comment]
:+1: for this. I always use a whitelist anyway. This is even more likely in the age of composer: if you don't define a whitelist, the code coverage will include anything from your ``vendor`` folder, which is not blacklisted automatically by PHPUnit. so not using a whitelist generates wunky coverage by default for composer users.

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by fpietka** [comment]
:+1:

**Comment by MajorCaiger** [comment]
:+1:  I always use whitelist and never use blacklist

**Comment by JanPietrzyk** [comment]
+1 Black & Whitelist do not serve the purpose of clean code.

**Comment by sandermarechal** [comment]
+1

**Comment by sebastianfeldmann** [comment]
:+1:

**Comment by sebastianbergmann** [comment]
PHPUnit 5.0 has been changed: https://github.com/sebastianbergmann/phpunit/commit/0fd7f2cfb4f47288968e058bbc1bdb43331b5c40

The respective functionality will be removed from PHP_CodeCoverage 3.0 in time for the PHPUnit 5.0 release.
