### ISSUE TITLE
Risky lines occasionally reported incorrectly and on the wrong file

### ISSUE THREAD

**Issue by braiba** [sebastianbergmann/php-code-coverage#388]
Very occasionally PHPUnit reports lines of code as risky both incorrectly and on the wrong file. I can't work out the exact circumstance under which this occurs, but for my current occurrence the circumstances were:
- Line x reported as risky in class A, despite that line not being executed
- Line x from class B was executed, but should not have been reported as risky, because there was a  @uses for class B on the unit test class
- Adding a line of whitespace to class B so that the code on line x is moved to line x+1 causes line x+1 to be reported as risky in class A instead
- Adding a line of whitespace to class A so that there is no code on line x results in no lines being displayed as risky.

I believe all the times I've seen this occur, the method in class B has only been a single line, but I'm not sure. When I get back to my code I'll try adding a dummy line and see what happens.

As a general rule I'm use @coversDefaultClass on all my unit tests and most of my @uses are at the class level rather than the method level, in case that's helpful in debugging this.

**Comment by braiba** [comment]
Just had this happen again, except that this time I can't find a class B where the line number is being hit (I've removed the @uses and changed the @covers to a different method so it reports every line as risky, and that's the only instance of that line number).

In this case, the reported line is on the class that I'm testing, but it's the opening brace of a method that definitely isn't called in that test.

**Comment by Gisleburt** [comment]
I just want to confirm that making the "risky" line whitespace or a comment seems to work around the problem:

Errors:
```php
    /**
     * @throws \RuntimeException
     * @return string
     */
    public function getComposerLocation()
    {
        if (!$this->composerLocation) { // This test executed code that is not listed as code to be covered or used:
              foreach ($this->getPotentialLocations() as $potentialLocation) {
                try {
                    $this->setComposerLocation($potentialLocation);
                    return $potentialLocation;
                } catch (\Exception $e) {
                    // Do nothing, keep trying
                }
            }
            throw new \RuntimeException('Could not find composer');
        }

        return $this->composerLocation;

    }
```

Does not error:
```php

    /**
     * @throws \RuntimeException
     * @return string
     */
    public function getComposerLocation()
    {
        // Offending line now whitespace or comment, no problems here
        if (!$this->composerLocation) {
            foreach ($this->getPotentialLocations() as $potentialLocation) {
                try {
                    $this->setComposerLocation($potentialLocation);
                    return $potentialLocation;
                } catch (\Exception $e) {
                    // Do nothing, keep trying
                }
            }
            throw new \RuntimeException('Could not find composer');
        }

        return $this->composerLocation;

    }
```

The weird thing is, this was not a problem until I added a trait, and I was wondering if it might be related to class composition with the trait which _was_ being executed. The trait usage is itself managed with an `@uses` annotation.

**Comment by thomas-bickley** [comment]
Class composition does sound like a reasonable culprit. Does the line number match the line number of a line of code that's executed within the trait by any chance? And if so, does moving that line of code in the trait cause the reported line number to change?

**Comment by Gisleburt** [comment]
Yes, additionally if I move the code from the Trait down a few lines it moves the Risky warning too. I think we have a winner. :smile:

**Comment by Gisleburt** [comment]
Version info:
* PHP 5.6.16
* PHPUnit 4.8.18
* XDebug 2.3.3
* Code Coverage 2.2.4

Let me know if you need anything else.

**Comment by sebastianbergmann** [comment]
I do not understand what you are trying to report.
