### ISSUE TITLE
Bogus coverage reports with PHP 7 & PHPDBG

### ISSUE THREAD

**Issue by Majkl578** [sebastianbergmann/php-code-coverage#389]
The coverage generated under PHP 7's PHPDBG SAPI seems to be broken.

Having these two files:
Foo.php
```php
<?php
class Foo {
	const VALUE = 123;

	public function bar() {
		return self::VALUE;
	}
}
```
FooTest.php
```php
require __DIR__ . '/Foo.php';

class FooTest extends PHPUnit_Framework_TestCase {
	public function testBar() {
		$this->assertSame(Foo::VALUE, (new Foo())->bar());
	}
}
```

```
$ phpdbg7.0.0 -qrr vendor/bin/phpunit FooTest.php --coverage-html=cov --whitelist Foo.php
```

This generated coverage report says the code is not fully covered.
In this case it breaks when XDebug is loaded (but not used as coverage backend).
It also breaks when I add `int` return type to `Foo::bar()`, even without XDebug being loaded.

Tested with PHPUnit 5.0.x-dev & php-code-coverage@12259bb.

![PHP 7 coverage](https://cloud.githubusercontent.com/assets/144181/10191355/57f9110e-6773-11e5-92f4-08a1cbdc6b17.png)

**Comment by sebastianbergmann** [comment]
If the code coverage is correctly reported with PHP 5 and Xdebug then this is an issue for @staabm and/or the developers of PHPDBG.

**Comment by staabm** [comment]
Just contacted @bwoebi . We will check that

**Comment by bwoebi** [comment]
I don't know what side-effects it has when XDebug is loaded… but yeah, that's a bug in PHPDBG that return types break it… it's a quick fix, will patch it tomorrow evening.

**Comment by bwoebi** [comment]
Should be fixed with newest PHP-7.0 … may you please verify @Majkl578 (commit 6c61286da4f2d71e659da70842168d71835292f9 in php-src)

**Comment by Majkl578** [comment]
@bwoebi: Thanks, it looks ok now. :+1: 
There seem to be some other issues, one I just noticed is reporting `declare(strict_types=1);` in some cases as an uncovered line (i.e. file with an interface).
Anyway, closing this issue as it's not an issue of php-code-coverage.

**Comment by bwoebi** [comment]
@Majkl578 weird, declare() shouldn't emit any opcode...
