### ISSUE TITLE
Incomplete remove of blacklisting

### ISSUE THREAD

**Issue by evgeny-l** [sebastianbergmann/php-code-coverage#390]
Commit 12259bb1352612df9ec24048714a3bedafe79674 removes support of blacklisting, but file scripts/auto_prepend.php still contains method call.
```
$filter->addFileToBlacklist(__FILE__);
$filter->addFileToBlacklist(dirname(__FILE__) . '/auto_append.php');
```

And also it breaks support of PHPUnit in PHPStorm IDE cause it's native phpunit helper uses blacklisting. This causes errors like this:
```
PHP Fatal error:  Call to undefined method PHP_CodeCoverage_Filter::addFileToBlacklist() in ~/.phpstorm_helpers/phpunit.php on line 321
```

**Comment by evgeny-l** [comment]
As little hack.
If you are using PHPUnit 5 with its dependencies from php-code-coverage 3 and suddenly PHPStorm after composer updates throws an error, you may temporary use this hack:
```
"phpunit/php-code-coverage": "dev-master#b8436b000263f6d72fbad1d36890e247ce84857e"
```

**Comment by sebastianbergmann** [comment]
PhpStorm 9.5 has support for PHPUnit 5.

**Comment by evgeny-l** [comment]
Yes, but it's EAP version for now. I got latest 9.0.2 where problem occurs.
Thank you.

**Comment by RezNikTaylor** [comment]
Same here. I installed EAP version and it had lots of bugs. Would be nice to have it working in 9.0.2

**Comment by IlyaBakhlin** [comment]
Same f*cking problem. :sob:

**Comment by FlxPeters** [comment]
You can get PhpStorm 9.5 here http://blog.jetbrains.com/phpstorm/2015/09/phpstorm-9-5-eap-142-5282/

**Comment by myDisconnect** [comment]
Bump.

**Comment by gischy** [comment]
best workaround for now seems to be to add "phpunit/php-code-coverage": "dev-master#b8436b000263f6d72fbad1d36890e247ce84857e" to the composer.json, thanks evgeny-l

**Comment by alexislefebvre** [comment]
The upgrade to [PhpStorm 10](https://www.jetbrains.com/phpstorm/download/) solved the problem.

**Comment by IlyaBakhlin** [comment]
Actually, upgrading to PhpStorm 9.5 would solve the problem, but that version has never left the EAP status.
