### ISSUE TITLE
Recursively resolve @uses

### ISSUE THREAD

**Issue by neclimdul** [sebastianbergmann/php-code-coverage#408]
When implementing tests and using checkForUnintentionallyCoveredCode with a coverage report, things get very leaky and painful when a parent class does common cleanup operations in its setUp(). Every child classes has to maintain a set of @uses annotations to match the parent classes setUp implementation.

This is currently blocking adoption/usage of this feature in Drupal: https://www.drupal.org/node/2626832

Example:

``` php
<?php
/**
 * @uses \My\Env
 */
class UnitTestCase extends \PHPUnit_Framework_TestCase {
  public function setUp() {
    parent::setUp();
    \My\Env::reset();
  }
}

/**
 * @coversDefaultClass \My\Car
 */
class CarTest extends UnitTestCase {
  /**
   * @covers ::myMethod
   */
  public testMyMethod() {
    $tmp = new \My\Car();
    $this->assertTrue($tmp->myMethod());
  }
}
?>
```

In this example, \My\Env will be reported as unintentionally covered code.

**Comment by sebastianbergmann** [comment]
So by "recursively" you mean that `@uses` annotations should be inherited from a parent class to its child classes?

**Comment by sebastianbergmann** [comment]
No feedback, closing.
