### ISSUE TITLE
Code coverage report class hierarchy is broken, @codeCoverageIgnore is not applyed.

### ISSUE THREAD

**Issue by olegserov** [sebastianbergmann/php-code-coverage#412]
I have a file with only one test class.
Here is folded version: https://www.dropbox.com/s/sgmrvq7bt1ysdl0/Screenshot%202015-12-12%2011.14.21.png?dl=0

And here is the code-coverage report: https://www.dropbox.com/s/bvdnmbbyzvd5z3o/Screenshot%202015-12-12%2011.17.39.png?dl=0

As you can see the hierarchy is broken.

What kind of data do you need to debug this bug?

Version info: 
Generated by PHP_CodeCoverage 3.0.1 using PHP 5.6.16 and PHPUnit 5.0.8 at Sat Dec 12 19:10:09 MSK 2015.
PHP 5.6.16 (cli) (built: Nov 26 2015 08:01:30)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Xdebug v2.3.3, Copyright (c) 2002-2015, by Derick Rethans

**Comment by sebastianbergmann** [comment]
I do not understand what you are trying to report.

**Comment by olegserov** [comment]
I had an issue with the codecoverage failing to show that the file has been executed despite the actual execution of the code. It's been 3 years since I reported the bug and I don't have any ability to reproduce this issue.
