### ISSUE TITLE
Xdebug Code Coverage Crashes PHP7

### ISSUE THREAD

**Issue by joefallon** [sebastianbergmann/php-code-coverage#416]
In version 2.1.7 of php-code-coverage the line:
```
xdebug_start_code_coverage(XDEBUG_CC_UNUSED | XDEBUG_CC_DEAD_CODE) 
```
crashes the PHP process with a SIGSEGV in PHP7.

However, if you change the line to read:
```
xdebug_start_code_coverage(XDEBUG_CC_UNUSED)
```
everything is fine and it works normally. 

Also, version 3 removes the blacklist directory feature. Can you bring that back? My code relies on it in a very core way.

**Comment by GrahamCampbell** [comment]
> crashes the PHP process with a SIGSEGV in PHP7.

I've seen this too.

**Comment by sebastianbergmann** [comment]
No, the blacklist will not be brought back. It was intentionally removed. The segfault is an issue that should be reported with Xdebug.
