### ISSUE TITLE
Rest of a function or method is ignored after an anonymous function

### ISSUE THREAD

**Issue by shanept** [sebastianbergmann/php-code-coverage#424]
I have a class function 'even' in which I filter an array with an anonymous function. Without testing 'even', I can achieve 100% code coverage on this function, and 0% code coverage on the anonymous function.

![complete coverage untested](https://cloud.githubusercontent.com/assets/5936269/13277315/f49763be-db02-11e5-8eae-aba6b62b0104.png)

Obviously, if I test it I can achieve full coverage of the function. The issue seems to be related to how Code Coverage detects the end of the function, were it must be a closing brace and nothing more on a line.

The issue may be bypassed by altering Example.php to look as follows:

``` php
$numbers = array_filter($numbers,
function($number) {
    return $number % 2 === 0;
}
);
```

---

Here is the contents of my files, so you may duplicate the issue. Please note I have commented out the test in TestExample.php so it will not run. You can expect 100% coverage if the test is run.

Example.php

``` php
<?php

class Example
{
    public function even($numbers)
    {
        $numbers = array_filter($numbers, function($number) {
            return $number % 2 === 0;
        });

       return array_merge($numbers);
    }
}
```

TestExample.php

``` php
<?php
include "./Example.php";

class TestExample extends PHPUnit_Framework_TestCase
{
    /*public function testReturnsEvenNumbers()
    {
        $numbers = range(1, 10);
        $expect  = range(2, 10, 2);

        $example = new Example;
        $numbers = $example->even($numbers);

        $this->assertEquals($numbers, $expect);
    }*/
}
```

phpunit.xml.dist

``` xml
<?xml version="1.0" encoding="UTF-8" ?>
<phpunit color="true"
        convertErrorsToExceptions="true"
        convertWarningsToExceptions="true"
        convertNoticesToExceptions="true"
        stopOnFailures="false"
        syntaxCheck="false">
    <testsuites>
        <testsuite name="example">
            <file>./TestExample.php</file>
        </testsuite>
    </testsuites>
    <filter>
        <whitelist processUncoveredFilesFromWhitelist="true">
            <file>./Example.php</file>
        </whitelist>
    </filter>
    <logging>
        <log type="coverage-html" target="./coverage" />
    </logging>
</phpunit>
```

**Comment by kweber-tcc** [comment]
I can verify this bug exists in PHPUnit 5.6.2.

Generated by php-code-coverage 4.0.1 using PHP 7.0.8-0ubuntu0.16.04.3 with Xdebug 2.4.0 and PHPUnit 5.6.2 at Thu Nov 10 15:08:31 UTC 2016.

**Comment by TeddyMorningStar** [comment]
Did you fix it ? Can you help me resolve it ?

**Comment by shanept** [comment]
I have had no progress with this since opening this issue unfortunately.

**Comment by TeddyMorningStar** [comment]
I think we need use mockery unit test and I research this: http://laravel-tricks.com/tricks/unittest-closure-in-query-builder-with-mockery but implement not complete. So i hope it can help you.
