### ISSUE TITLE
Blank percentage on code coverage report with no executable lines

### ISSUE THREAD

**Issue by TomK** [sebastianbergmann/php-code-coverage#428]
Hi, This may be by design but the percentage on code coverage reports is empty when the file has no executable lines.

``` xml
<?xml version="1.0"?>
<phpunit xmlns="http://schema.phpunit.de/coverage/1.0">
  <file name="IRoute.php">
    <totals>
      <lines total="26" comments="15" code="11" executable="0" executed="0" percent=""/>
      <methods count="0" tested="0" percent=""/>
      <functions count="0" tested="0" percent=""/>
      <classes count="0" tested="0" percent=""/>
      <traits count="0" tested="0" percent=""/>
    </totals>
  </file>
</phpunit>
```

I changed this locally, but wanted to check the desired operation before submitting a PR.
In `\PHP_CodeCoverage_Util`, I added a statement to check for both values being empty, and return 100, but this should probably also run through `sprintf` if `$asString` is true.

``` php
public static function percent($a, $b, $asString = false, $fixedWidth = false)
{
    if ($a == 0 && $b == 0) {
        return 100;
    }
```

Ref: https://github.com/Shippable/support/issues/2485

**Comment by sebastianbergmann** [comment]
This is definitely a bug. However, the root problem here is that 0/0 is not really defined. Both 0% and 100% are wrong, IMHO. In the HTML report 0/0 is reported as 100% and it confuses people (see https://github.com/sebastianbergmann/php-code-coverage/issues/411#issuecomment-184267347 for instance). Making it 100% here would be consistent, though.

**Comment by TomK** [comment]
Hm, tough call.
Using interfaces as an example there is no code to execute, but providing the interface is used without fatal exception it is deemed structurally effective which indicates 100% coverage.
If the interface is not used, it's usage has not been tested and so 0% coverage should be issued.
I have no idea if the data required to determine this is available though!

**Comment by sebastianbergmann** [comment]
This was changed a while ago:

![screenshot from 2017-11-27 06-36-56](https://user-images.githubusercontent.com/25218/33252300-907b4b18-d33d-11e7-89c3-8247e1ac2089.png)

![screenshot from 2017-11-27 06-37-00](https://user-images.githubusercontent.com/25218/33252303-93616d58-d33d-11e7-9142-3f7d9d45cb45.png)
