### ISSUE TITLE
Change how files with no executable lines are displayed in the HTML report

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/php-code-coverage#432]
A file that has no executable lines is currently reported to have 0 / 0 = 100% code coverage. This is wrong and confuses a lot of people (see https://github.com/sebastianbergmann/php-code-coverage/issues/411#issuecomment-184267347, for instance).

Whatever we do for the HTML code coverage report has to be done in the XML reports as well to avoid confusion through inconsistency. This is what #428 is about.

The examples shown below are from [sebastianbergmann/money](https://github.com/sebastianbergmann/money).
## Current

![screenshot from 2016-04-20 17-42-15](https://cloud.githubusercontent.com/assets/25218/14681026/c1385426-071f-11e6-8958-e525b1aad806.png)
![screenshot from 2016-04-20 17-42-21](https://cloud.githubusercontent.com/assets/25218/14681032/c45fec22-071f-11e6-9695-c335fc40129e.png)
![screenshot from 2016-04-20 17-42-27](https://cloud.githubusercontent.com/assets/25218/14681033/c6b1ae2a-071f-11e6-8dd6-b8357ca9717f.png)
## Possibility

![screenshot from 2016-04-20 17-46-56](https://cloud.githubusercontent.com/assets/25218/14681131/22279a80-0720-11e6-887b-6a75c3197bb1.png)
![screenshot from 2016-04-20 17-47-10](https://cloud.githubusercontent.com/assets/25218/14681133/24eb2700-0720-11e6-8550-60817751cc81.png)
![screenshot from 2016-04-20 17-47-32](https://cloud.githubusercontent.com/assets/25218/14681134/26d76682-0720-11e6-8cfa-2e02b28ed0c0.png)

**Comment by MajorCaiger** [comment]
What about
- "N/A" for the percentage
- leave the 0/0 in (IMO This could be useful information, especially if the row represents a directory)
- make the row a different colour?

**Comment by sebastianbergmann** [comment]
@MajorCaiger Good idea.

![screenshot from 2016-05-04 08-18-51](https://cloud.githubusercontent.com/assets/25218/15006434/2475b72a-11d1-11e6-958e-60768d8d3617.png)
![screenshot from 2016-05-04 08-19-18](https://cloud.githubusercontent.com/assets/25218/15006438/27fcec60-11d1-11e6-91fe-a2082e4c31f6.png)
![screenshot from 2016-05-04 08-19-31](https://cloud.githubusercontent.com/assets/25218/15006439/2ad9ae78-11d1-11e6-8d18-3495a03ede09.png)

**Comment by sebastianbergmann** [comment]
The following cases still need to be addressed:
![screenshot from 2016-05-04 08-21-47](https://cloud.githubusercontent.com/assets/25218/15006463/7e9ecc96-11d1-11e6-937c-2260bed2a05e.png)
![screenshot from 2016-05-04 08-21-51](https://cloud.githubusercontent.com/assets/25218/15006465/81f68ca8-11d1-11e6-9da0-013dd275ba1c.png)
![screenshot from 2016-05-04 08-22-04](https://cloud.githubusercontent.com/assets/25218/15006466/83fbe43a-11d1-11e6-95b1-81adddc7f959.png)
