### ISSUE TITLE
Dashboard charts not showing tooltips for data points

### ISSUE THREAD

**Issue by robations** [sebastianbergmann/php-code-coverage#440]
**Expected**: to see a tooltip, when mousing over each datapoint in the complexity charts, that shows the class or method to which it refers.

**Actual**: No tooltip and an error message in the console:

    nv.addGraph(function() {
      var chart = nv.models.scatterChart()
        .showDistX(true)
        .showDistY(true)
        .showLegend(false)
        .forceX([0, 100]);
      chart.tooltipContent(function(key, y, e, graph) {
        return '<p>' + graph.point.class + '</p>'; /// dashboard.html:435 Uncaught TypeError: Cannot read property 'point' of undefined
      });

No error messages appear while generating the reports. This is a problem for all data points on both class and method complexity charts.

I originally had the problem with phpunit 4.x / php-code-coverage 2.x, then upgraded to phpunit 5 /php-code-coverage 3, and had the same problem on both configurations. Attempts to debug JS were thwarted by minified code.

v3.3.3

**Comment by vjandrea** [comment]
Tooltips don't work on the Methods Complexity graph, while they do in the Class Complexity graph.

In the browser's console I can see:
```
nvd3 warning: `tooltips` has been deprecated.  use chart.tooltip.enabled() instead 2 nv.d3.min.js:2:1193
nvd3 warning: `tooltipContent` has been deprecated.  use chart.tooltip.contentGenerator() instead 2 nv.d3.min.js:2:1193
Uncaught TypeError: i is null d3.min.js:2:10331
    <trace removed>
```
Triggered in line 544 of dashboard.html by
```
d3.select('#methodComplexity svg')
      .datum(getComplexityData([<removed>], 'Method Complexity'))
      .transition()
      .duration(500)
      .call(chart);
```

versions used: 
php-code-coverage 9.2.5
PHP 7.4.12
Xdebug 3.0.1
PHPUnit 9.5.2
