### ISSUE TITLE
Large coverage % drop under phpdbg for PHP 7.0.7

### ISSUE THREAD

**Issue by ezzatron** [sebastianbergmann/php-code-coverage#443]
When running under phpdbg for PHP 7.0.6, my project has 100% coverage. Under phpdbg for PHP 7.0.7, it drops to around 60%.

At this stage it looks like a very strange bug with phpdbg, and probably cannot be worked around. Please see [krakjoe/phpdbg#156](https://github.com/krakjoe/phpdbg/issues/156) for a possible cause.

**Comment by Jean85** [comment]
I'm probably getting this bug too. I will try PHP 7.0.8 to see if the bug gets resolved.

**Comment by Jean85** [comment]
I rebuild the Docker container that I use for development using PHP 7.0.8, and the coverage got back to normal. I'm not 100% sure that the report is bug free, but this issue seems resolved.

Using PHPUnit 5.4.6 and
```
phpdbg 0.5.0 (built: Jun 23 2016 23:51:42)
PHP 7.0.8, Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.8, Copyright (c) 1999-2016, by Zend Technologies
```

**Comment by ezzatron** [comment]
Pretty conclusive at this point that this is a phpdbg bug, and the solution is to use a newer version of phpdbg.
