### ISSUE TITLE
Error when running unit test with code coverage

### ISSUE THREAD

**Issue by Henk8** [sebastianbergmann/php-code-coverage#444]
After updating to phpunit 5.4.2 and codecoverage 4.0.0 the following error is given:

Argument 1 passed to PHPUnit_Framework_TestResult::setCodeCoverage() must be an instance of SebastianBergmann\CodeCoverage\CodeCoverage, instance of Codeception\Coverage\DummyCodeCoverage given

The error occurs when running phpunit with the following arguments:  --coverage-xml --coverage-html --xml

**Comment by sebastianbergmann** [comment]
Seems to be a Codeception issue.

**Comment by thyseus** [comment]
I solved the problem. You need to assure that the globally installed version is compatible with the phpunit version inside the project you are working on. I did the following:

```
composer global require "codeception/codeception=dev-master"
composer global require "codeception/specify=dev-master"
composer global require "codeception/verify=dev-master"
```

followed by the same in the project directory:

```
composer require "codeception/codeception=dev-master"
composer require "codeception/specify=dev-master"
composer require "codeception/verify=dev-master"
```

which made the versions compatible. Everything is working fine now.

**Comment by sebastianbergmann** [comment]
Never ever mix a global installation of PHPUnit with a per-local version of PHPUnit (or its dependencies).
