### ISSUE TITLE
Show method's cyclomatic complexity + number of tests

### ISSUE THREAD

**Issue by afilina** [sebastianbergmann/php-code-coverage#445]
For each method, show cyclomatic complexity and number of tests right next to it.

It would be useful for people to know not only that they covered all the paths, but that they didn't duplicate efforts and only wrote as many tests as were necessary.

I'll try to get on this, but just wanted to throw the idea out in case someone would like to implement this sooner.

**Comment by sebastianbergmann** [comment]
The cyclomatic complexity is already taken into consideration for the CRAP metric which is displayed. I am not sure whether there is value in displaying the number of tests that exercise a method.

**Comment by afilina** [comment]
I was thinking more along the lines of showing people whether they're creating unnecessary tests. When I teach unit testing, a lot of people assume that they need to test permutations, which means that they write a lot more tests that they need, which then frustrates them and they give up on testing later on. This metric can be of great value, especially to beginner testers.

**Comment by beporter** [comment]
I agree with Anna. This information seems to already be crudely available in the tooltip boxes that appear when you hover over individual lines in the coverage report, but you'd have to count the tests listed there manually and you have to know that you can even see those covering tests by hovering over a line. Providing a **Num. Tests** column in the report itself would be helpful in quickly identifying spots where there may be unnecessary redundancy in your tests.

**Comment by sebastianbergmann** [comment]
I do not believe that you can identify redundancy in a test suite just by using the number of tests that exercise a method, sorry.
