### ISSUE TITLE
Completely misleading code coverage - showed 100% instead of 0%

### ISSUE THREAD

**Issue by mnabialek** [sebastianbergmann/php-code-coverage#453]
Info about code coverage is completely misleading sometimes.

For example:

![100](https://cloud.githubusercontent.com/assets/7656807/16539469/8ee09f52-4044-11e6-9678-98dae30cc143.jpg)

the 1st file is green (showed 100%) however as you see without any reason there's 0/0 line showed here. In fact this is file with many lines and no tests created for this class but if you look at code coverage you might think there's full coverage for this while whereas there's none.

PHP 7.0.3
Xdebug v2.4.0RC4,
phpunit/php-code-coverage             4.0.0 
phpunit/phpunit                       5.4.6

**Comment by sebastianbergmann** [comment]
Please use a stable version of Xdebug (there were quite a few fixes in Xdebug since 2.4.0RC4).

**Comment by mnabialek** [comment]
@sebastianbergmann Thank you for reply. I've just verified it with other configuration:

PHP 7.0.8
Xdebug v2.4.0
phpunit/php-code-coverage  4.0.0 
phpunit/phpunit 5.4.6

and I'm getting exactly same result.

Also when I go into dashboard I don't have this DatatablesQueryParser method/class listed anywhere

**Comment by mnabialek** [comment]
Also what's interesting, when I've added new test to test this DatatablesQueryParser. In this class I have 2 method + constructor. In test I've only created object (those methods are not launched) and now it looks like this:

![100 -2](https://cloud.githubusercontent.com/assets/7656807/16540893/c075375a-4074-11e6-8d6a-5a1be01b8459.jpg)

As you see now 4/4 is displayed.

And going into this class details I'm getting:
![lines](https://cloud.githubusercontent.com/assets/7656807/16540898/cf7d348c-4074-11e6-8afc-bc9920a75417.jpg)

As you see only for contructor there is 4/4, but for other methods there is 0/0 displayed as lines (but functions/methods are displayed as 100%)

**Comment by steadweb** [comment]
+1 this, in dev, I've rolled back to PHP 5.6 which works fine.

**Comment by Rockstar04** [comment]
This seems similar to issue #422

**Comment by samsonasik** [comment]
duplicate with #411 also

**Comment by romainneutron** [comment]
Should be closed in favor of #411

**Comment by sensorario** [comment]
Same issue here:

phpunit/php-code-coverage          5.2.2   Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator          1.4.2   FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template          1.2.1   Simple template engine.
phpunit/php-timer                  1.0.9   Utility class for timing
phpunit/php-token-stream           2.0.1   Wrapper around PHP's tokenizer extension.
phpunit/phpunit                    6.3.0   The PHP Unit Testing framework.
phpunit/phpunit-mock-objects       4.0.4   Mock Object library for PHPUnit



PHP 7.1.8 (cli) (built: Aug  7 2017 15:02:45) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.5.0, Copyright (c) 2002-2016, by Derick Rethans

**Comment by sensorario** [comment]
Fixed upgrading xdebug. Thanks

**Comment by Rockstar04** [comment]
@sensorario What version of XDebug fixed this issue?

**Comment by GrahamCampbell** [comment]
Newest is 2.5.5, so try that.

**Comment by sensorario** [comment]
```
$ php -v
PHP 7.1.8 (cli) (built: Aug  7 2017 15:02:45) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans
```

**Comment by nynka** [comment]
Thanks guys, I had the same issue and the latest setup fixed it. :+1:

```
$ php -v
PHP 7.1.9 (cli) (built: Aug 30 2017 18:34:46) ( ZTS MSVC14 (Visual C++ 2015) x64 )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans
```
