### ISSUE TITLE
Dashboard does not handle namespaced classes properly

### ISSUE THREAD

**Issue by kperry42** [sebastianbergmann/php-code-coverage#455]
When using code coverage on a namespaced class hierarchy, the Dashboard page's "Project Risks" lists (for both classes and methods) are built from data that is indexed using the un-namespaced names of the classes - for instance "Foo", for a class whose fully-qualified name is "\My\Package\Foo".  Thus, if you have two classes with the same name in different namespaces within the hierarchy, only one of them ends up in the Project Risks list.  For instance, if you have both "\My\Package\Foo" and "\My\OtherPkg\Foo", only the one that gets processed last will be shown in the class project risks.  And if they both have methods with the same name (say, Foo::get()), then only one of those methods will be reported in the method project risks list.

Seen in output "generated by php-code-coverage 4.0.0 using PHP 5.6.5 with Xdebug 2.2.7 and PHPUnit 5.4.6".

**Comment by sebastianbergmann** [comment]
I am able to reproduce this.

```
.
├── phpunit.xml
├── src
│   ├── autoload.php
│   ├── bar
│   │   └── Baz.php
│   └── foo
│       └── Baz.php
└── tests
    └── Test.php
```

#### `phpunit.xml`
```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/6.4/phpunit.xsd"
         bootstrap="src/autoload.php"
         verbose="true">
    <testsuite>
        <directory suffix="Test.php">tests</directory>
    </testsuite>

    <filter>
        <whitelist processUncoveredFilesFromWhitelist="true">
            <directory suffix=".php">src</directory>
        </whitelist>
    </filter>
</phpunit>
```
#### `foo/Baz.php`
```php
<?php
namespace foo;

class Baz
{
    public function m()
    {
        return true;
    }

    public function n()
    {
        return true;
    }
}
```
#### `bar/Baz.php`
```php
<?php
namespace bar;

class Baz
{
    public function m()
    {
        return true;
    }

    public function n()
    {
        return true;
    }
}
```
#### `tests/Test.php`
```php
<?php
use foo\Baz as FooBaz;
use bar\Baz as BarBaz;

class Test extends PHPUnit\Framework\TestCase
{
    public function testOne()
    {
        $foo = new FooBaz;
        $bar = new BarBaz;
        
        $this->assertTrue($foo->m());
        $this->assertTrue($bar->m());
    }
}
```
#### Screenshot
![screenshot from 2017-11-27 09-06-18](https://user-images.githubusercontent.com/25218/33256534-b54c6138-d352-11e7-8505-1849076ff152.png)
