### ISSUE TITLE
Coverage includes everything if non-existent file specified in filter (phar only)

### ISSUE THREAD

**Issue by nazar-pc** [sebastianbergmann/php-code-coverage#456]
### Preparation (creating phar version of php-code-coverage):

``` bash
composer require phpunit/php-code-coverage
```

``` php
<?php
$phar = new Phar('php-code-coverage.phar');
$phar->startBuffering();
$phar->buildFromDirectory(__DIR__.'/vendor');
$phar->setStub(
    <<<STUB
<?php
Phar::mapPhar('php-code-coverage.phar');
require_once 'phar://php-code-coverage.phar/autoload.php';
__HALT_COMPILER();
STUB
);
$phar->stopBuffering();
```
### Test case

``` php
<?php
require_once __DIR__.'/php-code-coverage.phar';

$filter = new \SebastianBergmann\CodeCoverage\Filter;
$filter->addFileToWhitelist(__DIR__.'/non-existent-file');

$coverage = new \SebastianBergmann\CodeCoverage\CodeCoverage(null, $filter);
$coverage->start('XYZ');

$coverage->stop();
print_r($coverage->getData(true));
```
### Expected output

```
Array
(
)
```
### Actual output

Huge array with files from `phar:///.../php-code-coverage.phar/...`
### Additional info

Doesn't occur if `require_once __DIR__.'/php-code-coverage.phar';` replaced with `require_once __DIR__.'/vendor/autoload.php';`.

Sample repository to reproduce an issue easily: https://github.com/nazar-pc/php-code-coverage-bug

```
PHP 7.0.8-3ubuntu1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.8-3ubuntu1, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans
```

**Comment by nazar-pc** [comment]
Looks like at least `file_exits()` is needed here: https://github.com/sebastianbergmann/php-code-coverage/blob/4712fc6b1328d62c5da00316e0c16d4f2147fed1/src/Filter.php#L49
Also `realpath()` doesn't work with Phar (also my use case).

**Comment by sebastianbergmann** [comment]
Why do you create a PHAR of php-code-coverage? To simulate usage of php-code-coverage from within a PHPUnit PHAR?

**Comment by nazar-pc** [comment]
I'm bundling it within source tree of another project and don't like to bundle a lot of files, so Phar seemed like a logical choice. Also when doing updates I only need to swap single binary rather that lots of text files that pollute changelog.

**Comment by sebastianbergmann** [comment]
Thank you for the explanation. However, as I already mentioned in https://github.com/sebastianbergmann/php-code-coverage/pull/457#pullrequestreview-23853064, I do not want to add a `file_exists()` check.

**Comment by nazar-pc** [comment]
The issue really is that `realpath()` of non-existing directory results in an empty string, which I believe is not what you want anyway.
