### ISSUE TITLE
Ignoring all lines of code in a file for coverage report

### ISSUE THREAD

**Issue by MrHash** [sebastianbergmann/php-code-coverage#459]
Hi, I cannot seem to ignore lines of code in test fixture data using `@codeCoverageIgnore` whether in the form of:

```
/**
 * @codeCoverageIgnore
 */
```

or 

```
// @codeCoverageIgnore
```

I have also tried using the start/end alternatives and returning after setting a variable. Could someone explain how to do this please? as it's counting the ignored lines as relevant. We are using PHPUnit 5.4.8.

Here is an example where >350 lines of code are considered relevant.
https://github.com/honeybee/honeybee/blob/master/testing/unit/Projection/EventHandler/Fixture/relation_projection_update_test_1.php

**Comment by MrHash** [comment]
For now i've got around the issue by excluding the files in configuration...

**Comment by sebastianbergmann** [comment]
I cannot reproduce this, sorry.
