### ISSUE TITLE
PHP 7.0 with xdebug in webserver mode can't send http-response after $codeCoverage->start()

### ISSUE THREAD

**Issue by SmetDenis** [sebastianbergmann/php-code-coverage#461]
Hi,

It seems I found a strange bug wit PHP 7.0 + xdebug and cli-server

I create simple web-server on travis 

``` sh
#!/usr/bin/env sh
php -S "localhost:8888" -t "./www" "./www/index.php" &
sleep 3s
```

My `./www/index.php` contains the code

``` php
<?php
require_once __DIR__ . '/../vendor/autoload.php';

if (class_exists('SebastianBergmann\CodeCoverage\CodeCoverage')) {
    $codeCoverage = new SebastianBergmann\CodeCoverage\CodeCoverage();
} else {
    $codeCoverage = new PHP_CodeCoverage();
}

$codeCoverage->start('id-42', true); //  It seems the fail is here
echo "ok";
$codeCoverage->stop();
```

And after that I try to load url via curl
`curl -S http://localhost:8888` show  error `(52) Empty reply from server`

So, if we have PHP7.0.9+xdebug 2.4.0, curl fails

Other PHP versions and PHP7 without xdebug work fine. 
I don't know what was happened and couldn't understand it (I tried).

---

I created clean repo to demo it - https://github.com/SmetDenis/phpcov-test
And results on travis - https://travis-ci.org/SmetDenis/phpcov-test/builds/149778135
Here fatal error - https://travis-ci.org/SmetDenis/phpcov-test/jobs/149778139#L191
PHP 5.6 + xdebug is OK - https://travis-ci.org/SmetDenis/phpcov-test/jobs/149781058#L189

I think it happens on [this line](https://github.com/SmetDenis/phpcov-test/blob/5d92d42f85aad16dad0c188aeb8f805555a2b1e5/www/index.php#L21)

After `$codeCoverage->start()` PHP built-in server can't send any http-response

I repeated the bug on 4.0.1 and 2.2.4 versions only on linux with travis-ci
BUT my Windows7x64 + PHP 7.0.9 + xdebug 2.4.0 works fine!

---

This bug does not allow me to do [Coverage Catcher](https://github.com/JBZoo/PHPUnit/blob/6ad10f04131b330d9f6df7bf9ee90ac026b48db1/src/CovCatcher.php) with [fake-index.php](https://github.com/JBZoo/PHPUnit/tree/6ad10f04131b330d9f6df7bf9ee90ac026b48db1/bin)

It helps me to collect coverage information of any included files or extentions in CMS on travis and local.

Thanks for your help and best regards,
Denis Smetannikov.

**Comment by ergonlogic** [comment]
Try upgrading to xdebug 2.4.1. Apparently xdebug 2.4.0 seg faults under such circumstances.

**Comment by sebastianbergmann** [comment]
No feedback, closing.
