### ISSUE TITLE
Code coverage hanging

### ISSUE THREAD

**Issue by elrossco22** [sebastianbergmann/php-code-coverage#472]
Hi,

I'm currently experiencing problems running the following command on our CI server
../vendor/bin/phpunit --coverage-xml $TRAVIS_BUILD_DIR/coverage --testsuite=unit

The tests finish and then the it hangs with the output
Generating code coverage report in PHPUnit XML format …

We have tried running both PHP 7 and PHP 5.6 ( we have been made aware PHPUnit does not support PHP 7) and running PHPUnit version 4.8.27, 

Does anyone know what might be causing this ?

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry.
