### ISSUE TITLE
Out of memory errors with phpdbg coverage

### ISSUE THREAD

**Issue by yuloh** [sebastianbergmann/php-code-coverage#474]
Hello,

While generating coverage data with phpdbg, I am experiencing an issue where php's memory usage climbs exponentially until exhaustion.  This only happens in some cases and depends on the code being tested or executed in the test.

Reproduction steps:

```bash
git clone https://github.com/yuloh/phpdbg-bug-demo/tree/fix-test
cd phpdbg-bug-demo
composer install
phpdbg -qrr vendor/bin/phpunit --coverage-text
```

Expected results:

The tests should run and generate coverage.

Actual results:

If the `memory_limit` is set, the tests will quickly reach the memory limit and the process is killed.
If the `memory_limit` is set to `-1`, the tests will slowly consume more memory while using > 90% CPU.

I raised the issue with phpdbg here:

https://github.com/krakjoe/phpdbg/issues/159

if I'm understanding correctly, phpdbg's oplog is being passed `SebastianBergmann\RecursionContext\Context::containsArray`.  The call itself generates more opcodes, causing an infinite loop.

**Comment by bwoebi** [comment]
Note: I'd actually report this to RecursionContext/Exporter repository as it uses an O(n^2) loop for this.
There really should be a way doing this in O(n).

It just happened to be an issue exposed by coverage, but it's not directly related.

**Comment by yuloh** [comment]
ah ok, thanks.  I will move this over there.
