### ISSUE TITLE
Bug With Whitelist

### ISSUE THREAD

**Issue by GinoPane** [sebastianbergmann/php-code-coverage#476]
Hello.
Recently I had an issue with 0 code coverage on the project running on Mac Os, whilst everything was fine on Windows.

The reason was in case-sentivity of unix-like systems. But the whitelist still accepts directories with wrong names:
![image](https://cloud.githubusercontent.com/assets/3897579/19785253/a697c3c0-9c90-11e6-8c8a-b2c40323bf81.png)
I've var-dumped in CodeCoverage/Filter:

```
   /**
     * Returns whether this filter has a whitelist.
     *
     * @return bool
     */
    public function hasWhitelist()
    {
        var_dump($this->whitelistedFiles); die();
        return !empty($this->whitelistedFiles);
    }
```

I think, whitelist should not accept such directories and it would be better to show an error, like the whitelist is empty. Because later it falls into zero percent code coverage, though no errors are shown:

![image](https://cloud.githubusercontent.com/assets/3897579/19785384/18b19cec-9c91-11e6-94cb-01224c5718f7.png)

P.S. Though, `file_exists` for this files also returns `true`, then maybe code coverage skips these files somewhere later, because if I change directories' names in the whitelist to capitalised names, then everything works.

**Comment by GinoPane** [comment]
A small problem with getting the real directory name for a file. I ran o this while investigating php-code-coverage's code.

On my system running Mac Os I have a structure like this:

    project/src/Directory/FileName.php

The directory is whitelisted for code coverage like this (note the case):

    <filter>
       <whitelist processUncoveredFilesFromWhitelist="false">
          <directory suffix=".php">./src/directory/</directory>
       </whitelist>
    </filter>

And the file is being added to whitelist array like this:

    <full_path>/project/src/directory/FileName.php

So directory names are different in reality and in whitelist array. Note, that such different names are valid for MacOs, that's why no error is being shown, as it might be for an empty whitelist.

The most interesting part comes next. In CodeCoverage::append() the method applyListFilter is being called:

 `$this->applyListsFilter($data);`

Which at the end comes to (Filter::isFiltered):

`return !isset($this->whitelistedFiles[$filename]);

And `$filename` here has a really valid path:
`<full_path>/project/src/Directory/FileName.php

And due to inequality of `Directory` and `directory` valid files are being filtered out though they are in whitelist.

I'm thinking about the solution right now.

**Comment by sebastianbergmann** [comment]
I do not understand what you are trying to report.
