### ISSUE TITLE
Much different code coverage on PHP 5.6 and 7.0

### ISSUE THREAD

**Issue by kocsismate** [sebastianbergmann/php-code-coverage#477]
Hey,

I am having a rather weird issue:

When running the test suite of my project on Travis CI on PHP 5.6, I get 13% less coverage than on PHP 7. Nothing changed between the builds except of the travis.yml file:
- PHP 5.6 (with Xdebug 2.2.7): https://travis-ci.org/woohoolabs/yin/jobs/171307319
- PHP 7.0 (with Xdebug 2.4.1): https://travis-ci.org/woohoolabs/yin/jobs/171305194

And here are all the classes where the coverage has changed:
https://scrutinizer-ci.com/g/woohoolabs/yin/inspections/efafe054-f61a-4d9a-91c6-829099363ce2/code-structure/test-coverage

Can you tell me what the reason of this confusing phenomenon? Which coverage is accurate?

**Comment by GinoPane** [comment]
Hello!
Have you checked code coverage results manually? In html report, for example. Just check files with differences and see, what's changed. 
I assume, that some bugs were fixed for PHP7 and newer xDebug, that's why you got more points with them.

**Comment by kocsismate** [comment]
The local test confirmed the prior coverage results and the difference mainly comes from the coverage of exception classes. You can see it among the 10-20 examples, you can see one here:

https://scrutinizer-ci.com/g/woohoolabs/yin/inspections/efafe054-f61a-4d9a-91c6-829099363ce2/code-structure/class/WoohooLabs%5CYin%5CJsonApi%5CException%5CDataMemberMissing?expandCoverage=1

The `getErrors()` method became "Not Executed". Interestingly, this part was white when generating the coverage locally. What could it mean?

I believe they should be red (but at least green) because I don't think I ever run those methods in my test suite.

**Comment by GinoPane** [comment]
> The getErrors() method became "Not Executed". Interestingly, this part was white when generating the coverage locally. What could it mean?

I thinks, that's ok. I mean, not executed code should be red, not white. White means, that code _can't_ be executed at all. And it's ok for declarations and so on, but not for valid code. 

You can update your test suite in order to make `getErrors()` executable and see if it changes to green. It would mean, that everything's ok with this part now.

**Comment by kocsismate** [comment]
Sorry, I didn't have time to test it, but I have good news:

I've just updated to PHPUnit 6.0 (and I now run tests on PHP 7.1) and code coverage went back to the original percentage! So I am closing the ticket. :)
