### ISSUE TITLE
trigger_error() automatically upgraded to an Exception

### ISSUE THREAD

**Issue by CJDennis** [sebastianbergmann/php-code-coverage#481]
Is there a way to mark a test to **not** upgrade trigger_error() to an Exception? I agree that in principle warnings should throw Exceptions but it would be handy to say "I *expect* this *particular* test to generate a warning but still continue", i.e. the *desired* behaviour is that it should generate a warning without failing.

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md#reporting-issues) have been reported on the [phpunit](https://github.com/sebastianbergmann/phpunit) project.

**Comment by CJDennis** [comment]
Sorry about that. I opened it here because originally it was about code coverage telling me that the code immediately after trigger_error() was not executed, yet there's no way to enable that without changing the whole testing environment.
