### ISSUE TITLE
Information request - Max execution time

### ISSUE THREAD

**Issue by sharky98** [sebastianbergmann/php-code-coverage#483]
Hello,

I'm using Codeception to run my tests. Lately I have some issues when I add too much tests (123 tests total, but it start showing errors at 118 tests). I've got a Maximum Execution Time of 30 secondes exceeded. This happen only when doing code coverage. I'm trying to figure out how this 30 is getting put in place, since PHP manuel tell us that time out is hard-coded to 0 for CLI script... Any info that could help me debug are appreciated.

On my automated test machine, it fail at the end when the test are completed with the line `Fatal error: Maximum execution time of 30 seconds exceeded in /builds/[appBuildPath]/vendor/phpunit/php-token-stream/src/Token/Stream.php on line 370` showing less than 1 second after my test are completed. On my local machine, it fail randomly with something similar: `Fatal error: Maximum execution time of 30 seconds exceeded in C:\[appBuildPath]\vendor\symfony\symfony\src\Symfony\Component\Config\Resource\DirectoryResource.php on line 72`

You can check out https://github.com/Codeception/Codeception/issues/3720 for the whole detail on my config files.

**Comment by sebastianbergmann** [comment]
Memory Limit (`memory_limit=-1`) and Maximum Execution Time (`max_execution_time=0`) should be disabled.
