### ISSUE TITLE
Finally being marked as uncovered

### ISSUE THREAD

**Issue by gmillsap** [sebastianbergmann/php-code-coverage#484]
I found this happening when a finally block uses a return statement.

Example:

`class FinallyBlock`
`{`
    `public function check(callable $fn) {`
        `try {`
            `$fn();`
        `} catch(\Exception $e) {`
            `echo 'exception';`
        `} finally {`
            `return 'a';`
        `}`
    `}`
`}`
``
`class FinallyBlockTest extends \PHPUnit_Framework_TestCase`
`{`
`    public function testCheck() {`
`        $block = new FinallyBlock();`
`        $block->check(function() {});`
`        $block->check(function() {`
`            throw new \Exception();`
`        });`
`    }`
`}`

**Comment by sebastianbergmann** [comment]
@derickr Does Xdebug not handle `finally` correctly?

**Comment by derickr** [comment]
It should with the latest versions.

**Comment by sebastianbergmann** [comment]
@gmillsap Which version of Xdebug are you using?

**Comment by gmillsap** [comment]
Xdebug 2.4.0

**Comment by sebastianbergmann** [comment]
@gmillsap In case the problem persists with Xdebug 2.4.1: please also try Xdebug 2.5.0RC1.

**Comment by gmillsap** [comment]
Tried with 2.5.0RC1 to no avail. Finally still showing as not covered when returning.

**Comment by gmillsap** [comment]
Tried with 2.4.1 and 2.5.0RC1 to no avail. Finally still showing as not covered when returning. I also want to note with 2.4.1+ I started seeing a lot of method closing braces being flagged as not covered.

**Comment by sebastianbergmann** [comment]
I think it is fair to say at this point that this is an issue with Xdebug, so I am closing this ticket. Please open a ticket at https://bugs.xdebug.org/my_view_page.php for @derickr to work on.
