### ISSUE TITLE
Problems in coverage with xdebug and uopz

### ISSUE THREAD

**Issue by mougrim** [sebastianbergmann/php-code-coverage#489]
I have wrong coverage if uopz is enabled.
See https://github.com/mougrim/coverage-problem
https://travis-ci.org/mougrim/coverage-problem/builds/179891288
I reproduced it for uopz-5.0.1 and Xdebug 2.4.0 or 2.5.0rc2-dev (from master).
So, with uopz (wrong):
![with uopz](https://cloud.githubusercontent.com/assets/1057709/20743980/5c6581ce-b6ea-11e6-8fbe-cf8b92f49e80.png)
Without uopz (right):
![without uopz](https://cloud.githubusercontent.com/assets/1057709/20743989/6a73c06e-b6ea-11e6-907a-692e79ebcfe4.png)

PHP 7.0.7 (and PHP 7.0.13-1+deb.sury.org~trusty+1)
PHPUnit 5.6.7 by Sebastian Bergmann and contributors.

**Comment by sebastianbergmann** [comment]
This is not an issue with this component, sorry.
