### ISSUE TITLE
Coverage ignore single line php blocks

### ISSUE THREAD

**Issue by sebaks** [sebastianbergmann/php-code-coverage#493]
Coverage ignore single line php block. 
In this case coverage is 100% but code is incorrect.  Is it normal?

```php
<?php if (true): ?>
    <?php
    'norm work';
    ?>
<?php else: ?>
    <?php callBadFunctions(); // Not existing function. Fatal error: Call to undefined function callBadFunctions()  ?>
<?php endif; ?>
```
Screenshot http://joxi.ru/BA0Ox11Cj54W2y
Generated by php-code-coverage 4.0.3 using PHP 5.6.29-1+deb.sury.org~trusty+1 with Xdebug 2.5.0 and PHPUnit 5.7.0

**Comment by sebastianbergmann** [comment]
I do not understand what you are trying to report.
