### ISSUE TITLE
Running phpunit with code coverage fatal errors because of max execution time

### ISSUE THREAD

**Issue by steadweb** [sebastianbergmann/php-code-coverage#507]
Recently I've been unable to generate code coverage for a project I work on. The whitelist contains a directory (`src`) which contains a lot of PHP classes. Running `phpunit` _without_ coverage works _fine_. 

If I'm explicit with the directories / files within the whitelist, and reduce the amount to 5 directories, then coverage works, but it doesn't give me complete coverage of `src/*`. 

`phpunit.xml` configuration below:

```
<?xml version="1.0" encoding="UTF-8"?>
<phpunit
        backupGlobals="false"
        backupStaticAttributes="false"
        colors="true"
        convertErrorsToExceptions="true"
        convertNoticesToExceptions="true"
        convertWarningsToExceptions="true"
        processIsolation="false"
        stopOnFailure="false"
        stopOnSkipped="false"
        syntaxCheck="false"
        bootstrap="bootstrap.php">

    <testsuites>
        <testsuite name="cmp">
            <directory>.</directory>
        </testsuite>
    </testsuites>

    <filter>
        <whitelist processUncoveredFilesFromWhitelist="true">
            <directory>../../src</directory>
        </whitelist>
        <blacklist>
            <directory>../../src/ext</directory>
            <directory>../../src/DAV</directory>
        </blacklist>
    </filter>
    <logging>
        <log type="coverage-clover"
             target="../../build"
             charset="UTF-8"
             yui="true"
             highlight="true"
             lowUpperBound="50"
             highLowerBound="80"
        />
    </logging>
</phpunit>
```

I've just upgraded from phpunit `4.x` to `5.x`, and `4.x` behaves exactly the same way. (Please ignore the warnings below). 

Command below, I've explicitly set the `max_execution_time` to `0` and `memory_limit` to `-1`

```$ php ./vendor/bin/phpunit -d max_execution_time=0 -d memory_limit=-1 -c ./tests/unit/phpunit.xml ./tests/unit/```

Results below, as you can see, it fatal errors half way through. 

```
PHPUnit 5.7.13 by Sebastian Bergmann and contributors.

.........WWWWWWW...................WWWWWWWWWWWWWWWWWWWWWW....   61 / 1361 (  4%)
...........................................WW................  122 / 1361 (  8%)
...........................II................................  183 / 1361 ( 13%)
.............................................................  244 / 1361 ( 17%)
.............................................................  305 / 1361 ( 22%)
...............................WW.....................WWWWWWW  366 / 1361 ( 26%)
WWWWWW.......................................................  427 / 1361 ( 31%)
......................................WWWWWW......WWWWWWWWWWW  488 / 1361 ( 35%)
WWWWWWWWWWWWWWWWWW...........................................  549 / 1361 ( 40%)
......................................................WWWWWWI  610 / 1361 ( 44%)
I..WWWWWWWWWW................................................  671 / 1361 ( 49%)
.............................................................  732 / 1361 ( 53%)
...............................................
Fatal error: Maximum execution time of 100 seconds exceeded in
```

PHP information (with Xdebug enabled)

```
PHP 5.6.30 (cli) (built: Jan 19 2017 10:06:11) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.5.0, Copyright (c) 2002-2016, by Derick Rethans
```

And `max_execution_time` within loaded `php.ini`.

```
$ php -i | grep max_execution_time
max_execution_time => 0 => 0
```

Any indication of where this limit may come from would help, as I've grep'd the project, looking for instances where `max_execution_time` is set, yet nothing is returned (both in my project `src` and its dependencies, i.e. `vendor/*`).

**Comment by sebastianbergmann** [comment]
I am sorry, but this does not appear to be a problem with PHPUnit or this component. Clearly PHP has a `max_execution_time` configured which causes the abortion of the execution.

**Comment by steadweb** [comment]
Thank you for your time @sebastianbergmann, and you were right. 

I was naive to think that the only way to set `max_execution_time` was via `ini_set`, and hadn't considered `set_time_limit`. I've found the offending line and indeed, this was the cause.

**Comment by FarukOne** [comment]
Hello, I also get the same problem, Fatal Error: Maximum execution time of 5 seconds exceeded.
How do I solve this?
In my php.ini there have max_execution_time =30.

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry.

**Comment by FarukOne** [comment]
Okay, I thought you have faced the same problem, so you can help me out with this problem. By the way, Thank You for your response. Have a good day.
