### ISSUE TITLE
Try / finally results in incomplete code coverage

### ISSUE THREAD

**Issue by MadEgg** [sebastianbergmann/php-code-coverage#509]
When a function wraps its contents in a try/finally block to execute some cleanup code on return should an exception be thrown, the function is not set as fully covered.

Example:

**src/Foo.php**
```
<?php
class Foo {
    public function test() {
        try
        {
            return "foo";
        }
        finally
        {}
    }
}
```

**tests/FooTest.php**
```
<?php
use PHPUnit\Framework\TestCase;

class FooTest extends TestCase {
    public function testFoo() {
        $f = new Foo;
        $this->assertEquals("foo", $f->test());
    }
}
```

**phpunit.xml**
```
<?xml version="1.0" encoding="UTF-8"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/6.0/phpunit.xsd"
         bootstrap="src/Foo.php"
         verbose="true">
    <testsuite>
        <directory suffix="Test.php">tests</directory>
    </testsuite>

    <filter>
        <whitelist processUncoveredFilesFromWhitelist="true">
            <directory suffix=".php">src</directory>
        </whitelist>
    </filter>
</phpunit>
```

Expected result: function 'test' is fully covered, as there is no execution path that is untested.
Actual result: the closing bracket of the function is marked as untested.

You can solve this by storing the response in a variable inside the try/finally and returning that variable afterwards, so it seems the lack of a return statement after the try/finally is causing the issue.

**Comment by sebastianbergmann** [comment]
@derickr Could this be an Xdebug issue?

**Comment by derickr** [comment]
Could be, but should be fixed in 2.4.1: https://bugs.xdebug.org/bug_view_page.php?bug_id=00001241

**Comment by sebastianbergmann** [comment]
@MadEgg Which of versions of PHP, PHPUnit, and Xdebug are you experiencing this issue with?

**Comment by MadEgg** [comment]
XDebug newer than 2.4.0 (Ubuntu 16.04 default) indeed seems to fix it.

I tried it on Ubuntu 16.04 with PHP 7.0 and XDebug 2.4.0 and PHP 7.1 / XDebug 2.4.0. This was both using PHPUnit 6.0.7.

I upgraded XDebug to 2.5.0 from a PPA and that solves the problem.
