### ISSUE TITLE
InstanceOf in elseif clause not marked as executed

### ISSUE THREAD

**Issue by MadEgg** [sebastianbergmann/php-code-coverage#510]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 5.0.2
| PHP version               | 7.1.2
| Driver                    | Xdebug
| Xdebug version (if used)  | 2.5.0
| Installation Method       | PHPUnit PHAR
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 6.0.8

**``src/Foo.php``**
```php
<?php
class Foo
{
    public function __construct($arg)
    {
        if (is_string($arg))
            return;
        elseif ($arg instanceof DateTime)
            return;
    }
}
```

**``tests/FooTest.php``**
```php
<?php
use PHPUnit\Framework\TestCase;

class FooTest extends TestCase
{
    public function testFoo()
    {
        $f = new Foo(new DateTime);
        $this->assertInstanceOf(Foo::class, $f);

        $f = new Foo("");
        $this->assertInstanceOf(Foo::class, $f);

        $f = new Foo(0);
        $this->assertInstanceOf(Foo::class, $f);
    }
}
```

**``phpunit.xml``**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/6.0/phpunit.xsd"
         bootstrap="src/Foo.php"
         verbose="true">
    <testsuite>
        <directory suffix="Test.php">tests</directory>
    </testsuite>

    <filter>
        <whitelist processUncoveredFilesFromWhitelist="true">
            <directory suffix=".php">src</directory>
        </whitelist>
    </filter>
</phpunit>
```

**Expected results:** 100% code coverage
**Actual results:** Line 8 (the one with instanceof) is not marked as executed, even though it clearly must be as line 9 is marked as executed.

![spectacle lh7516](https://cloud.githubusercontent.com/assets/1172291/23592981/072d280a-0209-11e7-944e-14d11f2a1a2d.png)

**Comment by sebastianbergmann** [comment]
Looks like an Xdebug issue to me. Can you please test with Xdebug 2.5.1?

**Comment by MadEgg** [comment]
This issue indeed does not occur with Xdebug 2.5.1.
