### ISSUE TITLE
File / Class exceptionally removed / not showing up in coverage report

### ISSUE THREAD

**Issue by jankal** [sebastianbergmann/php-code-coverage#511]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 5.0.3
| PHP version               | 7.0.6
| Driver                    | Xdebug
| Xdebug version (if used)  | 2.5.1
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 6.0.8

I recently started jankal/checked-instance where I'm now using PHPUnit for Unit Tests and Coverage.

With the first tests and features I archieved 100 % coverage on both source files (`Factory.php, Instance.php`).

After jankal/checked-instance@c02a9a7ed125c84f16a7ff0914de62998a0243fd the coverage for `Factory.php` was not displayed in my IDE anymore and the clover report contained `<metrics ... classes="0"...>` for the file.

Why is PHPUnit not generating a coverage report for `Factory.php` anymore?

It still worked fine with jankal/checked-instance@0175b71

Coverage on coveralls: [![Coverage Status](https://coveralls.io/repos/github/jankal/checked-instance/badge.svg?branch=master)](https://coveralls.io/github/jankal/checked-instance?branch=master)
Build on TravisCI: [![Build Status](https://travis-ci.org/jankal/checked-instance.svg?branch=master)](https://travis-ci.org/jankal/checked-instance)

Previous issue: sebastianbergmann/phpunit#2564

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by jankal** [comment]
@sebastianbergmann I don't yet know what exact part of the commit caused this Issue.

**Comment by sebastianbergmann** [comment]
No feedback, closing.
