### ISSUE TITLE
Unable to update phpunit/php-code-coverage (4.0.5 => 4.0.7)

### ISSUE THREAD

**Issue by podlom** [sebastianbergmann/php-code-coverage#512]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 4.0.5
| PHP version               | 7.0.8
| Installation Method       | Composer

Composer update failed with error:
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 12 updates, 0 removals
  - Updating phpunit/php-code-coverage (4.0.5 => 4.0.7): Loading from cache

  [ErrorException]
  ZipArchive::extractTo(C:\OpenServer\domains\domain.local\yii-advanced-app-2.0.11\advanced/vendor/composer/c87a6bc4/sebastianbergmann-php-code-coverage-09e2277\tests\_files\Report\HTML\CoverageForClassWithA
  nonymousFunction/source_with_class_and_anonymous_function.php.html): failed to open stream: Invalid argument

update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--
optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...

**Comment by sebastianbergmann** [comment]
Looks like a Windows issue related to too-long paths. Other users solved similar issues by following the advice in https://mspoweruser.com/ntfs-260-character-windows-10/.

**Comment by podlom** [comment]
Thanks a lot, @sebastianbergmann 
I have checked composer updated on shorter directory path. It works fine.
