### ISSUE TITLE
It would be great if the Xdebug version was also rendered in the footer

### ISSUE THREAD

**Issue by derickr** [sebastianbergmann/php-code-coverage#520]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 2.0.11
| PHP version               | 7.1.4-dev
| Driver                    | Xdebug
| Xdebug version (if used)  | 2.6.0-dev
| Installation Method       | PHPUnit PHAR
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 4.3.4

Currently, the footer is:

 Generated by PHP_CodeCoverage 2.0.11 using PHP 7.1.4-dev and PHPUnit 4.3.4 at Thu Apr 13 17:49:36 UTC 2017. 

Can you add the Xdebug version too please?

**Comment by sebastianbergmann** [comment]
Will do.

**Comment by sebastianbergmann** [comment]
Apparently I already did that a while ago:
![screenshot from 2017-04-14 07-11-25](https://cloud.githubusercontent.com/assets/25218/25033845/b9e2954c-20e1-11e7-96d9-54dedc4e3835.png)
