### ISSUE TITLE
False negative on code coverage 

### ISSUE THREAD

**Issue by sebastianfeldmann** [sebastianbergmann/php-code-coverage#521]
| Q | A
| --------------------------| ---------------
| php-code-coverage version | 5.2.1
| PHP version | 7.1.2
| Driver | Xdebug
| Xdebug version (if used) | 2.5.0
| Installation Method | PHPUnit PHAR
| Usage Method | PHPUnit
| PHPUnit version (if used) | 6.1.1

If you create a map with local constant values and external constant values the lines defining the map are marked as not covered.
The external class is **not** in the whitelisted path for code coverage (vendor directory).

The map has to have more than 1 element.

```php
namespace MyName;

class Dummy
{
    const foo = 'foo';
    const bar = 'bar';
    const baz = 'baz';

    private $fooBarBazMap;

    public function __construct()
    {
        $this->fooBarBazMap = [
            self::foo => \SomeVendorClass::FOO,
            self::bar => \SomeVendorClass::BAR, // not covered
            self::baz => \SomeVendorClass::BAZ // not covered
        ];
    }
}
```

If you are using strings instead of local constants it works

```php
$this->fooBarBazMap = [
    'foo' => \SomeVendorClass::FOO,
    'bar' => \SomeVendorClass::BAR, // covered
    'baz' => \SomeVendorClass::BAZ // covered
];
```

If you are using strings or local constants instead of external constants it works as well

```php
$this->fooBarBazMap = [
    self::foo => 'FOO',
    self::bar => self::bar, // covered
    self::baz => 'BAZ' // covered
];
```

**Comment by GrahamCampbell** [comment]
Does this happen with the newest php and xdebug? 7.1.4, 2.5.2.

**Comment by sebastianfeldmann** [comment]
No indeed it does not.

| Q | A
| --------------------------| ---------------
| php-code-coverage version | 5.2.1
| PHP version | **7.1.4**
| Driver | Xdebug
| Xdebug version (if used) | **2.5.3**
| Installation Method | PHPUnit PHAR
| Usage Method | PHPUnit
| PHPUnit version (if used) | 6.1.1

works just fine

Thanks, and sorry for bothering you.

**Comment by mundschenk-at** [comment]
I see this still happening with PHP 7.1.11 and Xdebug 2.5.5 (php-code-coverage 5.2.3, PHPUnit 6.4.4)
