### ISSUE TITLE
codeCoverageIgnore for specific test suite only

### ISSUE THREAD

**Issue by anuragrana** [sebastianbergmann/php-code-coverage#525]
I have defined two test-suites in `phpunit.xml` file, one for Unit Tests and other for Functional Test. For some functions which can't be unit tested, I am using `@codeCoverageIgnore` in my source code. But I do not want this code to be ignored when running Functional Tests.

Is it possible to add test-suite name to `codeCoverageIgnore` so that my code is ignored for unit tests and not for functional tests.

As confirmed by Sebastian, This is not possible. Hence opening a ticket.

http://stackoverflow.com/questions/43886660/how-to-codecoverageignore-for-specific-test-suite-only-in-phpunit/43886717#43886717

**Comment by sebastianbergmann** [comment]
I do not think that this would be useful.
