### ISSUE TITLE
Code Coverage visualisation issue with group use statements

### ISSUE THREAD

**Issue by derickr** [sebastianbergmann/php-code-coverage#530]
Related: https://bugs.xdebug.org/view.php?id=1440 — has reproducible case too.

![screenshot-code-coverage](https://cloud.githubusercontent.com/assets/208074/26499291/06ff3a4e-4200-11e7-9f5e-ea94a05f6703.png)

**Comment by sebastianbergmann** [comment]
I cannot reproduce this:
```
```
```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/6.1/phpunit.xsd"
         bootstrap="src/Foo.php"
         forceCoversAnnotation="true"
         beStrictAboutCoversAnnotation="true"
         beStrictAboutOutputDuringTests="true"
         beStrictAboutTodoAnnotatedTests="true"
         verbose="true">
    <testsuite>
        <directory suffix="Test.php">tests</directory>
    </testsuite>

    <filter>
        <whitelist processUncoveredFilesFromWhitelist="true">
            <directory suffix=".php">src</directory>
        </whitelist>
    </filter>
</phpunit>
```
```php
<?php
use vendor\project\ {
   ClassA, ClassB, ClassC as C
};

class Foo
{
    public function bar()
    {
        return true;
    }
}
```
```php
<?php
/**
 * @covers Foo
 */
class FooTest extends PHPUnit\Framework\TestCase
{
    public function testOne()
    {
        $foo = new Foo;

        $this->assertTrue($foo->bar());
    }
}
```
![screenshot from 2017-05-26 11-16-10](https://cloud.githubusercontent.com/assets/25218/26500713/fab52032-4204-11e7-8a4f-0f12b7512587.png)

**Comment by sebastianbergmann** [comment]
@freyr Can you please provide feedback on whether @derickr and I understood your problem correctly? Thanks!

**Comment by derickr** [comment]
I can reproduce it with:

```
git clone https://github.com/freyr/photo-gallery
cd photo-gallery
composer install
php -dxdebug.coverage_enable=1 vendor/phpunit/phpunit/phpunit --coverage-html=/tmp/1440 --testsuite unit
firefox file:///tmp/1440/Model/Gallery/PhotoRepository.php.html
```

Generated by php-code-coverage 5.2.1 using PHP 7.1.6-dev with Xdebug 2.5.5-dev and PHPUnit 6.1.3 at Sun May 28 15:21:48 UTC 2017

```
PHP 7.1.6-dev (cli) (built: May 23 2017 13:36:45) ( NTS DEBUG )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.5.5-dev, Copyright (c) 2002-2017, by Derick Rethans
```

**Comment by sebastianbergmann** [comment]
In the `phpunit.xml` configuration file `processUncoveredFilesFromWhitelist="false`" is set. The generated code coverage report is correct for this setting. Set `processUncoveredFilesFromWhitelist="false`" and you will get the expected result.

**Comment by sebastianbergmann** [comment]
It may be possible to filter the lines in question also when `processUncoveredFilesFromWhitelist="false"` is set.

**Comment by freyr** [comment]
@sebastianbergmann - Problem occurs only for group use in interfaces  - as @derickr shows - using grouping statements in file that contain only interface will end up marking that file as part of a coverage statistics. Since you cannot test or cover use statement - those lines in interface are shown as not covered and the summary for the folder is also going down...

**Comment by sebastianbergmann** [comment]
As far as I can see, this has nothing to do with interfaces but rather with uncovered whitelisted files.

**Comment by sebastianbergmann** [comment]
I agree that the current behavior is {confusing|inconsistent|inconvenient} but -- considering the fact using `processUncoveredFilesFromWhitelist="true"` should be used -- I am not inclined to spend time on fixing this myself. I would, of course, consider a pull request, though.
