### ISSUE TITLE
CoveredCodeNotExecutedException thrown too eagerly

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/php-code-coverage#533]
When `setCheckForUnexecutedCoveredCode(true)` is used then an `CoveredCodeNotExecutedException` will be raised when `@covers class` or `@covers class::method` (or `@uses class` or `@uses class::method`) is used. It should only be raised for `@covers class::method` (or `@uses class::method`).

**Comment by RobQuistNL** [comment]
ITT: Sebastian battling AI

**Comment by sebastianbergmann** [comment]
The functionality in question has been removed as part of 92cb0536ccf85e90479b066c6a9ead8bbb2d5fb9.
