### ISSUE TITLE
Code coverage skips parameters

### ISSUE THREAD

**Issue by nyamsprod** [sebastianbergmann/php-code-coverage#535]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 5.2.1
| PHP version               | PHP 7.0.18-0ubuntu0.16.04.1 (cli) ( NTS )
| Driver                    | Xdebug / PHPDBG (both)
| Xdebug version (if used)  | 2.4.0 (default install Ubuntu)
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 6.2.1
[bug-codecoverage.tar.gz](https://github.com/sebastianbergmann/php-code-coverage/files/1056079/bug-codecoverage.tar.gz)

Depending on how the StreamIterator::fputcsv1 or StreamIterator::fputcsv0 is called, code coverage is different and some parameters are shown has not having been covered while phpunit says 100% code coverage.

The testsuite is attached with a simple class and its associated test.

This is an extract from https://travis-ci.org/thephpleague/csv/jobs/240014939 where it happens in PHP7.1 with a more recent version of Xdebug 2.5.3.

Of note if I put all the parameters on the same line code coverage says everything is fine.

**Comment by sebastianbergmann** [comment]
@derickr ping

**Comment by derickr** [comment]
Likely fixed through https://bugs.xdebug.org/view.php?id=1444 (and https://github.com/sebastianbergmann/php-code-coverage/issues/527)

**Comment by sebastianbergmann** [comment]
@derickr ETA for Xdebug 2.5.5?

**Comment by derickr** [comment]
Not sure yet... There are only very few fixes: https://bugs.xdebug.org/changelog_page.php?version_id=48

**Comment by sebastianbergmann** [comment]
Release early, release often :)

**Comment by derickr** [comment]
Elections...
