### ISSUE TITLE
[Bug] Unexecutable lines are counted for uncovered files

### ISSUE THREAD

**Issue by leberknecht** [sebastianbergmann/php-code-coverage#537]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | dev-master
| PHP version               | 7.0.20
| Driver                    | Xdebug 
| Xdebug version (if used)  | v2.5.4
| Installation Method       | Composer
| Usage Method              | code-coverage

In `CodeCoverage::.addUncoveredFilesFromWhitelist` we iterate over the list of uncovered files and then do
```php
$lines = count(file($uncoveredFile));

for ($i = 1; $i <= $lines; $i++) {
    $data[$uncoveredFile][$i] = Driver::LINE_NOT_EXECUTED;
}
```
resulting in counting _all_ lines as uncovered, including lines that are not executable.
This results in 
a) wrong metrics, as more lines are counted as uncovered than can be covered
b) when we merge two reports, where first report has no coverage at all for a class, but the second has 100%, the merged result will show < 100% coverage, which is wrong.

**Comment by sebastianbergmann** [comment]
This is not a bug. Simply set `processUncoveredFilesFromWhitelist="true"` on the `whitelist` element in your `phpunit.xml`.

**Comment by leberknecht** [comment]
Indeed! That did the trick, thanks a lot!
