### ISSUE TITLE
Content Security Issues

### ISSUE THREAD

**Issue by PatrickRose** [sebastianbergmann/php-code-coverage#538]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 4.0.8
| PHP version               | 5.6.30
| Driver                    | Xdebug
| Xdebug version (if used)  | 2.2.5
| Installation Method       | Composer
| Usage Method              | PHPUnit (via jenkins)
| PHPUnit version (if used) | 5.7.19

Jenkins [applies a content security policy when it serves raw HTML files](https://wiki.jenkins-ci.org/display/JENKINS/Configuring+Content+Security+Policy) - we create a clover HTML file as part of our build and dump the files which are then deployed to the build but when we view the report Firefox and Chrome don't allow the inline styles to work meaning we don't get a particularly helpful dashboard.

[It's a known limitation of Bootstrap's progress bar](http://getbootstrap.com/components/#progress), with the alternatives to do it via JS or use custom classes. I can send the boring PR to add the custom classes and update the template if you think that's the right thing to do?

**Comment by sebastianbergmann** [comment]
A pull request would be appreciated.

**Comment by PatrickRose** [comment]
Is 4.* still supported, and should I PR against there or against master?

**Comment by sebastianbergmann** [comment]
4.* is used by PHPUnit 5.7 and thus still supported.

**Comment by sebastianbergmann** [comment]
Won't fix.

**Comment by sebastianbergmann** [comment]
I think the right solution is to configure Jenkins to not apply its rather strict CSP to the code coverage report.
