### ISSUE TITLE
Missing attribute `type` in the css <link> tags

### ISSUE THREAD

**Issue by ValentinMATHIEU** [sebastianbergmann/php-code-coverage#540]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 4.0.4
| PHP version               | 7.0 / 7.1
| Driver                    | Xdebug
| Xdebug version (if used)  | 2.5.5
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | x.y.z

When i generate the HTML code coverage report, the css tags have missing attribute `type`.

```html
<link href="css/bootstrap.min.css" rel="stylesheet">
<link href="css/style.css" rel="stylesheet">
```
This may cause display issue: no CSS, and some error messages about wrong mime types.
In my case Google Chrome cry about mime types and doesn't run CSS.

After adding `type="text/css"` no more errors. ref: [w3schools](https://www.w3schools.com/tags/tag_link.asp)

```html
<link href="css/bootstrap.min.css" rel="stylesheet" type="text/css">
<link href="css/style.css" rel="stylesheet" type="text/css">
```

**Comment by ValentinMATHIEU** [comment]
I have a local branch named issue-540, ready to fix.

**Comment by garrettw** [comment]
I recommend closing this issue and opening a PR with your fix.
