### ISSUE TITLE
Only the last anonymous function is reported

### ISSUE THREAD

**Issue by CJDennis** [sebastianbergmann/php-code-coverage#543]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | x.y.z
| PHP version               | 5.4.45
| Driver                    | Xdebug
| Xdebug version (if used)  | 2.2.5
| Installation Method       | PHAR
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 4.8.27

It appears that anonymous functions are all recorded using the same key, so each one overwrites the previous one leaving only the last one in the results.

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by sebastianbergmann** [comment]
I was able to reproduce this:

![screenshot from 2017-07-25 07-16-35](https://user-images.githubusercontent.com/25218/28556877-6a03a1b0-7109-11e7-9c51-ccd9b5c672dd.png)

**Comment by sebastianbergmann** [comment]
Please note that this will not be fixed for PHPUnit 4.8 as that version has reached its end-of-life.

**Comment by sebastianbergmann** [comment]
Moved to https://github.com/sebastianbergmann/php-token-stream/issues/66
