### ISSUE TITLE
If @covers is defined, some lines are not covered if throw an exception 

### ISSUE THREAD

**Issue by FedericoBiccheddu** [sebastianbergmann/php-code-coverage#544]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 5.2.1
| PHP version               | 7.1.1
| Driver                    | Xdebug
| Xdebug version (if used)  | 2.5.5
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 6.23

Having logic isolate in private methods that are not tested directly, if test passed, the exception thrown is not covered anymore. 

Eg:
```php
<?php

# ValueObject.php

class ValueObject
{
    /**
     * @var string
     */
    private $value;

    public function __construct(string $value)
    {
        $this->setValue($value);
    }

    /**
     * @param string $value
     *
     * @throws \DomainException
     */
    public function changeValue(string $value)
    {
        $this->setValue($value);
    }
    /**
     * @param string $value
     *
     * @throws \DomainException
     */
    private function setValue(string $value): void
    {
        $this->assertLength($value);

        $this->value = $value;
    }

    /**
     * @param $value
     *
     * @throws \DomainException
     */
    private function assertLength($value): void
    {
        if (strlen($value) >= 10) {
            throw new \DomainException('Value must be max 10 characters long.');
        }
    }
}
```

```php
<?php

use PHPUnit\Framework\TestCase;

/**
 * @coversDefaultClass \ValueObject
 */
class ValueObjectTest extends TestCase
{
    public function test()
    {
        $this->expectException(\DomainException::class);

        $valueObject = new ValueObject('foo');

        $valueObject->changeValue(str_repeat('a', 11));
    }

    public function testMultipleException()
    {
        $this->expectException(\DomainException::class);

        $valueObject = new ValueObject('foo');

        $valueObject->changeValue('.foo');
    }
}
```

This is the coverage result with `@covers \ValueObject::changeValue()`:
<img width="1154" alt="screen shot 2017-07-31 at 12 06 13" src="https://user-images.githubusercontent.com/433819/28773279-24e98646-75e9-11e7-920b-6e33c98a45eb.png">

This is the coverage result without `@covers \ValueObject::changeValue()`:
<img width="1147" alt="screen shot 2017-07-31 at 12 10 26" src="https://user-images.githubusercontent.com/433819/28773306-48d16a92-75e9-11e7-81fe-de10a9055ac1.png">

If multiple private methods throw an exception, like in the next code example, the result change and even if the test is passed, only the last exception is covered:
```php
<?php

# ValueObject.php

class ValueObject
{
    /**
     * @var string
     */
    private $value;

    public function __construct(string $value)
    {
        $this->setValue($value);
    }

    /**
     * @param string $value
     *
     * @throws \DomainException
     */
    public function changeValue(string $value)
    {
        $this->setValue($value);
    }
    /**
     * @param string $value
     *
     * @throws \DomainException
     */
    private function setValue(string $value): void
    {
        $this->assertLength($value);
        $this->assertDoesNotStartWithDot($value);

        $this->value = $value;
    }

    /**
     * @param $value
     *
     * @throws \DomainException
     */
    private function assertDoesNotStartWithDot($value): void
    {
        if ($value{0} !== '.') {
            throw new \DomainException('Value can not starts with a dot.');
        }
    }

    /**
     * @param $value
     *
     * @throws \DomainException
     */
    private function assertLength($value): void
    {
        if (strlen($value) >= 10) {
            throw new \DomainException('Value must be max 10 characters long.');
        }
    }
}
```

And this is the result without the `@covers \ValueObject::changeValue()`:
<img width="1152" alt="screen shot 2017-07-31 at 12 13 26" src="https://user-images.githubusercontent.com/433819/28773497-129edf8a-75ea-11e7-927f-49bb4425ac02.png">

And this is the result with the `@covers \ValueObject::changeValue()`:
<img width="1148" alt="screen shot 2017-07-31 at 12 20 53" src="https://user-images.githubusercontent.com/433819/28773654-be41e4f4-75ea-11e7-924f-58911afe4b59.png">

And this is the output from CLI:
```
$ vendor/bin/phpunit

PHPUnit 6.2.3 by Sebastian Bergmann and contributors.


Time: 670 ms, Memory: 6.00MB

OK (2 tests, 2 assertions)

Generating code coverage report in Clover XML format ... done

Generating code coverage report in HTML format ... done

Process finished with exit code 0
```

**Comment by sebastianbergmann** [comment]
There can be many reasons why a specific line is not covered. Each of them is likely a different issue. In order to be able to reproduce *anything* and not get bogged down with details, you need to provide the following **in ONE new issue per case**.

That means:

- The exact versions of (this is what the template requires too, but more):
  - PHP
  - PHP Code Coverage
  - Xdebug
  - PHPUnit
- ```php -v``` output
- Either a ```.tar.gz``` archive or a GitHub repository with a reproduce case. With **one** file that shows the problem and **one** test case file (with the exception that sometimes, you might need **two** source files to show a problem.

This information should be filed as **one specific case per issue**.

**Comment by sebastianbergmann** [comment]
No feedback, closing.
