### ISSUE TITLE
phpunit/php-token-stream require php ^7.0

### ISSUE THREAD

**Issue by jaredchu** [sebastianbergmann/php-code-coverage#545]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 5.2.2
| PHP version               | 5.6.x
| Driver                    | Xdebug / PHPDBG
| Xdebug version (if used)  | not specific
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 5.6.x

Travis CI build fail on PHP 5.6

```
composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Installation request for phpunit/php-token-stream 2.0.0 -> satisfiable by phpunit/php-token-stream[2.0.0].
    - phpunit/php-token-stream 2.0.0 requires php ^7.0 -> your PHP version (5.6.24) does not satisfy that requirement.
  Problem 2
    - phpunit/php-token-stream 2.0.0 requires php ^7.0 -> your PHP version (5.6.24) does not satisfy that requirement.
    - phpunit/php-code-coverage 4.0.8 requires phpunit/php-token-stream ^1.4.2 || ^2.0 -> satisfiable by phpunit/php-token-stream[2.0.0].
    - Installation request for phpunit/php-code-coverage 4.0.8 -> satisfiable by phpunit/php-code-coverage[4.0.8].
```

**Comment by sebastianbergmann** [comment]
php-code-coverage 5.2.2 requires PHP 7 itself.

**Comment by Mehmood-khan** [comment]
I'm having the same problem of php version, that when I run composer install it gives me something like this :
 phpunit/php-token-stream 3.0.1 requires php ^7.1 -> your PHP version (7.0.9)                                                     does not satisfy that requirement.

How do I update my php version to ^7.1 ? 
please help

**Comment by jaredchu** [comment]
@Mehmood-khan use a lower version of php-code-coverage. It's working for PHP 5.5, 5.6, 7.0 and 7.1 if I use this configuration:

```
"require-dev": {
        "phpunit/phpunit": "^4.0 || ^5.0"
}
```

**Comment by Mehmood-khan** [comment]
where should I add the line of code you've mentioned ? @jaredchu

**Comment by jaredchu** [comment]
In `composer.json`. You're using `php-code-coverage` for `PHP Unit Testing`, right?
If not please explain your issue on a StackOverflow question.

**Comment by Mehmood-khan** [comment]
No, I've just moved my laravel application from my one computer to another, I get into the folder where I pasted it, but when I try to do like `php artisan serve` it says this:



phpunit/php-token-stream 3.0.1 requires php ^7.1 -> your PHP version (7.0.9) does not satisfy that requirement.
I know that _php version_ of mine at the new computer is 7.0.9, and it needs ^7.1, so how to solve this problem ?

**Comment by jaredchu** [comment]
@Mehmood-khan You need to upgrade your PHP version to 7.1. It depends on your environment and it's not in the scope of this project. Thanks!
