### ISSUE TITLE
Notice in CLI mode: Undefined index: REQUEST_TIME

### ISSUE THREAD

**Issue by garrettw** [sebastianbergmann/php-code-coverage#546]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 4.0.8
| PHP version               | 5.6.5
| Driver                    | Xdebug
| Xdebug version (if used)  | 2.2.7
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 5.7.21

As can be seen in [this Travis output](https://travis-ci.org/gjerokrsteski/pimf-framework/jobs/263155019), running `vendor/bin/phpunit --coverage-clover=coverage.clover` causes 2 notices related to the array index `'REQUEST_TIME'` not being found in `$_SERVER`.
See src/Report/Clover.php on lines [34](https://github.com/sebastianbergmann/php-code-coverage/blob/master/src/Report/Clover.php#L34) and [38](https://github.com/sebastianbergmann/php-code-coverage/blob/master/src/Report/Clover.php#L38).

**Comment by sebastianbergmann** [comment]
Looks like your code unsets `$_SERVER['REQUEST_TIME']`.

**Comment by garrettw** [comment]
Where are you seeing that? I just searched the codebase (and the tests dir) for `REQUEST_TIME` (case insensitive) and found 0 matches.

**Comment by sebastianbergmann** [comment]
I am not seeing this anywhere (because I did not look). But `$_SERVER['REQUEST_TIME']` is available by default. If it is not then because somewhere in the code an `unset()` happens.

**Comment by garrettw** [comment]
Wow, I had no idea, as I am not the main developer of this library. I have found the offending test. Sorry to bother you.
