### ISSUE TITLE
Method is incorrectly marked as anonymous function

### ISSUE THREAD

**Issue by jtreurniet** [sebastianbergmann/php-code-coverage#547]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 5.2.2
| PHP version               | 7.1.7
| Driver                    | Xdebug
| Xdebug version (if used)  | 2.5.5
| Installation Method       | PHPUnit PHAR
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 6.3.0

I have a class which defines a method called `empty`. The code coverage report reports this as an anonymous function, rather than the actual method.

![bug-1](https://user-images.githubusercontent.com/30029909/29491784-5973428a-8534-11e7-8f28-b3996a0d851d.png)
![bug-2](https://user-images.githubusercontent.com/30029909/29491785-597444c8-8534-11e7-989c-bd982e5fe548.png)

Renaming the method makes it show up in the coverage report as expected. Changing or removing the return-type hint does not appear to make a difference.

**Comment by sebastianbergmann** [comment]
Reproduced with the minimal, self-contained example shown below.

![screenshot from 2017-08-20 07-19-22](https://user-images.githubusercontent.com/25218/29492312-12122b60-8578-11e7-9efd-0e52a3e6aea2.png)

**Comment by sebastianbergmann** [comment]
Moved to https://github.com/sebastianbergmann/php-token-stream/issues/68.
