### ISSUE TITLE
phpdbg throws "out of memory" even when memory_limit is -1

### ISSUE THREAD

**Issue by vivekagarwal1984** [sebastianbergmann/php-code-coverage#550]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | PHPDBG 7.0.22-0ubuntu0.17.04.1
| PHP version               | x.y.z
| Driver                    |  PHPDBG
| Xdebug version (if used)  | x.y.z
| Installation Method       | Composer / PHPUnit PHAR
| Usage Method              | PHPUnit / other
| PHPUnit version (if used) | PHPUnit 6.3.0

I have 2000 unit test cases which I am trying to run using phpdbg.
My machine has 32 GB ram and I have specified memory_limit as -1.
Even when i try to pass the memory limit from the comman line, it always exists after consuming 5GB

Command: phpdbg -qrr -d memory_limit=-1 ./vendor/phpunit/phpunit/phpunit --debug --verbose
mmap() failed: [12] Cannot allocate memory

Output: [PHP Fatal error:  Out of memory (allocated 5771886592) (tried to allocate 65536 bytes) in

I have limited knowledge of php and hence finding it difficult to debug

**Comment by sebastianbergmann** [comment]
I am sorry but this is not an issue with this component and there is nothing I can help with.
