### ISSUE TITLE
Incorrect code coverage with switch(true) - line is not covered

### ISSUE THREAD

**Issue by borNfreee** [sebastianbergmann/php-code-coverage#552]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 5.1.0
| PHP version               | 7.1.0
| Driver                    | Xdebug
| Xdebug version (if used)  | 2.5.1
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 6.1.0

The line of code with `switch(true)` is not covered in Code Coverage Data. When it has any other condition, like `switch($someVar)` - it works as expected

I'm not sure this is an issue with code coverage or xDebug, but I don't have enough knowledge to check it.

![coverage](https://user-images.githubusercontent.com/3725595/30136749-ba032446-9360-11e7-826a-bc44d1a19d36.png)

**Comment by morozov** [comment]
I have a similar issue in a slightly different setup:

| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 5.2.2
| PHP version               | 7.1.9
| Driver                    | Xdebug
| Xdebug version (if used)  | 2.5.5
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 6.2.4

The line containing assignment of a boolean value to the array element is reported as not covered, however the rest of the assignments in the same array are reported as covered. The file coverage is reported correctly as 100% which probably means that this line is considered non-executable.

![552](https://user-images.githubusercontent.com/59683/30840962-f8a50656-a22e-11e7-962f-24e7afd078a1.png)

**Comment by morozov** [comment]
It looks like an Xdebug issue ([#1479](https://bugs.xdebug.org/view.php?id=1479)).
