### ISSUE TITLE
phpunit code coverage issue

### ISSUE THREAD

**Issue by archana27m** [sebastianbergmann/php-code-coverage#555]
PHPUnit version     | 6.3.0
PHP version         | 7.0.15
XDebug | 2.5.4
Installation Method | Composer 

Composer.json
```
"require-dev": {
         "phpunit/phpunit": "6.3.0"
    }
```

I have my php class files inside lib folder and unit test cases inside tests folder.
Using phpunit.xml as follows: 
```
<?xml version="1.0" encoding="UTF-8"?>
<phpunit>
  <testsuites>
    <testsuite name="ProjectName">
      <directory suffix="Test.php">tests</directory>
    </testsuite>
  </testsuites>
<filter>
    <whitelist addUncoveredFilesFromWhitelist="true">
      <directory suffix=".php">./lib</directory>
    </whitelist>
  </filter>
</phpunit>
```

The coverage html files getting generated but showing code coverage as 0% for all files.
Please help me on this.

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by archana27m** [comment]
<?php
include_once dirname(__DIR__)."/vendor/autoload.php";

use PHPUnit\Framework\TestCase;

class dummyTest extends TestCase
{

	public function testDummyData()
	{
		$this->assertEquals("hello","hello");
	}
	
}

However I am simply running some test cases similarly, there is no error at all, I get all tests cases executed fine with using .\vendor\bin\phpunit tests\dummyTest or directly .\vendor\bin\phpunit tests 

It does not show coverage at all, code coverage is 0%.  

Just wanted to ask do I need to install php-code-coverage via composer as well or using phpunit : 6.3.0 is enough?

**Comment by kubawerlos** [comment]
> Just wanted to ask do I need to install php-code-coverage via composer as well or using phpunit : 6.3.0 is enough?

Definitely it's enough, can you past your tests output too?

**Comment by archana27m** [comment]
yes I am able to get all results fine as 
```
Time: 3.88 seconds, Memory: 8.00MB

OK (6 tests, 11 assertions)
```

**Comment by VincentChataignier** [comment]
Do you use option `--coverage-[type of coverage]` with your command ?

**Comment by archana27m** [comment]
```
.\vendor\bin\phpunit --coverage-text=testcoverage.txt tests 
or 
.\vendor\bin\phpunit --coverage-html tests
```

**Comment by VincentChataignier** [comment]
Can you try with this phpunit.xml please?
```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit>
  <testsuites>
    <testsuite name="ProjectName">
      <directory suffix="Test.php">tests</directory>
    </testsuite>
  </testsuites>
<filter>
    <whitelist>
      <directory suffix=".php">./lib</directory>
    </whitelist>
  </filter>
</phpunit>
```

**Comment by archana27m** [comment]
No..  still coverage is 0% using --coverage-html

**Comment by archana27m** [comment]
Can some one help me with versions I have specified for PHPUnit, Xdebug and PHP? are these fine?

**Comment by kubawerlos** [comment]
Looks fine, I'd suspect something like `forceCoversAnnotation`.

**Comment by archana27m** [comment]
I have not defined @covers annotation anywhere in the code, ideally it should cover all the source code. 
I also tried updating xdebug version to 2.5.5 but no luck.

**Comment by sebastianbergmann** [comment]
https://github.com/sebastianbergmann/php-code-coverage/issues/555#issuecomment-343227047 is not a complete, minimal, self-contained, reproducing test case.

**Comment by sebastianbergmann** [comment]
No feedback, closing.
