### ISSUE TITLE
Allow injection of Builder

### ISSUE THREAD

**Issue by exussum12** [sebastianbergmann/php-code-coverage#565]
https://github.com/sebastianbergmann/php-code-coverage/blob/master/src/CodeCoverage.php#L169

On the link above, the builder class is hard coded, If possible I would need to inject this in, Just wondering what you think the best method would be

- Change the visibility to protected and extend the class (small amount of code change)
- Allow a string name class to be put into the constructor for new classes
- A setBuilder method to inject into (probably a bad idea due to the amount its set / cleared)
- Something else I have missed

Thank you

**Comment by sebastianbergmann** [comment]
I do not think that this makes sense.

**Comment by exussum12** [comment]
How can you over ride the behaviour otherwise ?
