### ISSUE TITLE
HHVM incompatibility with php-code-coverage

### ISSUE THREAD

**Issue by neilmatillano** [sebastianbergmann/php-code-coverage#570]
|  No code coverage driver is available error message                    | A
| --------------------------| ---------------
| php-code-coverage version | 5.3.0
| PHP version               | 7.1.11
| Driver                    | Xdebug / PHPDBG ( I cannot confirm but I believe it's xdebug
| Xdebug version (if used)  | Cannot find
| Installation Method       | Composer 
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 6.4.3

I am trying to run a code coverage on my project and I get an error
No code coverage driver available

Also get exception 
SebastianBergmann\CodeCoverage\RuntimeException: No code coverage driver available
When being called in $coverage = new CodeCoverage;

I already added xdebug parameters on php.ini 
zend_extension= "/usr/lib/php/extensions/no-debug-non-zts-20160303/xdebug.so"
[XDebug]
xdebug.remote_enable = 1
xdebug.remote_autostart = 1

also I got this info from php -v
PHP 7.1.11 (cli) (built: Oct 27 2017 11:00:03) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans

But when i do a composer show , i don't see xdebug listed

**Comment by sebastianbergmann** [comment]
Looks like there is something wrong with your PHP environment.
