### ISSUE TITLE
Regression bug on PHPUnit 4.8.36 when debugging coverage

### ISSUE THREAD

**Issue by pharazon** [sebastianbergmann/php-code-coverage#574]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 2.2.4
| PHP version               | PHP 7.1.10-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Sep 29 2017 17:04:25) ( NTS )
| Driver                    | Xdebug
| Xdebug version (if used)  | 2.5.5
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 4.8.36

I get the same error when running phpunit 4.8.36  with code coverage than what is reported to be fixed on PHPUnit 4.6
https://github.com/sebastianbergmann/php-code-coverage/issues/231

**Comment by sebastianbergmann** [comment]
PHPUnit 4.8 is no longer supported. Please open a new ticket in case this still applies to a supported version of PHPUnit.

**Comment by pharazon** [comment]
Thanks, it works ok on phpUnit 6.5 and php-code-coverage 5.3.0!
