### ISSUE TITLE
license of html5shiv.min.js

### ISSUE THREAD

**Issue by luisapace** [sebastianbergmann/php-code-coverage#576]
Hi, 
in the file at php-code-coverage-2.2.4/src/CodeCoverage/Report/HTML/Renderer/Template/js/html5shiv.min.js
is specified: 
*** @preserve HTML5 Shiv 3.7.2 | @afarkas @jdalton @jon_neal @rem | MIT/GPL2 Licensed**
I suppose that it's dual license between MIT OR GPL2, so I can use one of twos, at my choose.
Am I right?

Thanks.

**Comment by sebastianbergmann** [comment]
That would be a question for the maintainers of that project.

**Comment by luisapace** [comment]
Could you please tell me who are the maintainers of the project so I can contact them? thanks
