### ISSUE TITLE
Weird coverage on case statements

### ISSUE THREAD

**Issue by Chi-teck** [sebastianbergmann/php-code-coverage#577]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 5.3.0
| PHP version               | 7.2.1
| Driver                    | Xdebug
| Xdebug version (if used)  | 2.6.0beta1
| Installation Method       | Composer (global)
| Usage Method              | PHPUnit
| PHPUnit version | 6.5.5

![switch-coverage](https://user-images.githubusercontent.com/673139/34913862-45741476-f929-11e7-8989-4c17af62feeb.png)

Similar issue on S.O.
https://stackoverflow.com/questions/43255885/phpunit-code-coverage-strange-non-executed-code-on-switch-statement

**Comment by sebastianbergmann** [comment]
@derickr can correct me if I'm wrong, but IIRC this has been fixed already (after Xdebug 2.6.0beta1).

**Comment by derickr** [comment]
Yes. After beta1. Planning to do beta2 today with the fix.
