### ISSUE TITLE
edge case with <?php and ?>not documented

### ISSUE THREAD

**Issue by uglyoldbob** [sebastianbergmann/php-code-coverage#581]
I'm seeing some unexpected results when using ?> and <?php in a script.

I believe this is an undocumented edge case.

This statement does not get marked as covered.

`<?php echo "Some stuff"; ?>`

This statement gets marked as covered.

```
<?php

 echo "Some stuff"; 

?>
```

**Comment by sebastianbergmann** [comment]
CC @derickr

**Comment by derickr** [comment]
I can't see any reason why this would be a problem. In both cases there is an EXT_STMT and ECHO on the right line in VLD output. So more information required.
