### ISSUE TITLE
Target directories are not created recursively

### ISSUE THREAD

**Issue by KanDisheng** [sebastianbergmann/php-code-coverage#584]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 6.0.0
| PHP version               | 7.2.1
| Driver                    | Xdebug
| Xdebug version (if used)  | 2.6.0
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 7.0.0

When I generate code coverage report in Clover XML format, there was an error:

```
PHP Fatal error:  Uncaught RuntimeException: Directory "Some Path" was not created
```

It could automatically create folders when the php-code-coverage version less than 6.0.0, version 6.0.0 could not.

**Comment by sebastianbergmann** [comment]
I cannot reproduce this:
```
$ ll /tmp/does-not-exist                                               
ls: cannot access '/tmp/does-not-exist': No such file or directory

$ ./vendor/bin/phpunit --coverage-clover /tmp/does-not-exist/clover.xml
PHPUnit 7.0.0 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.2.2 with Xdebug 2.6.0
Configuration: /home/sb/thePHP.cc/terraforming/phpunit.xml

................................                                  32 / 32 (100%)

Time: 74 ms, Memory: 6.00MB

OK (32 tests, 42 assertions)

Generating code coverage report in Clover XML format ... done

$ ll /tmp/does-not-exist                                               
total 12K
-rw-r--r--. 1 sb sb 8,1K  2. Feb 07:28 clover.xml
```

**Comment by KanDisheng** [comment]
Try /tmp/does-not-exist-1/does-not-exist-2

**Comment by sebastianbergmann** [comment]
Now I can reproduce it, thanks.
