### ISSUE TITLE
Creating target directories fails with custom error handler that doesn't ignore warnings

### ISSUE THREAD

**Issue by zealsolutions** [sebastianbergmann/php-code-coverage#585]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 6.0.1
| PHP version               | 7.1.11
| Driver                    | Xdebug
| Xdebug version (if used)  | 2.5.5
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 7.0.0

When I generate a code coverage report in HTML format, I get the error "mkdir(): File exists" in src/Report/Html/Facade.php:164

This ended up being an issue with my custom PHP error handler, as set by set_error_handler(), but I wanted to mention this here in case this behavior is unintentional or to help someone else who runs into this.

In the php-code-coverage version 5.3 code around getting directories, [is_dir() was run before mkdir()](https://github.com/sebastianbergmann/php-code-coverage/blob/5.3/src/Report/Html/Facade.php#L175), so if a directory already existed, you'd never hit mkdir() and its ensuing warnings.

In the new code (6.0.1), "[!@\mkdir($directory, 0777, true) && !\is_dir($directory)](https://github.com/sebastianbergmann/php-code-coverage/blob/master/src/Report/Html/Facade.php#L164)", so mkdir() and its warnings get hit if the directory exists.

The fix was to add the following to the top of my error handler, [as described on the PHP error control operators](http://php.net/manual/en/language.operators.errorcontrol.php) and [as shown in Example 1 on the error_reporting() page](http://php.net/manual/en/function.set-error-handler.php).
```
    if (!(error_reporting() & $errno)) {
        // This error code is not included in error_reporting, so let it fall
        // through to the standard PHP error handler
        return false;
    }
```

Sorry for the report if this is just a personal problem, but I've never run into this particular issue with any other libraries I've used and this is a change from the previous version of php-code-coverage.

**Comment by garak** [comment]
I encountered this same problem on an environment I can't control (with `xdebug.scream=1`).
I think that the error suppression is really an ugly solution, can't we just try/catch on ErrorException?

**Comment by MarkusRodler** [comment]
I confirm this issues with the new 6.0.x versions. It generates a warning on line 106 and 164 of the Facade class as mentioned above.

Here is an example output of the warnings:
![image](https://user-images.githubusercontent.com/14873906/40420116-92a9b26e-5e87-11e8-9c38-bdbd0ba2d583.png)

@sebastianbergmann Reverting this file back to 5.3.x resolves the issues for me.
