### ISSUE TITLE
Statement counts vary when using addUncoveredFilesFromWhitelist

### ISSUE THREAD

**Issue by michaelbutler** [sebastianbergmann/php-code-coverage#586]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 5.3.0
| PHP version               | 7.1.14
| Driver                    | Xdebug
| Xdebug version (if used)  | 2.6.0
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 6.5.6

When using the `addUncoveredFilesFromWhitelist` feature of whitelist, in files that were not "touched", lines that contain only a `{`, call it Line X, (e.g. opening bracket of a method call) are reported as statements (stmt) in clover xml output. However, when the source file **is** touched, Line X is not reported as a statement. Thus, for varying test suite runs, the same source will not have the same number of total statements (for that file and also for the overall total).

This can cause inconsistent results with custom tooling we are trying to write. It would be good if the total number of statements is consistent for a given source file, no matter if it was touched or not.

Source Two.php file snippet:

```php
37    public function __construct($test_value = '')
38    {
39        if ($test_value === 'yes') {
40            throw new \RuntimeException('Cannot use yes as test value');
41        }
42
43        $this->foo = $test_value;
44    }
```

Running `php vendor/bin/phpunit --coverage-clover=full.xml`,
File Two.php Touched, reports 8 statements:

```xml
      <file name="/Users/testuser/tmp/phpunit-issue-testing/src/Two/Two.php">
        <class name="MyProj\Two\Two" namespace="MyProj\Two">
          <metrics complexity="5" methods="3" coveredmethods="0" conditionals="0" coveredconditionals="0" statements="8" coveredstatements="5" elements="11" coveredelements="5"/>
        </class>
        <line num="37" type="method" name="__construct" visibility="public" complexity="2" crap="2.06" count="1"/>
        <line num="39" type="stmt" count="1"/>
        <line num="40" type="stmt" count="0"/>
        <line num="43" type="stmt" count="1"/>
        <line num="44" type="stmt" count="1"/>
        <line num="50" type="method" name="doubleFoo" visibility="public" complexity="1" crap="2" count="0"/>
        <line num="52" type="stmt" count="0"/>
        <line num="60" type="method" name="powerFoo" visibility="public" complexity="2" crap="2.15" count="1"/>
        <line num="62" type="stmt" count="1"/>
        <line num="63" type="stmt" count="0"/>
        <line num="66" type="stmt" count="1"/>
        <metrics loc="68" ncloc="51" classes="1" methods="3" coveredmethods="0" conditionals="0" coveredconditionals="0" statements="8" coveredstatements="5" elements="11" coveredelements="5"/>
      </file>
```

Running `php vendor/bin/phpunit --coverage-clover=partial.xml test/one/`,
File Two.php Not Touched, reports 15 statements:

```xml
      <file name="/Users/testuser/tmp/phpunit-issue-testing/src/Two/Two.php">
        <class name="MyProj\Two\Two" namespace="MyProj\Two">
          <metrics complexity="5" methods="3" coveredmethods="0" conditionals="0" coveredconditionals="0" statements="15" coveredstatements="0" elements="18" coveredelements="0"/>
        </class>
        <line num="37" type="method" name="__construct" visibility="public" complexity="2" crap="6" count="0"/>
        <line num="38" type="stmt" count="0"/>
        <line num="39" type="stmt" count="0"/>
        <line num="40" type="stmt" count="0"/>
        <line num="41" type="stmt" count="0"/>
        <line num="43" type="stmt" count="0"/>
        <line num="44" type="stmt" count="0"/>
        <line num="50" type="method" name="doubleFoo" visibility="public" complexity="1" crap="2" count="0"/>
        <line num="51" type="stmt" count="0"/>
        <line num="52" type="stmt" count="0"/>
        <line num="53" type="stmt" count="0"/>
        <line num="60" type="method" name="powerFoo" visibility="public" complexity="2" crap="6" count="0"/>
        <line num="61" type="stmt" count="0"/>
        <line num="62" type="stmt" count="0"/>
        <line num="63" type="stmt" count="0"/>
        <line num="64" type="stmt" count="0"/>
        <line num="66" type="stmt" count="0"/>
        <line num="67" type="stmt" count="0"/>
        <metrics loc="68" ncloc="51" classes="1" methods="3" coveredmethods="0" conditionals="0" coveredconditionals="0" statements="15" coveredstatements="0" elements="18" coveredelements="0"/>
      </file>
```

I have a full reproduce case in this pull request of a test project, I've tried to minimized it down to the bare minimum (it requires two tests & two source files to see the result clearly): https://github.com/michaelbutler/phpunit-issue-testing/pull/1

**Comment by sebastianbergmann** [comment]
Sounds like you do not have `<whitelist processUncoveredFilesFromWhitelist="true">`.

**Comment by michaelbutler** [comment]
Wow I thought there was only one setting, not process vs add. Will confirm in 9 hours if this fixes the issue.

**Comment by sebastianbergmann** [comment]
* `addUncoveredFilesFromWhitelist="true"`: All whitelisted files appear in the code coverage report
* `processUncoveredFilesFromWhitelist="true"`: Uncovered whitelisted files are loaded and processed for more detailed information

**Comment by michaelbutler** [comment]
Thanks so much.
