### ISSUE TITLE
Different code line numbers shown for the same source file, depending on when the class is loaded

### ISSUE THREAD

**Issue by czirkoszoltan** [sebastianbergmann/php-code-coverage#594]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 5.3.0
| PHP version               | 7.0.25-0ubuntu0.16.04.1
| Driver                    | Xdebug
| Xdebug version (if used)  | 2.4.0
| Installation Method       | Composer
| Usage Method              | see example

I have three identical classes named A, B and C (see `a.class.php` and the comment below). Depending on when they are loaded, they are treated to contain a different amount of code. Sometimes global code lines are ignored, sometimes `try` lines and block ending braces are treated as if they contained executable code.

Class A is included before invoking `$coverage->start()`. Class B is included (maybe autoloaded, same result) during the test. Class C is never included. With the Xdebug 2.4.0 driver, I get:

| file | lines run / all code lines
| -----| ---------------
| A    | 0/5
| B    | 1/6
| C    | 0/8

With PHPDBG 0.5.0 (same PHP version), I get:

| file | lines run / all code lines
| -----| ---------------
| A    | 0/5
| B    | 1/5
| C    | 0/8

The number of lines run is OK (only the global `echo` in `b.class.php` did run during the test), however the number of all code lines should be the same for all classes, regardless when they are loaded.

For a project of 50k lines, this can easily add up to 5k/10k difference of the *all code lines* metric, depending on which classes were autoloaded and which were not required during a particular test. This causes coverage percentage metric to shift as well.

Test case:
```php
<?php

require_once __DIR__ . "/vendor/autoload.php";

$coverage = new SebastianBergmann\CodeCoverage\CodeCoverage;
$coverage->filter()->addFileToWhiteList(__DIR__ . "/a.class.php");
$coverage->filter()->addFileToWhiteList(__DIR__ . "/b.class.php");
$coverage->filter()->addFileToWhiteList(__DIR__ . "/c.class.php");

require_once __DIR__ . "/a.class.php";      // included before test
$coverage->start('test');
require_once __DIR__ . "/b.class.php";      // included during test
$coverage->stop();
// require_once __DIR__ . "/c.class.php";  // never included

$writer = new \SebastianBergmann\CodeCoverage\Report\Html\Facade;
$writer->process($coverage, "/tmp/code-coverage-report");
```

`a.class.php`:
```php
<?php

class A {
    public function __construct() {
        echo "A constructed\n";
        try {
            echo "try";
        } catch (\Exception $e) {
            echo "catch";
        }
    }
}

echo "A loaded\n";
```

`b.class.php` and `c.class.php` are the same, only with names changed.

**Comment by sebastianbergmann** [comment]
The data for files that are not loaded during test execution can only be correct when `processUncoveredFilesFromWhitelist="true"` is set.

**Comment by sebastianbergmann** [comment]
This is what https://github.com/sebastianbergmann/phpunit-documentation-english/issues/42 is about.

**Comment by czirkoszoltan** [comment]
Please link the documentation at http://phpunit.readthedocs.io/en/7.1/code-coverage-analysis.html in the readme.md file of this project then! The github main page at https://github.com/sebastianbergmann/php-code-coverage/ is the main source of documentation and starting point for anybody finding the project.
