### ISSUE TITLE
elseif with empty marked as not executed

### ISSUE THREAD

**Issue by pentatonicfunk** [sebastianbergmann/php-code-coverage#598]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 5.3.0
| PHP version               | 7.2.3
| Driver                    | XDebug
| Xdebug version (if used)  | 2.6.0
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 6.5.7

```

90 | $active_addons = get_option( self::$_active_addons_option, false );
91 | if ( false === $active_addons ) {
92 | $this->is_non_exist_activated_option = true;
93 | $active_addons                       = array();
94 | } elseif ( empty( $active_addons ) ) { //<=== this one marked as NOT Executed
95 | $active_addons                   = array();//<=== this one marked as Executed
96 | $this->is_empty_activated_option = true;//<=== this one marked as Executed
97 | }
```

**Comment by sebastianbergmann** [comment]
There can be many reasons why a specific line is not covered. Each of them is likely a different issue. In order to be able to reproduce *anything* and not get bogged down with details, you need to provide the following **in ONE new issue per case**.

That means:

- The exact versions of (this is what the template requires too, but more):
  - PHP
  - PHP Code Coverage
  - Xdebug
  - PHPUnit
- ```php -v``` output
- Either a ```.tar.gz``` archive or a GitHub repository with a reproduce case. With **one** file that shows the problem and **one** test case file (with the exception that sometimes, you might need **two** source files to show a problem.

This information should be filed as **one specific case per issue**.

CC @derickr

**Comment by sebastianbergmann** [comment]
If you have the same issue then maybe you can provide the reproducing example that I requested in https://github.com/sebastianbergmann/php-code-coverage/issues/598#issuecomment-375333422.

**Comment by koponk04** [comment]
so this is my simple code : 
```
<?php
namespace Kaskus\Platform\Widget\Service;

class DisplayShowcaseService
{
	const ALL_NOT_EMPTY = 'all input not empty';
	const INPUT_1_EMPTY = 'empty input 1';
	const INPUT_2_EMPTY = 'empty input 2';

	public function someFunction($input1, $input2)
	{
		$output = self::ALL_NOT_EMPTY;
		if (empty($input1)) {
			$output = self::INPUT_1_EMPTY;
		} elseif (empty($input2)) {
			$output = self::INPUT_2_EMPTY;
		}

		return $output;
	}
}
```

and this is my unit test : 
```
<?php
namespace Kaskus\Platform\Widget\Service;

use PHPUnit\Framework\TestCase;

class DisplayShowcaseServiceTest extends TestCase
{
	public function test_someFunction_EmptyInput1_ReturnEmptyInput1()
	{
		$service = new DisplayShowcaseService();
		$input1 = '';
		$input2 = 'not empty';
		$result = $service->someFunction($input1, $input2);
		$this->assertEquals($result, DisplayShowcaseService::INPUT_1_EMPTY);
	}

	public function test_someFunction_EmptyInput2_ReturnEmptyInput2()
	{
		$service = new DisplayShowcaseService();
		$input1 = 'not empty';
		$input2 = '';
		$result = $service->someFunction($input1, $input2);
		$this->assertEquals($result, DisplayShowcaseService::INPUT_2_EMPTY);
	}

	public function test_someFunction_AllInputEmpty_ReturnAllEmptyInput()
	{
		$service = new DisplayShowcaseService();
		$input1 = 'not empty';
		$input2 = 'not empty';
		$result = $service->someFunction($input1, $input2);
		$this->assertEquals($result, DisplayShowcaseService::ALL_NOT_EMPTY);
	}
}

```

my xml : 
```
<?xml version="1.0" encoding="UTF-8"?>
<phpunit backupGlobals="false" backupStaticAttributes="false"
	bootstrap="bootstrap/phpunit.php" colors="true"
	convertErrorsToExceptions="true" convertNoticesToExceptions="true"
	convertWarningsToExceptions="true" processIsolation="false"
	stopOnFailure="false" beStrictAboutTestsThatDoNotTestAnything="false">

	<logging>
		<log type="coverage-html" target="build/html" lowUpperBound="35"
			 highLowerBound="70"/>
		<log type="coverage-clover" target="build/coverage.xml"/>
		<log type="junit" target="build/junit.xml"/>
	</logging>
</phpunit>

```

and this is the coverage : 
![sebas2](https://user-images.githubusercontent.com/17003188/46863611-14631000-ce42-11e8-9678-1f1480081a93.png)

**Comment by koponk04** [comment]
btw, if i use : 
```
} elseif (empty($input2) == true) {
```
some how it works,,,

thanks,

**Comment by koponk04** [comment]
and my environment : 
phpunit/phpunit :  7.4.*
php version : 7.1.22-1+ubuntu16.04.1+deb.sury.org+1
