### ISSUE TITLE
Add Cobertura XML reporting

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/php-code-coverage#6]

**Comment by rask** [comment]
Sorry for necro, just want to know whether the current XML coverage reporter represents Cobertura in any way? Some googling shows results from people saying that the format is Cobertura, but the source code looks different to me.

**Comment by sebastianbergmann** [comment]
No, we do not support Cobertura.

**Comment by rask** [comment]
Okay, thanks. Will look into it some more in case one would be a good addition at some point.
