### ISSUE TITLE
Uncovered code marked as covered

### ISSUE THREAD

**Issue by guytomer** [sebastianbergmann/php-code-coverage#600]
When running test on a piece of code that should not be covered,
it is marked as covered.
| PHPUnit version     | 7.0.3
| PHP version         | 7.2.4
| Installation Method | Composer

Composer info:
doctrine/instantiator              1.1.0  A small, lightweight utility to instantiate objects in PHP without invoking their constructors
mikey179/vfsStream                 v1.6.5 Virtual file system to mock the real file system in unit tests.
myclabs/deep-copy                  1.7.0  Create deep copies (clones) of your objects
phar-io/manifest                   1.0.1  Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                    1.0.1  Library for handling version information and constraints
phpdocumentor/reflection-common    1.0.1  Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock  4.3.0  With this component, a library can provide support for annotations via DocBlocks or otherwise ...
phpdocumentor/type-resolver        0.4.0
phpspec/prophecy                   1.7.5  Highly opinionated mocking framework for PHP 5.3+
phpunit/dbunit                     4.0.0  PHPUnit extension for database interaction testing
phpunit/php-code-coverage          6.0.1  Library that provides collection, processing, and rendering functionality for PHP code coverag...
phpunit/php-file-iterator          1.4.5  FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template          1.2.1  Simple template engine.
phpunit/php-timer                  2.0.0  Utility class for timing
phpunit/php-token-stream           3.0.0  Wrapper around PHP's tokenizer extension.
phpunit/phpunit                    7.0.3  The PHP Unit Testing framework.
phpunit/phpunit-mock-objects       6.0.1  Mock Object library for PHPUnit
sebastian/code-unit-reverse-lookup 1.0.1  Looks up which function or method a line of code belongs to
sebastian/comparator               2.1.3  Provides the functionality to compare PHP values for equality
sebastian/diff                     3.0.0  Diff implementation
sebastian/environment              3.1.0  Provides functionality to handle HHVM/PHP environments
sebastian/exporter                 3.1.0  Provides the functionality to export PHP variables for visualization
sebastian/global-state             2.0.0  Snapshotting of global state
sebastian/object-enumerator        3.0.3  Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector         1.1.1  Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context        3.0.0  Provides functionality to recursively process PHP variables
sebastian/resource-operations      1.0.0  Provides a list of PHP built-in functions that operate on resources
sebastian/version                  2.0.1  Library that helps with managing the version number of Git-hosted PHP projects
symfony/yaml                       v4.0.6 Symfony Yaml Component
theseer/tokenizer                  1.1.0  A small library for converting tokenized PHP source code into XML and potentially other formats
webmozart/assert                   1.3.0  Assertions to validate method input/output with nice error messages.

Code:
```php
public function execute()
{
    $this->email = $this->get_email_html_from_repository($this->directory);
    $this->mail_infos = $this->get_mail_infos();
    $this->websites = $this->get_websites_for_mail_infos();
    foreach ($this->mail_infos as $mail_info)
    {
        $email = $this->create_mail_for_mail_info($mail_info);
        $this->mail_sender->send($email);
        $send_result = $this->mail_sender->get_last_send_result();
        $was_mail_sent = $send_result->result = "success";
        $does_after_send_function_exist = \method_exists($this, "after_send");
        if(false)
        {
            $this->after_send($mail_info, $email);
        }
    }
}
```

This line should not be covered:
$this->after_send($mail_info, $email);

but marked as covered
<img width="784" alt="screen shot 2018-03-30 at 12 18 47" src="https://user-images.githubusercontent.com/1851054/38133069-47ca8f2a-3416-11e8-8b42-a95817846f36.png">

**Comment by sebastianbergmann** [comment]
There can be many reasons why a specific line is (not) covered. Each of them is likely a different issue. In order to be able to reproduce *anything* and not get bogged down with details, you need to provide the following **in ONE new issue per case**.

That means:

- The exact versions of (this is what the template requires too, but more):
  - PHP
  - PHP Code Coverage
  - Xdebug
  - PHPUnit
- ```php -v``` output
- Either a ```.tar.gz``` archive or a GitHub repository with a reproduce case. With **one** file that shows the problem and **one** test case file (with the exception that sometimes, you might need **two** source files to show a problem.

This information should be filed as **one specific case per issue**.

**Comment by guytomer** [comment]
PHP 7.2.4
PHP Code Coverage 6.0.1
Xdebug 2.6.0
PHPUnit 7.0.3

php -v:
PHP 7.2.4 (cli) (built: Mar 29 2018 15:19:46) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.4, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans

.tar.gz archive:
[auto_mail.tar.gz](https://github.com/sebastianbergmann/php-code-coverage/files/1866176/auto_mail.tar.gz)

I hope this is what you need - if something else is required please let me know so I can provide it.
Thank you.

**Comment by sebastianbergmann** [comment]
I need a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

**Comment by CJDennis** [comment]
![orphaned-covered-line](https://user-images.githubusercontent.com/1551236/41454637-7ec485b0-70bd-11e8-8771-dbe29670a8cf.png)

The relevant part from `coverage.serialized` is:

```
    89 => 
    array (
    ),
    90 => 
    array (
    ),
    91 => 
    array (
    ),
    93 => 
    array (
    ),
    94 => 
    array (
    ),
    95 => 
    array (
    ),
    97 => 
    array (
    ),
    98 => 
    array (
    ),
    99 => 
    array (
    ),
    100 => 
    array (
    ),
```

![orphaned-covered-line-2](https://user-images.githubusercontent.com/1551236/41454805-27cdeb4c-70be-11e8-8c74-a06a3ae49c93.png)

The relevant part from `coverage.serialized` is:

```
    140 => 
    array (
    ),
    141 => 
    array (
    ),
    142 => NULL,
    143 => 
    array (
    ),
    144 => 
    array (
    ),
    146 => 
    array (
      0 => 'HMRX\\AppBundle\\Controller\\PharmacistControllerTest::testShouldDownloadAPharmacistDocument',
    ),
    147 => 
    array (
    ),
    148 => 
    array (
    ),
    149 => 
    array (
    ),
    151 => 
    array (
    ),
    152 => 
    array (
    ),
    153 => NULL,
    154 => 
    array (
    ),
    155 => 
    array (
    ),
    156 => 
    array (
    ),
    157 => 
    array (
    ),
    158 => NULL,
    159 => 
    array (
    ),
    160 => 
    array (
    ),
    161 => NULL,
```

This code is part of a huge project. How can I turn it into a minimal example?

**Comment by CJDennis** [comment]
@sebastianbergmann How can we give you a minimal example when we don't know what causes this? From the user's perspective, it happens at random positions in a file, although always the same position if no code changes and the test is run again.

**Comment by derickr** [comment]
For reference, this is the same issue as #589 and #657
