### ISSUE TITLE
Possible to isolate coverage without marking as covered?

### ISSUE THREAD

**Issue by jhoff** [sebastianbergmann/php-code-coverage#601]
So I apologize if this is already possible. I'm not seeing what I'm looking for in the documentation.

Basically, I'm interested in using an annotation like `@covers \Foo\BarClass` in my test class to designate that code coverage should be isolated only that class without just marking everything as covered.

I'm struggling to understand the use case of the `@covers` annotations in general. On one hand they have the desired benefit of not calculating coverage for classes and methods outside of the ones in the annotations, but then on the other hand, they mark those classes and methods as 100% covered whether they were executed or not.

Is it possible to have both? I want real coverage to be marked only for the classes and methods in the annotations.

Hopefully that makes sense. I appreciate everything that you do for the PHP community!

| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 5.3.0
| PHP version               | 7.2.4
| Driver                    | PHPDBG
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 6.4.4

**Comment by sebastianbergmann** [comment]
The `@covers` annotation does not mark a unit of code as 100% covered.
