### ISSUE TITLE
Lines are inconsistent when filtering test suites

### ISSUE THREAD

**Issue by twifty** [sebastianbergmann/php-code-coverage#608]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 6.0.3
| PHP version               | 7.1
| Driver                    | Xdebug
| Xdebug version (if used)  | 2.6.0
| Installation Method       | Composer / PHPUnit PHAR
| Usage Method              | PHPUnit / other
| PHPUnit version (if used) | 7.2.3

Possibly related to #594.

Take the following two classes
```php
class Hello
{
    public function sayHello()
    {
        return 'Hello';
    }
}

class Goodbye
{
    public function sayGoodbye()
    {
        return 'Bye Bye';
    }
}
```
If I run the test with  `--filter HelloTest`, the clover report is populated with all files in the project, as it should be, but for those files which are not covered (in this case the `Goodbye.php` file) the lines are incorrect. There is a `<line>` entry for the opening brace of the `sayGoodbye` method, further adding to the problem this line has the attribute `type="stmt"` which it cannot be since it contains no executable code.

Now, if I run the test with `--filter GoodbyeTest`, those `<line>` elements for the opening braces are omitted. The same is true for running the test without a filter (ie all test classes).

This causes a big problem when merging the resulting clover reports as there is a line count miss match with those extra lines always being in an uncovered state.

This should be reproducible on any project you have handy with at least two test classes.

**Comment by sebastianbergmann** [comment]
The data for files that are not loaded during test execution can only be correct when `processUncoveredFilesFromWhitelist="true"` is set.

**Comment by twifty** [comment]
Ahh, OK. My bad.
