### ISSUE TITLE
how to Install without internet

### ISSUE THREAD

**Issue by kite-nubia** [sebastianbergmann/php-code-coverage#609]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | x.y.z
| PHP version               | x.y.z
| Driver                    | Xdebug / PHPDBG
| Xdebug version (if used)  | x.y.z
| Installation Method       | Composer / PHPUnit PHAR
| Usage Method              | PHPUnit / other
| PHPUnit version (if used) | x.y.z

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry.
