### ISSUE TITLE
Set base_path for assets on html coverage via config

### ISSUE THREAD

**Issue by Jarvvski** [sebastianbergmann/php-code-coverage#610]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 6.3.0
| PHP version               | 7.1.16
| Driver                    | Xdebug
| Xdebug version (if used)  | 2.6.0
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 7.1.4

I was wondering if it's possible to change the root path via config for any _asset_ files, such as `JS` or `css`?

My usage is with uploading the generated html pages to a `gh-pages` branch. The issue is also relevant with embedded `js` code.

You can see the page currently at: https://7cav.github.io/CavApps-Coverage/
With the associated repo at: https://github.com/7Cav/CavApps-Coverage/tree/gh-pages

If this is already a thing (i've looked at things like https://github.com/IcecaveStudios/woodhouse arleady but it's abandoned, I'd be happy to be shown the door!

**Comment by Jarvvski** [comment]
Any news?

**Comment by zephirfan** [comment]
It would be great!

https://phpunit.readthedocs.io/en/7.4/configuration.html?highlight=coverage-html#logging

```xml
<logging>
  <log type="coverage-html" target="/tmp/report" base_path="http://domain.tld/project/tests/"/>
</logging>
```

Default `base_path` is `.`.

**Comment by Jarvvski** [comment]
Hopefully someone sees it 😃

**Comment by Danon** [comment]
It would really be great
