### ISSUE TITLE
Covers should override coversNothing

### ISSUE THREAD

**Issue by Danack** [sebastianbergmann/php-code-coverage#611]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 6.0.3
| PHP version               | N/A
| Driver                    | N/A
| Xdebug version (if used)  | N/A
| Installation Method       | N/A
| Usage Method              | N/A
| PHPUnit version (if used) | N/A

Currently it seems that the `@coversNothing` annotation on a class takes priority over the `@covers` annotation on a method. e.g. this test:

```php
/**
 * @coversNothing
 */
class BarTest extends TestCase
{
    /**
     * @covers \Valide\Rule\ValidCharacters
     */
    public function testValidation($validCharactersPattern, $testValue, $expectedErrorPosition)  {
       ...
    }
}
```

Will never report any coverage for whatever is in the test.

For the following scenario, it would be strongly preferable for the priority to be the other way round: that `@covers` annotations on the methods override the class `@coversNothing` annotation.

# Scenario

I have large set of poorly written test suites which have never used the coverage annotation. I want to start using the coverage annotation, but want to start with a clean slate of what code has coverage or not.

I can add the `@coversNothing` annotation to make all of the tests not report coverage.

I would then like to be able to go through test by test, and write the correct `@covers` annotation.

However some tests are actually integration tests, and so I don't want to add the `@covers` annotation to those.

Because of the current priority of `@coversNothing` over `@covers`, this won't actually produce any useful coverage information.

If the priority was the other way round, migrating to using the `@covers` annotation would be significantly easier.

**Comment by sebastianbergmann** [comment]
I think that I agree, @Danack. Can you send a pull request that implements the change?

**Comment by Danack** [comment]
Sent PR https://github.com/sebastianbergmann/phpunit/pull/3115 so will close this.
