### ISSUE TITLE
Code-coverage cannot capture closure or anonymous functions

### ISSUE THREAD

**Issue by ajcastro** [sebastianbergmann/php-code-coverage#612]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | PHPUnit 7.0.3
| PHP version         | PHP 7.2.4
| Installation Method | Composer

![image](https://user-images.githubusercontent.com/4918318/39406336-c6a30cda-4be7-11e8-8e7a-e9872bfb52e7.png)

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by sebastianbergmann** [comment]
Also note that PHPUnit 7.0 is no longer supported. Please try to reproduce the issue with the latest version of PHPUnit 7.1 as well as the latest version of php-code-coverage.

**Comment by hartono-sulaiman-kaskus** [comment]
i also had this problem

PHPUnit 7.1.5

my code is like this
```
$cacheKey = Article::CACHE_KEY_LIST . '_' .
            $cursorParameter->getParameter('last_published_date') . '_' .
            $cursorParameter->getParameter('last_id') . '_' .
            $limit;

        return CollectionWithMeta::make(
            Cache::tags(Article::CACHE_KEY_LIST)
                ->remember(
                    $cacheKey,
                    config('cache.lifetime'),
                    function () use ($cursorParameter, $limit) {
                        return $this->repository->readManyByCursorAndStatus(
                            $cursorParameter,
                            $limit,
                            Article::STATUS_PUBLISHED
                        );
                    }
                )
        );
```

i got this coverage

![screen shot 2018-05-07 at 9 23 13 am](https://user-images.githubusercontent.com/5936876/39682169-8c490e44-51d8-11e8-89af-e9ae66829ac3.png)


but if i make it to one line, i got this
![screen shot 2018-05-07 at 9 24 33 am](https://user-images.githubusercontent.com/5936876/39682164-881af9cc-51d8-11e8-8e40-1634fcd85709.png)

**Comment by sebastianbergmann** [comment]
@hartono-sulaiman-kaskus That, too, is not a minimal, self-contained, reproducing test case that I (or @derickr) can use to debug this issue in php-code-coverage (or Xdebug).

**Comment by hartono-sulaiman-kaskus** [comment]
okay this is my folder structure

project
project/src
project/src/Product.php
```
<?php
class Product
{
    public function run()
    {
        $c = 'a' . 'b' . 'c';
        $this->methodA(
            '1',
            '2',
            $c,
            [],
            []
        );
        return true;
    }

    private function methodA(
        string $a,
        string $b,
        ?string $c = null,
        array $d = [],
        array $e = []
    ) {
        echo "$a $b $c\n";
    }
}
```
project/src/tests/ProductTest.php
```
<?php

use PHPUnit\Framework\TestCase;

class ProductTest extends TestCase
{
    public function testRun()
    {
        $product = new \Product();
        $this->assertTrue($product->run());
    }
}
```
project/composer.json
```
{
  "require-dev": {
	"phpunit/phpunit": "~7.0"
  },
  "autoload": {
	"classmap": [
	  "src"
	]
  }
}
```
project/phpunit.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<phpunit backupGlobals="false"
         backupStaticAttributes="false"
         bootstrap="vendor/autoload.php"
         colors="true"
         convertErrorsToExceptions="true"
         convertNoticesToExceptions="true"
         convertWarningsToExceptions="true"
         processIsolation="false"
         stopOnFailure="false">
    <filter>
        <whitelist processUncoveredFilesFromWhitelist="true">
            <directory suffix=".php">./src</directory>
        </whitelist>
    </filter>
</phpunit>

```

is it enough?

thanks

**Comment by CJDennis** [comment]
@sebastianbergmann Isn't it a bit unfair to push this back onto the users? How are we supposed to produce a minimal example? I've never seen this bug in tiny code and no-one is going to submit their entire project (i.e. a breach of confidentiality) for you to look at, which you'd reject anyway for being too big.

**Comment by ellisgl** [comment]
Reopening this,
Here's an example I believe: https://github.com/ellisgl/GeekLab-Conf
