### ISSUE TITLE
Merging code coverage files does not handle dead code correctly

### ISSUE THREAD

**Issue by dekker-m** [sebastianbergmann/php-code-coverage#614]
Related to the issue in #409 . The issue still isn't completely resolved. The pull request by @celowsky fixed a lot of the errors mentioned in this issue, but it does not handle all (or at least some) cases of dead code correctly.

The PHP coverage format seems to assign `NULL` as a value if dead code is detected. If another coverage file did not execute the file, this line is still marked as "not executed", after the results have been merged. The `array_key_exists` function in the anonymous function in `merge` returns true for lines which have been marked as dead code. If XDebug detected a line as being dead code, it should not be able to execute it during other runs. In other words: if one of the code coverage reports contains a `null` value for one of the lines, the merged results should be `null` as well. Perhaps someone can think of a where this is false, but from what I can see, this is the case.

To mark those lines as "dead code" in the merged result, there should be a check if lines are `null` in either of the source coverage files. This can easily be implemented in the last foreach loop in the `merge` method. For example:

```php
foreach ($lines as $line => $data) {
    if ($data === null || $this->data[$file][$line] === null) {
        // if the line is marked as "dead code" in either, mark it as dead code in the merged result
        $this->data[$file][$line] = null;
    } else if (!isset($this->data[$file][$line])) {
        // if no data has been set in the current data, overwrite all
        $this->data[$file][$line] = $data;
    } else {
        // otherwise merge data from both coverage files
        $this->data[$file][$line] = \array_unique(
            \array_merge($this->data[$file][$line], $data)
        );
    }
}
```

With the above code the test cases for our project yield the same result when run in a single run and when run in parallel over 4 processes. There are still some minor differences, but this does not look related to merging the coverage files. In fact, the merged .cov files are more accurate then the original coverage in some edge cases with anonymous functions.

**Comment by sebastianbergmann** [comment]
Can you please send a pull request that implements the change you propose? Thanks!

**Comment by dekker-m** [comment]
Against which branch should the pull request be made?

**Comment by sebastianbergmann** [comment]
If the changes made by @celowsky are in `5.3` then to that, otherwise `master`.

**Comment by dekker-m** [comment]
I created a pull request in #618 in against master.
