### ISSUE TITLE
Coverage Finds Classes, Always 0% complete

### ISSUE THREAD

**Issue by n0nag0n** [sebastianbergmann/php-code-coverage#622]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | (phpunit phar, 7.1.5)
| PHP version               | 7.2.5
| Driver                    | Xdebug
| Xdebug version (if used)  | 2.6.0
| Installation Method       | PHPUnit PHAR
| Usage Method              | PHPUnit / other
| PHPUnit version (if used) | 7.1.5

I have tried to get code coverage working 3 separate times without any success over the past year or so. I tried with php71 and now with php72, still I get the same results. Basically when I run this `phpunit --bootstrap tests/_bootstrap.php --whitelist includes/classes/ --whitelist includes/models tests/unit/ --coverage-text` I get this output.

```
Code Coverage Report:      
  2018-05-25 19:29:27      
                           
 Summary:                  
  Classes:  0.00% (0/75)   
  Methods:  0.00% (0/1181) 
  Lines:    0.00% (0/21083)
```

And this is specific to my user on my computer. I have other devs run this same code, and they get the expected output. I created another user on my computer and it is working as expected. So that leads me to believe that something in my user environment is affecting it. I have looked at any funny hidden files in ~/ with no luck. I have removed all my custom commands from .bash_profile and .bashrc. I know it can't be the php version, or the config, because all that still works when I use another user on my Mac. I've looked through several code repos trying to find any form of a config that would affect the way that phpunit runs and pulls coverage reports, but I have found nothing. I originally was using codeception which wraps around PHPUnit, and then I just used PHPUnit directly and both give the same result.

So is there any user, environment variable, config file, that is somehow based on user that would cause this kind of behavior? I'm so close, but I can't connect the dots.

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by n0nag0n** [comment]
So I made a minimal use case in another folder, and of course, that one works just fine. 
![image](https://user-images.githubusercontent.com/2322095/40565002-b6f45b6c-601f-11e8-9bb9-96638cfc2035.png)

I tried cloning my code into another spot on my machine in case I had some ignored files that were causing the conflict....of course I still get the same result. Same codebase on the other user on my machine, same codebase with my other devs, all the same, and it works for them, but not me. Well I guess this points me to something more directly related in my code repo and not a global problem with my user. 

Any random thoughts would be appreciated. Sorry I couldn't get you a reproducing test case.

**Comment by sebastianbergmann** [comment]
Sorry, but I'll have to close this then.

**Comment by n0nag0n** [comment]
I figured it out....and I'm so glad you didn't waste anymore time with it, but it's probably worth mentioning here in case it happens to anyone else. It was how my autoloader was registering files. I was calling the files using a premade CONSTANT, and it worked for all intents and purposes, but it broke when running under code coverage (whether this is a php-code-coverage issue or an xdebug issue, I don't know).

So for instance the following code was breaking...

```php
define("CLASSES_PATH", '/home/blah/includes/classes/');
spl_autoload_register(function($class_name) {
	if(file_exists(CLASSES_PATH.$class_name.'.php')) {
		include_once(CLASSES_PATH.$class_name.'.php');
		return true;
	}
	return false;
});
```

While this one was returning the correct stuff and including the right files.

```php
spl_autoload_register(function($class_name) {
	if(file_exists(__DIR__.'/classes/'.$class_name.'.php')) {
		include_once(__DIR__.'/classes/'.$class_name.'.php');
		return true;
	}
	return false;
});
```

**Comment by n0nag0n** [comment]
@sebastianbergmann In case you didn't see my solution.
