### ISSUE TITLE
Missing lines from "top level" code

### ISSUE THREAD

**Issue by dtowell** [sebastianbergmann/php-code-coverage#625]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | n/a
| PHP version               | 7.1.17
| Driver                    | Xdebug
| Xdebug version (if used)  | 2.6.0
| Installation Method       | n/a
| Usage Method              | other
| PHPUnit version (if used) | n/a

https://bugs.xdebug.org/view.php?id=1559

Unexecuted "top level" code lines are not included in coverage report, yet similar unexecuted code lines inside a function is reported are.

```
<?php
xdebug_start_code_coverage(XDEBUG_CC_UNUSED | XDEBUG_CC_DEAD_CODE);
$x = 5*5;
if ($x < 20) {
    echo "low\n";
    $x = 1000;
}
function f($y) {
    if ($y < 20) {
        echo "low 2\n";
        $y = 1000;
    }
}
f($x);
print_r(xdebug_get_code_coverage());
```

produces:

```
Array
(
    [/var/www/x.php] => Array
        (
            [3] => 1
            [4] => 1
            [8] => 1
            [9] => 1
            [10] => -1
            [11] => -1
            [13] => 1
            [14] => 1
            [15] => 1
        )
)
```

Observe 5 & 6 are missing.

**Comment by sebastianbergmann** [comment]
Why do you open a ticket here in addition to the one for Xdebug?

**Comment by dtowell** [comment]
OH! Sorry, I just realized that this was the wrong forum.
