### ISSUE TITLE
Option beStrictAboutCoversAnnotation=true tries to make you account for lines covered in setUp too

### ISSUE THREAD

**Issue by sg3s** [sebastianbergmann/php-code-coverage#629]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 6.0.7
| PHP version               | 7.2.7
| Driver                    | Xdebug
| Xdebug version (if used)  | 2.6.0
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) |  7.2.6

When using the `beStrictAboutCoversAnnotation="false"` option and when using some frameworks where a setup is used things can get messy quick. This was mentioned in issue #408 as well but the reporter failed to elaborate.

Basically, the lines of code covered during `setUp()` and `tearDown()` are counted as well, and if you do not specify all of the classes/methods touched upon during these methods, php-code-coverage will let you know and mark the test as risky.

For me this results in output like this:

```
1) Tests\Unit\UserTest::testFoo
This test executed code that is not listed as code to be covered or used:
- App\Console\Kernel::commands
- App\Console\Kernel::schedule
- App\Database\BlueprintMixin::belongsTo
- App\Database\BlueprintMixin::createdAtDefaults
- App\Database\BlueprintMixin::deletedAtDefaults
- App\Database\BlueprintMixin::timestampDefaults
- App\Database\BlueprintMixin::trackUpdates
- App\Database\BlueprintMixin::updatedAtDefaults
- App\Providers\AppServiceProvider::boot
- App\Providers\AppServiceProvider::register
- App\Providers\AuthServiceProvider::boot
- App\Providers\BlueprintMixinServiceProvider::boot
- App\Providers\BlueprintMixinServiceProvider::register
- App\Providers\EventServiceProvider::boot
- App\Providers\RouteServiceProvider::boot
- App\Providers\RouteServiceProvider::map
- App\Providers\RouteServiceProvider::mapApiRoutes
- App\Providers\RouteServiceProvider::mapWebRoutes
 ```

Where `Tests\Unit\UserTest` looks like this:

```
namespace Tests\Unit;
use Tests\TestCase;

/**
 * @coversDefaultClass App\Models\User
 */
class UserTest extends TestCase
{
    /**
     * @covers ::foo
     */
    public function testFoo()
    {
        $this->assertEquals('bar', (new \App\Models\User)->foo());
    }
}
```

The class `Tests\Unit\UserTest` extends `Tests\TestCase` where the `setUp()` method is used to build an application context in which the (framework) code can operate and interact with the database.

This is all based on a fairly vanilla / clean setup of Laravel. Reproducing should be as easy as creating a new Laravel application, setting the `beStrictAboutCoversAnnotation` to true and running phpunit with coverage. Laravel provides basic testing scaffolding as part of its default installation.

**Suggestion**
If possible we would want to be as strict as possible, but allow for the setup of the application. Maybe an option to really restrict the coverage checks to the code executed in the `test*()` method? I'm not sure if or how that could work, but it would help us out a lot.

**Comment by sg3s** [comment]
So, not sure this opens it, but I do think this still is an issue, or at least a good spot for improvement. 

I've taken a look at the code, and from what I understand, simply starting tracking of covered files/lines before setup it should be possible to do after, maybe with a flag?

I would try to make it a PR if I can get some direction on how to approach this. We would really like to have this.

**Comment by NunoLopes96** [comment]
This still happens, is there any solution?

**Comment by sg3s** [comment]
@NunoLopesPT While I had an idea how it might be fixed, since I never received any reply, I was not able to do anything with it. I've given up trying to use strict mode.

If you want this fixed you should take a look at the code and try to followup with a PR. I no longer remember where the hooks should be.
