### ISSUE TITLE
@covers not working

### ISSUE THREAD

**Issue by OxCom** [sebastianbergmann/php-code-coverage#631]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 6.0.7
| PHP version               | 7.1.20
| Driver                    | Xdebug
| Xdebug version (if used)  | 2.6.0
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 7.3.1

Second case with the same issue:

| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 5.3.2
| PHP version               | 7.1.20
| Driver                    | Xdebug
| Xdebug version (if used)  | 2.6.0
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 6.5.11

[Minimal example](https://drive.google.com/open?id=1IA65f_APiwqqNZQHgRBu8wPRK1d0KC_e)

**Expecred**:

This test case should be provided with correct coverage report: all specified method should be marked as covered.
```php
/**
 * @covers \Coverage\CoverageClass::shouldBeCovered
 * @covers \Coverage\CoverageClass::shouldBeCoveredToo
 */
public function testShouldBeCovered()
{
    $class = new CoverageClass();
    $value = $class->shouldBeCovered();

    $this->assertNotEmpty($value);
}
```
**Result**

```@covers``` function ignored.

#### Possible issue:
In a method ```\SebastianBergmann\CodeCoverage\CodeCoverage::applyCoversAnnotationFilter()```
there is a code block that applies lines that should be marked as covered:
```php
foreach (\array_keys($data) as $filename) {
    $_linesToBeCovered = \array_flip($linesToBeCovered[$filename]);
    $data[$filename]   = \array_intersect_key($data[$filename], $_linesToBeCovered);
}
```

On a second line of the loop we will have intersection by keys, but value of each key will be the same.
Each line that should be market as "visited" should has value 1. As this lines were marked in ```$data[$filename]```
as -1 (not "visited"), so in a result we still have -1.

#### Possible solution
As in a result of intesection we will have list of the lines that should be marked as "visited", then we can update this loop as:
```php
foreach (\array_keys($data) as $filename) {
    $_linesToBeCovered = \array_flip($linesToBeCovered[$filename]);
    $data[$filename]   = \array_intersect_key($data[$filename], $_linesToBeCovered);
    $data[$filename]   = \array_map(function () {
        return 1;
    }, $data[$filename]);
}
```

**Comment by sebastianbergmann** [comment]
`@covers` does not do what you think it does.

**Comment by OxCom** [comment]
@sebastianbergmann thanks for reply. I was confused by documentation.
