### ISSUE TITLE
Feature request: diff 2 coverage reports

### ISSUE THREAD

**Issue by mikk150** [sebastianbergmann/php-code-coverage#632]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 4.0.8
| PHP version               | 5.6.37
| Driver                    | Xdebug
| Xdebug version (if used)  |2.5.0
| Installation Method       | Composer
| Usage Method              | Codeception
| PHPUnit version (if used) | 5.7.27

It would be really good to diff 2 coverage reports

**Comment by sebastianbergmann** [comment]
That would be outside the scope of this library.
