### ISSUE TITLE
Remove linear search in CodeCoverage::append()

### ISSUE THREAD

**Issue by Netmosfera** [sebastianbergmann/php-code-coverage#635]
There is an occurrence of `in_array()` in that method that slows down CC quite a bit.

```php
foreach ($lines as $k => $v) {
    if ($v === Driver::LINE_EXECUTED) {
        if (empty($this->data[$file][$k]) || !\in_array($id, $this->data[$file][$k])) { // <- here
            $this->data[$file][$k][] = $id;
        }
    }
}
```

I (very naively) changed it to this:

```php
foreach ($lines as $k => $v) {
    if ($v === Driver::LINE_EXECUTED) {
        if (empty($this->data[$file][$k]) || !isset($this->data[$file][$k][$id])) {
            $this->data[$file][$k][$id] = $id;
        }
    }
}
```

And I got the execution time nearly halved. However, I'm not sure that's a 100% valid replacement.

Can you have a look please? Thank you.

**Comment by Netmosfera** [comment]
Not sure how I managed to close this accidentally? However, I tried that change on some of my projects and it looks like it doesn't change the result of code coverage (but still improves speed).

**Comment by sebastianbergmann** [comment]
Please send a pull request against `master` with this change.

**Comment by Netmosfera** [comment]
I'm not sure it's the right way to do it. This:
```
$this->data[$file][$k][$id] = $id;
```
Should probably be a "Set":
```
$this->data[$file][$k][$id] = true;
```
But that's a way bigger change.

**Comment by sebastianbergmann** [comment]
I do not understand what you mean by Should probably be a Set:".

**Comment by Netmosfera** [comment]
"Set" as in the abstract data structure... the php way. 

Use only the set of keys of an array, while all values are set to true, ie `[44 => true]` over `[44 => 44]`. 

If it's not a simple change, just ignore that suggestion.

Thanks

**Comment by 1blankz7** [comment]
The improvements are low according to the xdebug profiler. In addition the change would make some tests fail and we need to check for the usage of the data. 

If we get rid of the guard `empty($this->data[$file][$k]) || !\in_array($id, $this->data[$file][$k])` will not fail, but I am not sure if this will create a sufficient structure.

**Comment by sebastianbergmann** [comment]
If the performance improvement is not that great then I would rather not make the change.

**Comment by Netmosfera** [comment]
@1blankz7 15% of time is not a small improvement
![15%](https://user-images.githubusercontent.com/4203089/46528835-0850de80-c895-11e8-8329-f785df7e0e86.png)
