### ISSUE TITLE
Single line methods are not marked and counted in HTML coverage report

### ISSUE THREAD

**Issue by kwebble** [sebastianbergmann/php-code-coverage#637]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 6.0.5
| PHP version               | 7.1.21
| Driver                    | Xdebug
| Xdebug version (if used)  | 2.6.1
| Installation Method       | PHPUnit PHAR
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 7.0.0

Complete methods written on 1 line that are executed during a test are not counted as executable and not shown as covered in the HTML coverage report.

Code example:

    public function getProviderId    (): string { return $this->providerId;   }
    public function getProviderName  (): string { return $this->providerName; }
    public function getPaymentMethods(): array  { return $this->methods;      }

The PHPUnit HTML report:

![20180920_coverage-report](https://user-images.githubusercontent.com/5430511/45812678-c2125180-bcd0-11e8-8527-2ad0be93dd85.png)

When changing the code layout to this:

    public function getProviderId    (): string {
        return $this->providerId; 
    }
    public function getProviderName  (): string {
        return $this->providerName; 
    }
    public function getPaymentMethods(): array  {
        return $this->methods;      
    }

The lines are counted and shown as covered in the report:

![20180920_coverage-report-ok](https://user-images.githubusercontent.com/5430511/45812670-bd4d9d80-bcd0-11e8-8ec2-1b4008824e8f.png)

**Comment by sebastianbergmann** [comment]
I agree that this is a bug. But I have to say that I am not really motivated to look into this because I believe that code should not be formatted like that. I will, of course, consider a pull request that addresses this.

**Comment by kwebble** [comment]
If you expect the pull request from me then I suggest closing this issue. I briefly looked at the code but can't determine how lines of code are matched to test results and how complex a change would be.
