### ISSUE TITLE
Feature Request: ignore lines matching regular expression

### ISSUE THREAD

**Issue by sebastienbarre** [sebastianbergmann/php-code-coverage#638]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 5.3.2
| PHP version               | 7.2.10
| Driver                    | not sure
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 6.5.8

I'm aware of all the `@codeCoverageIgnore` annotations, but I'm wondering if there is a way to have a configuration option that could let me ignore *all* lines matching a specific regular expression.

The use case here is that we have hundreds and hundreds of files starting like this:
```php
<?php
declare(strict_types=1);

App::uses('GenericCollection', 'Lib/DataStructure');
App::uses('ItemNotFoundException', 'Error');
App::uses('QuickBooksJobIdentifier', 'Lib/Integration/QuickBooks');

class QuickBooksJobIdentifierCollection extends GenericCollection
{
[...]
```

and php-code-coverage systematically choose to flag the `App::uses()` as "not covered", for reasons I don't quite understand. The implementation of `App::uses()` comes from the CakePHP MFC framework by the way:
```
	public static function uses($className, $location) {
		static::$_classMap[$className] = $location;
	}
```

This is problematic for us as the report then shows some missing percentage of coverage, and we don't know if it's because of `App::uses()` or because we forgot to test/cover some critical lines in the code.

Is there a place to hook from `CodeCoverage.php::getLinesToBeIgnored()` maybe?

Thank you

**Comment by sebastienbarre** [comment]
To get the ball rolling, is this a feature you would accept a PR for?

**Comment by sebastianbergmann** [comment]
Sorry, but I am not interested in this functionality.
