### ISSUE TITLE
"else if" code coverage

### ISSUE THREAD

**Issue by jhansche** [sebastianbergmann/php-code-coverage#65]
Not sure if this is an XDebug problem, or php-code-coverage.  Consider this SUT method:

``` php
<?php
function doStuff($a)
{
  if ($a < 0)
  {
    $result = -1;
  }
  else if ($a > 0)
  {
    $result = 1;
  }
  elseif ($a == 0)
  {
    $result = 0;
  }

  return $result;
}
```

Having 3 test methods to test all three code paths, the Code Coverage report will report that the first `else if` line is not executed, but the second `elseif` line is.  Removing the space to make it `elseif` will cause the coverage to be reported properly.

**Comment by ThaDafinser** [comment]
The problem is still alive in PHP 7.1.1 and xdebug 2.5.3.

![image](https://cloud.githubusercontent.com/assets/533017/25939098/f33f6454-3631-11e7-8a46-40571e9e1136.png)
![image](https://cloud.githubusercontent.com/assets/533017/25939139/1e3a91f6-3632-11e7-962a-608f39a44de3.png)

**Comment by GrahamCampbell** [comment]
> The problem is still alive in PHP 7.1.1 and xdebug 2.5.3.

What about the latest versions?
