### ISSUE TITLE
False positive inside foreach loop

### ISSUE THREAD

**Issue by dcrouch79** [sebastianbergmann/php-code-coverage#657]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 6.1.4
| PHP version               | 7.2.10
| Driver                    | Xdebug
| Xdebug version (if used)  | 2.6.0
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 7.4.4

`php -v` output:
```
PHP 7.2.10-0ubuntu0.18.04.1 (cli) (built: Sep 13 2018 13:45:02) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.10-0ubuntu0.18.04.1, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans
```

This is the code that produces the wrong coverage report:
```
class Main
{
    public function run()
    {
        foreach ([1] as $value) {
            if ($value === 1) {
                echo "Is called\n";            // TRUE positive
            } else {
                echo "Not called\n";           // TRUE negative
                echo "Not called either\n";    // FALSE positive!
            }
        }
    }
}
```

The resultant coverage report shows that `echo "Not called either\n";` is covered when it isn't:

![coverage](https://user-images.githubusercontent.com/3524988/49019344-9f476200-f185-11e8-851f-9298adca6ff1.png)

If notice that if I move the body of the foreach loop into a separate function the coverage is then correct. Would be nice not to have to do this.

I've attached a zip of the project to reproduce the issue. Just need to run `composer install` followed by `composer test`.

[php-code-coverage.zip](https://github.com/sebastianbergmann/php-code-coverage/files/2615885/php-code-coverage.zip)

**Comment by sebastianbergmann** [comment]
CC @derickr

**Comment by derickr** [comment]
This is an issue with PHP itself. It puts the ``FE_FREE`` for cleaning up the foreach loop on line 12:

```
compiled vars:  !0 = $value
line     #* E I O op                           fetch          ext  return  operands
-------------------------------------------------------------------------------------
   5     0  E >   EXT_NOP                                                  
   7     1        EXT_STMT                                                 
         2      > FE_RESET_R                                       $1      <array>, ->15
         3    > > FE_FETCH_R                                               $1, !0, ->15
   8     4    >   EXT_STMT                                                 
         5        IS_IDENTICAL                                     ~2      !0, 1
         6      > JMPZ                                                     ~2, ->10
   9     7    >   EXT_STMT                                                 
         8        ECHO                                                     'Is+called%0A'
         9      > JMP                                                      ->3
  11    10    >   EXT_STMT                                                 
        11        ECHO                                                     'Not+called%0A'
  12    12        EXT_STMT                                                 
        13        ECHO                                                     'Not+called+either%0A'
        14      > JMP                                                      ->3
        15    >   FE_FREE                                                  $1
  15    16        EXT_STMT                                                 
        17      > RETURN                                                   null
```

There is nothing that Xdebug can do about this.

**Comment by derickr** [comment]
This is the same issue as https://bugs.xdebug.org/view.php?id=1530 and #589, and I have filed this with PHP as https://bugs.php.net/bug.php?id=76046, which is still open (and ignored?).

**Comment by sebastianbergmann** [comment]
Thanks, @derickr. There is nothing for us to do here, so I closed the issue.

**Comment by carltondickson** [comment]
@dcrouch79. Adding some code after the else's closing bracket, e.g. assert(true) works but your suggestion of extracting the if else part to another function seems much more sensible 👍
