### ISSUE TITLE
Fatal error generating TEXT report $_SERVER['REQUEST_TIME']

### ISSUE THREAD

**Issue by jorgevbo** [sebastianbergmann/php-code-coverage#669]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | master
| PHP version               | 7.3.1
| Driver                    | Xdebug
| Xdebug version (if used)  | 2.7.0.0rc1
| Installation Method       | XDebug source code Compiling
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 8.0.1

Stacktrace when using PHPUnit to generate TEXT report format for code coverage:

PHP Fatal error:  Uncaught TypeError: date() expects parameter 2 to be int, string given in phar:///usr/local/Cellar/phpunit/8.0.1/bin/phpunit/php-code-coverage/Report/Text.php:157
Stack trace:
0: phar:///usr/local/Cellar/phpunit/8.0.1/bin/phpunit/php-code-coverage/Report/Text.php(157): date('  Y-m-d H:i:s', '1549623375')
1: phar:///usr/local/Cellar/phpunit/8.0.1/bin/phpunit/phpunit/TextUI/TestRunner.php(744): SebastianBergmann\CodeCoverage\Report\Text->process(Object(SebastianBergmann\CodeCoverage\CodeCoverage), false)
2: phar:///usr/local/Cellar/phpunit/8.0.1/bin/phpunit/phpunit/TextUI/Command.php(208): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
3: phar:///usr/local/Cellar/phpunit/8.0.1/bin/phpunit/phpunit/TextUI/Command.php(164): PHPUnit\TextUI\Command->run(Array, true)
4: /usr/local/Cellar/phpunit/8.0.1/bin/phpunit(619): PHPUnit\TextUI\Command::main()
:5 {main}
  thrown in phar:///usr/local/Cellar/phpunit/8.0.1/bin/phpunit/php-code-coverage/Report/Text.php on line 157

Fatal error: Uncaught TypeError: date() expects parameter 2 to be int, string given in phar:///usr/local/Cellar/phpunit/8.0.1/bin/phpunit/php-code-coverage/Report/Text.php on line 157

TypeError: date() expects parameter 2 to be int, string given in phar:///usr/local/Cellar/phpunit/8.0.1/bin/phpunit/php-code-coverage/Report/Text.php on line 157

Call Stack:
    0.0010     546728   1. {main}() /usr/local/Cellar/phpunit/8.0.1/bin/phpunit:0
    0.0609    9875528   2. PHPUnit\TextUI\Command::main() /usr/local/Cellar/phpunit/8.0.1/bin/phpunit:619
    0.0609    9875640   3. PHPUnit\TextUI\Command->run() phar:///usr/local/Cellar/phpunit/8.0.1/bin/phpunit/phpunit/TextUI/Command.php:164
    0.4124   33661592   4. PHPUnit\TextUI\TestRunner->doRun() phar:///usr/local/Cellar/phpunit/8.0.1/bin/phpunit/phpunit/TextUI/Command.php:208
    0.6797   35684432   5. SebastianBergmann\CodeCoverage\Report\Text->process() phar:///usr/local/Cellar/phpunit/8.0.1/bin/phpunit/phpunit/TextUI/TestRunner.php:744
    0.6799   35685392   6. date() phar:///usr/local/Cellar/phpunit/8.0.1/bin/phpunit/php-code-coverage/Report/Text.php:157

Same problem like: https://github.com/sebastianbergmann/phpunit/issues/2330 when generating HTML report.

$date = date('D M j G:i:s T Y', $_SERVER['REQUEST_TIME']);

$_SERVER['REQUEST_TIME'] return a string value.

$date = date('D M j G:i:s T Y', (int)$_SERVER['REQUEST_TIME']); ?

**Comment by sebastianbergmann** [comment]
`$_SERVER['REQUEST_TIME']` is predefined by PHP and contains a value of type `int`:
```
php -nr 'var_dump($_SERVER["REQUEST_TIME"]);'
int(1549630502)
```
If `$_SERVER['REQUEST_TIME']` does not contain a value of type `int` then this is because code overwrites `$_SERVER['REQUEST_TIME']`. This could be in your test code, in the code you test, or in code used by the code you test.
