### ISSUE TITLE
clover.xml not generated 

### ISSUE THREAD

**Issue by nownlater** [sebastianbergmann/php-code-coverage#670]
| Q                         | A
| --------------------------| ---------------
| PHP version                   | PHP 7.2.14
| Driver                               | Xdebug 
| Xdebug version (if used)  | v2.6.1,
| Installation Method       | Composer 
| Usage Method              | PHPUnit 
| PHPUnit version (if used) | 8.0.0

    <testsuite name="tests">
        <directory suffix="Test.php">./tests</directory>
        <file>tests/LoginModelTest.php</file>
    </testsuite>
    <filter>
    <whitelist addUncoveredFilesFromWhitelist="true">
            <directory suffix=".php">./</directory>        
            <file>./model/LoginModel.php</file> 
            <file>./login.php</file>      
    </whitelist>
    </filter> 
    <logging> 
      <log type="coverage-clover" target="./reports/clover.xml"/>
       <log type="coverage-html"   target="./reports/coverage_html" lowUpperBound="35" highLowerBound="70"></log> 
        <log type="coverage-xml" target="./reports/coverage.xml"/>
    </logging>         

execute result console ↓
------------------------------------------------------------------------------------------------------
PHPUnit 8.0.0 by Sebastian Bergmann and contributors.

..                                                                  2 / 2 (100%)

Time: 2.11 seconds, Memory: 6.00MB

OK (2 tests, 2 assertions)

Generating code coverage report in Clover XML format ... done

Generating code coverage report in HTML format ... done
Generating code coverage report in PHPUnit XML format ... done

my php.ini setting ↓
--------------------------------------------------------------------------------------------------------
[xdebug]
zend_extension="C:\php\ext\php_xdebug-2.6.1-7.2-vc15-x86_64.dll"
xdebug.remote_enable=1
xdebug.remote_autostart=1
xdebug.default_enable=on
xdebug.remote_host=localhost
xdebug.remote_port=9000
xdebug.remote_connect_back = 1
xdebug.max_nesting_level = 512

//coverage.xml and coverage_htlm was generated but clover.xml was not generated...
please help if you could.

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by nownlater** [comment]
thank you for reply
testcase↓
---------------------------------------------------------------------------------------------------------


require_once __DIR__ . '/../model/LoginModel.php';

require_once __DIR__ . '/../tests/PDOMock.php';

require_once __DIR__ . '/../tests/PDOStatementMock.php';

use \PHPUnit\Framework\TestCase;

class LoginModelTest extends TestCase {
    /**
     * @test
     * $conn = null pattern
     *
     */
    public function test_doLoginNull() {

        $this->loginModel = new LoginModel();

        $conn = NULL;
        $this->loginModel->doLogin($conn);

        $this->loginModel->setErrMsg('XXX');

        $this->assertEquals('XXX', $this->loginModel->getErrMsg());
    }

    /**
     * @test
     *
     *
     */
    public function test_doLogin() {

        //mockset
        $pdoStub = $this->createMock(PDOMock::class);

        $pdoStateStub = $this->createMock(PDOStatementMock::class);

        // stubset
        //$pdoStub->expects($this->any())->method('__construct')->will($this->onConsecutiveCalls(NULL));
        //$pdoStub->__construct("oci:dbname=" . OFFICIAL_ORAHOST . ":" . OFFICIAL_ORAPORT . "/" . OFFICIAL_ORASID . ";charset=" . OFFICIAL_ORACHAR, OFFICIAL_ORAUSER, OFFICIAL_ORAPASS, NULL);
        
        $pdoStub->expects($this->any())->method('setAttribute')->willReturn(TRUE);

        $pdoStub->setAttribute(PDO::ATTR_EMULATE_PREPARES, FALSE);

        $selectSQL = "SELECT USER_ID, USER_NAME, AUTH_LEVEL, USER_PASSWORD,REMARK
                    FROM USER_MANAGEMENT
                    WHERE USER_ID = :USER_ID";

        $pdoStub->expects($this->any())->method('prepare')->willReturn($pdoStateStub);

       
        $pdoStateStub = $pdoStub->prepare($selectSQL);

        
        $pdoStateStub->method('bindValue')->willReturn(TRUE);

        
        $pdoStateStub->bindValue(':USER_ID', filter_input(INPUT_POST, "id"));

        
        $pdoStateStub->method('execute')->willReturn(TRUE);

       
        $pdoStateStub->execute();

        $loginModel = new LoginModel();
       
        $loginModel->doLogin($pdoStub);
       
        $loginModel->setErrMsg('XXX');

        $this->assertEquals('XXX', $loginModel->getErrMsg());
    }


//PDOMock.php is extends PDOclass.
//PDOStatementMock is extends PDOStatementclass sir.

**Comment by nownlater** [comment]
sorry and execute PHPUnit on WindowsPowerShell console contents like this↓
--------------------------------------------------------------------------
PS C:\work> phpunit --coverage-clover clover C:\work>
PHPUnit 8.0.0 by Sebastian Bergmann and contributors.

Error:         No whitelist is configured, no code coverage will be generated.

..                                                                  2 / 2 (100%)

Time: 715 ms, Memory: 6.00MB

OK (2 tests, 2 assertions)

**Comment by sebastianbergmann** [comment]
That is neither minimal nor self-contained. But `Error: No whitelist is configured, no code coverage will be generated.` should tell you exactly what is going on.

**Comment by nownlater** [comment]
Sorry for the poor English...
I confused netbeans's console is No Error and clover.xml wasn't generated but in Powershell Error.
whitelist is not good?
