### ISSUE TITLE
when use lambda function, occurred error with Code coverage html issue

### ISSUE THREAD

**Issue by lbayarkhuu** [sebastianbergmann/php-code-coverage#674]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 5.7.27
| PHP version         | 7.1
| Installation Method | Composer / PHAR

![Screenshot from 2019-04-03 09-45-01](https://user-images.githubusercontent.com/6688626/55447241-82b8ac00-55f5-11e9-98c6-ce5d91998bd2.png)

**Comment by sebastianbergmann** [comment]
I do not understant what you are trying to report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue. Please do not post screenshots of code but provide the actual code as text.
