### ISSUE TITLE
Problem with coverage-html

### ISSUE THREAD

**Issue by blink2004** [sebastianbergmann/php-code-coverage#675]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | ?
| PHP version               | 7.3.3
| Driver                    | Xdebug 
| Xdebug version (if used)  | 2.7.0
| Installation Method       | PHPUnit PHAR
| Usage Method              | PHPUnit 
| PHPUnit version (if used) | 8.0.5

I just created own class and covered it with PHPUnit's tests. After executed command `phpunit -v` (1) they working. Was generated report about covered code by command `phpunit --coverage-html ./report/` (2) then. It's working.

I decided use PHPUnit in more real project then. Took CMS WordPress by base. Created file /vendor/autolad.php, writen `require_once '/wp-include/class-wp.php';`. Run command (1) receive OK result. Then I decided generate report by command (2) and received message:
`PHP Fatal error:  Cannot declare class WP, because the name is already in use in /var/www/html/wordpress/wp-includes/class-wp.php on line 8`

I commented line in autolad.php ```//require_once '/wp-include/class-wp.php';```.

Then run command (2) again. Tests was executed - OK, but on generating report step received error:
`Generating code coverage report in HTML format ...PHP Fatal error:  Uncaught TypeError: date() expects parameter 2 to be int, string given in phar:///usr/local/bin/phpunit/php-code-coverage/Report/Html/Facade.php:63
Stack trace:
#0 phar:///usr/local/bin/phpunit/php-code-coverage/Report/Html/Facade.php(63): date('D M j G:i:s T Y', '1554286376')`

If I use XML format instead of *HTML* then all working.

I understand what mean this error, but don't understand why it happens with WordPress and not with my own demo-class? What I'm doing wrong?

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by blink2004** [comment]
Ok, just few minutes.

I'm using "Linux ubuntu-server 4.4.0-145-generic #171-Ubuntu SMP Tue Mar 26 12:44:29 UTC 2019 i686 i686 i686 GNU/Linux", 32-bit

1. Create folder "wordpress" in `/var/www/html/` as user (not a root)
2. Download and install WordPress as described by link [https://codex.wordpress.org/Installing_WordPress#Detailed_Instructions](https://codex.wordpress.org/Installing_WordPress#Detailed_Instructions).
3. Run command `phpunit --generate-configuration`. I'm added only one file for coverage ```<file>wp-includes/class-wp-admin-bar.php</file>```
4. Create folder `./tests` and `./tests/report`
5. Create file `./tests/demoTest.php` with any test methods, for example:
```
use PHPUnit\Framework\TestCase;

class adminBarTest extends TestCase {

    function testGetAdmin(){
        $this->assertTrue(true);
    }

} 
```
6. Run `phpunit -v` (must be OK)
7. Run `phpunit --coverage-html ./tests/report/`

**Comment by blink2004** [comment]
Did you reproduce it?

**Comment by silentdragonz** [comment]
Not sure if you figured it out, but I've encountered something similar with WordPress projects. WP clobbers all the superglobals with addslashes and now that PHP is adding more typing it breaks everything. The fix we've been doing is in `wp-config.php` at the very bottom add: `$_SERVER['REQUEST_TIME'] = (int) $_SERVER['REQUEST_TIME'];`

**Comment by blink2004** [comment]
@silentdragonz , that's great!
I just added in the end of file `.\wordpress\wp-config.php` your code:
`
//...

/** Sets up WordPress vars and included files. */
require_once( ABSPATH . 'wp-settings.php' );

$_SERVER['REQUEST_TIME'] = (int) $_SERVER['REQUEST_TIME'];

`
and executed command `phpunit --coverage-html ./report/`. All is OK!
Thank you so much!
