### ISSUE TITLE
Code-coverage broken due to anonymous function / closure

### ISSUE THREAD

**Issue by ellisgl** [sebastianbergmann/php-code-coverage#683]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 7.0.4
| PHP version               | 7.2.0 / 7.2.15
| Driver                    | Xdebug 
| Xdebug version (if used)  | 2.6.0
| Installation Method       | Composer 
| Usage Method              | PHPUnit 
| PHPUnit version (if used) | 8.1.6

I belive this is related to Item #612 . You can see all the code here: https://github.com/ellisgl/GeekLab-Conf and the report here https://codecov.io/gh/ellisgl/GeekLab-Conf/tree/master/src

(I know, this code isn't the best - it's being re-written, and should get coverage with ease)

**Comment by sebastianbergmann** [comment]
The HTML report you link is generated by custom code by codecov.io based on, presumably, XML that is generated by PHPUnit. Please understand that I cannot look at third-party reports.

What I can do is look at an HTML code coverage report generated with `--coverage-html` by out-of-the-box PHPUnit. Can you point me to the sourcecode location you are interested in?

**Comment by ellisgl** [comment]
https://github.com/ellisgl/GeekLab-Conf/tree/master/build --- There's the report.
If you noticed, pretty much everything saying it's isn't being called, Even the constructors!

**Comment by sebastianbergmann** [comment]
I do not see anything wrong with your code coverage report. It looks to me like you are excluding the code you are interested in from code coverage through `@covers` annotations that are too agressive.

**Comment by ellisgl** [comment]
I get the same thing without the @covers
