### ISSUE TITLE
The results of the second visit will cover the first

### ISSUE THREAD

**Issue by fangxiaoyaner** [sebastianbergmann/php-code-coverage#684]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 6.1.4
| PHP version               | 7.1.10
| Driver                    | Xdebug / PHPDBG
| Xdebug version (if used)  | 2.7.0
| Installation Method       | Composer / PHPUnit PHAR
| Usage Method              | PHPUnit / other
| PHPUnit version (if used) | x.y.z

The results of the second visit will cover the first. I don't want to be covered. I want to know how I can not cover it. Thank you.

**Comment by fangxiaoyaner** [comment]
Hello, why does the report cover every time I request it? Interface returns slowly, mostly on the $writer - > process function?

**Comment by sebastianbergmann** [comment]
I do not understand what you are trying to ask or report, sorry.

**Comment by fangxiaoyaner** [comment]
The results of the second visit will cover the first. I don't want to be covered.

**Comment by sebastianbergmann** [comment]
What do you mean by "visit"?

**Comment by fangxiaoyaner** [comment]
i wanna Multiple use 【include_once("/xxx/prepend.php")】，but the result will cover the lats one.  how can i get the aggregation of multiple result not the final result?

**Comment by sebastianbergmann** [comment]
What is `prepend.php`?

**Comment by fangxiaoyaner** [comment]
![image](https://user-images.githubusercontent.com/51904095/59659489-e5731a00-91d8-11e9-8a9b-530d311dfb71.png)

like this

**Comment by sebastianbergmann** [comment]
Likely related to #765.
