### ISSUE TITLE
Tests in subdirectories are run, but are missing from the coverage report

### ISSUE THREAD

**Issue by Torniojaws** [sebastianbergmann/php-code-coverage#686]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 7.0.6
| PHP version               | 7.2.14
| Driver                    | Xdebug
| Xdebug version (if used)  | 2.7.2
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 7.4.3

When running the test suite, the tests in subdirectories are run correctly. However, they are missing from the coverage html report, which only shows tests in the root directory.

```
classes/
├ EmailsAPI/
│ └ EmailsAPI.php
└ Report.php
tests/
├ EmailsAPI/
│ └ EmailsAPITest.php
└ ReportTest.php
autoload.php
index.php
```
With phpunit.xml:
```
<?xml version="1.0"?>
<phpunit bootstrap="autoload.php">
  <testsuites>
    <testsuite name="Backend">
      <directory suffix="Test.php">./tests/*</directory>
    </testsuite>
  </testsuites>
  <logging>
    <log type="testdox-text" target="php://stdout"/>
  </logging>
  <filter>
    <whitelist>
      <directory suffix="Test.php">./tests/*API/</directory>
    </whitelist>
  </filter>
</phpunit>
```
I've also tried it without the `<filter>` element.

The test report shows both the root level test and the subdir test:

```
EmailsAPI
..... [x] Send on hold notification
 [x] Send on hold notification with empty template string
 [x] Send order on hold notification
 [x] Send order on hold notification with unknown template
 [x] Send order on hold notification with disabled notification

Report
. [x] Contains expected string
```

However, in the HTML report, I can only see the tests in the root. No entry for "EmailsAPI" exists, and no such directory is added to the `coverage/´directory structure.

**Comment by sebastianbergmann** [comment]
Your whitelist configuration is wrong. You do not whitelist the test code but the production code. What you want is likely:
```xml
<filter>
  <whitelist>
    <directory suffix=".php">classes</directory>
  </whitelist>
</filter>
```

**Comment by deyvisonrocha** [comment]
Q | A
-- | --
php-code-coverage version | 6.1.4
PHP version | 7.1.31
Driver | pcov
Pcov version | 1.0.6
Xdebug version (if used) | 0
Installation Method | Composer
Usage Method | PHPUnit
PHPUnit version (if used) | 7.5.13


Hi. I have the same problem.

See my phpunit.xml:

`<phpunit backupGlobals="false"
  backupStaticAttributes="false"
  bootstrap="vendor/autoload.php"
  colors="true"
  convertErrorsToExceptions="true"
  convertNoticesToExceptions="true"
  convertWarningsToExceptions="true"
  processIsolation="false"
  stopOnFailure="false">
<testsuites>
    ...
</testsuites>
<filter>
    <whitelist>
      <directory suffix=".php">./app</directory>
      <directory suffix=".php">./src</directory>
    </whitelist>
  </filter>
  <php>
    <server name="APP_ENV" value="testing"/>
    <server name="BCRYPT_ROUNDS" value="4"/>
    <server name="CACHE_DRIVER" value="array"/>
    <server name="MAIL_DRIVER" value="array"/>
    <server name="QUEUE_CONNECTION" value="sync"/>
    <server name="QUEUE_DRIVER" value="sync"/>
    <server name="SESSION_DRIVER" value="array"/>
  </php>
  <logging>
    <log type="coverage-clover" target="./report/coverage.xml"/>
    <log type="testdox-text" target="./report/log.txt"/>
    <log type="junit" target="./report/tests-junit.xml"/>
    <log type="coverage-html" target="./report" lowUpperBound="50" highLowerBound="80"/>
  </logging>
</phpunit>`

The folder './src' has coverage but the './app' doesn't has coverage. See the screenshot:

![image](https://user-images.githubusercontent.com/686067/62462299-75572e00-b75d-11e9-9831-c8aee11550bb.png)
