### ISSUE TITLE
Incorrect detection: line executed is marked as not executed

### ISSUE THREAD

**Issue by xthiago** [sebastianbergmann/php-code-coverage#687]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 7.0.6
| PHP version               | PHP 7.4.0alpha2 (cli) (built: Jul 12 2019 01:56:19) ( NTS )
| Driver                    | Xdebug
| Xdebug version | 2.8.0alpha1
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version | 8.2.5

When I was analyzing the code coverage I saw that `->verifyNow()` call below is incorrectly detected as not executed.

```php
public static function fromString(string $latitude, string $longitude) : self
    {
        Assert::lazy()
            ->that($latitude, 'latitude')->range(self::LATITUDE_RANGE['min'], self::LATITUDE_RANGE['max'])
            ->that($longitude, 'longitude')->range(self::LONGITUDE_RANGE['min'], self::LONGITUDE_RANGE['max'])
            ->verifyNow();

        return new self($latitude, $longitude);
    }
```

The report:

![image](https://user-images.githubusercontent.com/720151/61863128-680c8a80-aea5-11e9-8263-fea4152b8719.png)

It is detected correctly if I a change that the structure of statements to call everything in one line:

```php
    public static function fromString(string $latitude, string $longitude) : self
    {
        Assert::lazy()->that($latitude, 'latitude')->range(self::LATITUDE_RANGE['min'], self::LATITUDE_RANGE['max'])->that($longitude, 'longitude')->range(self::LONGITUDE_RANGE['min'], self::LONGITUDE_RANGE['max'])->verifyNow();

        return new self($latitude, $longitude);
    }
```
![image](https://user-images.githubusercontent.com/720151/61863467-0862af00-aea6-11e9-8b09-1bf5b7e20d42.png)

Or if I split the `verifyNow()` call to another line:

```php
public static function fromString(string $latitude, string $longitude) : self
    {
        $assertion = Assert::lazy()
            ->that($latitude, 'latitude')->range(self::LATITUDE_RANGE['min'], self::LATITUDE_RANGE['max'])
            ->that($longitude, 'longitude')->range(self::LONGITUDE_RANGE['min'], self::LONGITUDE_RANGE['max']);
        $assertion->verifyNow();

        return new self($latitude, $longitude);
    }
```
![image](https://user-images.githubusercontent.com/720151/61863607-51b2fe80-aea6-11e9-9aa6-17c51bb91daf.png)

**Comment by sebastianbergmann** [comment]
There can be many reasons why a specific line is not covered. Each of them is likely a different issue. In order to be able to reproduce *anything* and not get bogged down with details, you need to provide the following **in ONE new issue per case**.

That means:

- The exact versions of (this is what the template requires too, but more):
  - PHP
  - PHP Code Coverage
  - Xdebug
  - PHPUnit
- ```php -v``` output
- Either a ```.tar.gz``` archive or a GitHub repository with a reproduce case. With **one** file that shows the problem and **one** test case file (with the exception that sometimes, you might need **two** source files to show a problem.

This information should be filed as **one specific case per issue**.

CC @derickr

**Comment by xthiago** [comment]
@sebastianbergmann Here's the repository with the reproduce case: https://github.com/xthiago/php-code-coverage-with-incorrect-line-detection

**Comment by xthiago** [comment]
I have upgraded the Dockerfile of the repository to PHP 7.4.0beta1 and xdebug to 2.8.0beta1 and the problem still happening.

For curiosity, I created a [scenario version with php 7.3](https://github.com/xthiago/php-code-coverage-with-incorrect-line-detection/tree/php7.3) and I can confirm that in this version the line is detected correctly.

**Comment by krakjoe** [comment]
@xthiago just fyi, there is nothing that @sebastianbergmann can do, this is not a bug in this package but upstream in Xdebug, opening an issue on the Xdebug tracker is the only way forward.

**Comment by derickr** [comment]
If you do file an issue at https://bugs.xdebug.org, please only supply the file `Sample.php`. I have no use for Docker images and the like.

**Comment by xthiago** [comment]
I opened the issue on Xdebug side: https://bugs.xdebug.org/view.php?id=1691

Thank you!
