### ISSUE TITLE
Tests pass (code executes during test run) but code is not covered

### ISSUE THREAD

**Issue by dingo-d** [sebastianbergmann/php-code-coverage#691]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 6.1.4
| PHP version               | 7.3.7
| Driver                    | Xdebug
| Xdebug version (if used)  | 2.7.2
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 7.5.14

I'm running integration tests for WordPress plugin which can be set up using WP-CLI `wp scaffold plugin-tests` command. When writing tests, you extend the `WP_UnitTestCase` [class](https://github.com/WordPress/wordpress-develop/blob/10855438eaca4da1aa24616fdc5f90f5745a45e4/tests/phpunit/includes/phpunit7/testcase.php), which extends the `PHPUnit_Framework_TestCase`.

The MWE is here: https://github.com/dingo-d/test-plugin, alongside the required steps to reproduce the issue.

It's a simple plugin that registers three custom post types (CPT).

Now the problem I have is, that I wrote a test that will check if the custom post types are registered, the test will pass, but the code coverage is red, and the code that governs the registration of the custom post types gets run during the test run (tested by placing a `print_r` in the method for registering CPTs).

I'm a bit confused here. If the code is run an obviously passed through during the test run, shouldn't it be automatically covered without explicitly calling it in my tests (with `new My_Plugin\Custom_Post_Type\Documentation()` inside a test)?

**Comment by had1z** [comment]
I have the same problem with phpunit 8.4

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that does not involve Wordpress and shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by dingo-d** [comment]
> Please provide a minimal, self-contained, reproducing test case that **does not involve Wordpress** and shows the problem you are reporting.

But the issue I'm talking about is the **integration test**, which means I need WordPress in order to run the tests

The steps to reproduce the issue is to

```bash
git clone git@github.com:dingo-d/test-plugin.git
composer install
bash bin/install-wp-tests.sh wordpress_test root '' localhost latest
composer run-tests-cov
```

Which generates code coverage but doesn't cover passed code.

Not sure how to simplify the issue tbh 😕

**Comment by had1z** [comment]
> I have the same problem with phpunit 8.4
[SOLVED]
The problem was my configuration file.
