### ISSUE TITLE
phpunit --coverage-php very slow and out of memory

### ISSUE THREAD

**Issue by jesusslim** [sebastianbergmann/php-code-coverage#702]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 2.1
| PHP version               | 7.1
| Driver                    | Xdebug
| Xdebug version (if used)  | 2.7.2
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 4.8.21

Everytime i use coverage-php,phpunit will be very very slow,and finally out of memory,my memory_limit is 128M,it seems that CodeCoverage object has very big data,after phpunit,memery_usage is about 80M,and then crash when $coverage->getData in PHP_CodeCoverage_Report_PHP.Is there any way to speed up the coverage,and make CodeCoverage size smaller to use less memory?

**Comment by afbora** [comment]
My error output on Travis CI:

> [PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 12288 bytes) in /home/travis/build/afbora/test/vendor/phpunit/php-code-coverage/src/CodeCoverage.php on line 558]

**PHP** 7.1
**Xdebug** 2.7.2
**PHPUnit** 7.5.16
**PHPCodeCoverage** 6.1.4

**Comment by kubawerlos** [comment]
@jesusslim have you tried to use [PCOV](https://github.com/krakjoe/pcov) instead of Xdebug?
