### ISSUE TITLE
When using nested, chopped down function call, some lines as marked as uncovered

### ISSUE THREAD

**Issue by jfilla** [sebastianbergmann/php-code-coverage#711]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 7.0.10
| PHP version               | PHP 7.4.0
| Driver                    | Xdebug 
| Xdebug version (if used)  | v2.8.1
| Installation Method       | Composer
| Usage Method              | PHPUnit 
| PHPUnit version (if used) | 8.5.0

In following case there is one line, which is not marked as covered (it should be)
```php
        public static function fc(string $a): string
	{
		return self::nested(
			self::nested( //this line is marked as uncovered
				$a
			)
		);
	}

	private static function nested(string $a): string
	{
		return $a;
	}
```
however in following case all lines are marked as covered

```php
        public static function fc(string $a): string
	{
		return self::nested(
			self::nested($a) // this line is marked as covered
		);
	}
```
Coverage xml snippet

```xml
<file name="/var/www/flowgate/copy-general/app/CopyGeneral/Models/Example.php">
        <class name="Flowgate\CopyGeneral\Models\Example" namespace="Flowgate\CopyGeneral\Models">
          <metrics complexity="2" methods="2" coveredmethods="1" conditionals="0" coveredconditionals="0" statements="4" coveredstatements="3" elements="6" coveredelements="4"/>
        </class>
        <line num="12" type="method" name="fc" visibility="public" complexity="1" crap="1.04" count="1"/>
        <line num="14" type="stmt" count="1"/>
        <line num="15" type="stmt" count="0"/>
        <line num="16" type="stmt" count="1"/>
        <line num="21" type="method" name="nested" visibility="private" complexity="1" crap="1" count="1"/>
        <line num="23" type="stmt" count="1"/>
        <metrics loc="26" ncloc="26" classes="1" methods="2" coveredmethods="1" conditionals="0" coveredconditionals="0" statements="4" coveredstatements="3" elements="6" coveredelements="4"/>
      </file>
```

**Comment by sebastianbergmann** [comment]
There can be many reasons why a specific line is not covered. Each of them is likely a different issue. In order to be able to reproduce *anything* and not get bogged down with details, you need to provide the following **in ONE new issue per case**.

That means:

- The exact versions of (this is what the template requires too, but more):
  - PHP
  - PHP Code Coverage
  - Xdebug
  - PHPUnit
- ```php -v``` output
- Either a ```.tar.gz``` archive or a GitHub repository with a reproduce case. With **one** file that shows the problem and **one** test case file (with the exception that sometimes, you might need **two** source files to show a problem.

This information should be filed as **one specific case per issue**.

CC @derickr

**Comment by sebastianbergmann** [comment]
@jfilla Can you please whether using PCOV instead of Xdebug gives a different result? Thanks!

**Comment by derickr** [comment]
In this case, just the code was needed. With VLD, we see that line 7 (in my example) has an `INIT_STATIC_METHOD_CALL` that Xdebug doesn't overload yet:

```
  1 <?php
  2 class bar
  3 {
  4 public static function fc(string $a): string
  5     {
  6         return self::nested(
  7             self::nested( //this line is marked as uncovered
  8                 $a
  9             )
 10         );
 11     }
```
```
line     #* E I O op                           fetch          ext  return  operands
-------------------------------------------------------------------------------------
   4     0  E >   EXT_NOP                                                  
         1        RECV                                             !0      
   6     2        EXT_STMT                                                 
         3        INIT_STATIC_METHOD_CALL                                  'nested'
   7     4        INIT_STATIC_METHOD_CALL                                  'nested'
   8     5        SEND_VAR                                                 !0
```

**Comment by jfilla** [comment]
Thanks, it works with PCOV. Repository https://github.com/jfilla/php-code-coverage-issue-711. php -v output 
```PHP 7.4.0 (cli) (built: Nov 28 2019 07:26:50) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.0, Copyright (c), by Zend Technologies
    with Xdebug v2.8.1, Copyright (c) 2002-2019, by Derick Rethans
```

**Comment by derickr** [comment]
https://bugs.xdebug.org/view.php?id=1728
