### ISSUE TITLE
Test does not pass when collecting coverage. Problem with eager file inclusion?

### ISSUE THREAD

**Issue by bartvanhoutte** [sebastianbergmann/php-code-coverage#713]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 7.0.10
| PHP version               | 7.4.0
| Driver                    | Xdebug
| Xdebug version (if used)  | 2.9.0
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version | 8.5.0

I have an application that uses `goaop/framework` to log various messages. The framework registers an autoloader that uses the composer autoloader as a basis, but switches out specific classes for proxy classes. However, when running my test suite with code coverage enabled, the autoloader for these specific classes is not called and the test suite fails.

With coverage enabled the test suite fails:
```sh
/var/www # php -dxdebug.coverage_enable=1 /var/www/vendor/phpunit/phpunit/phpunit --coverage-clover /opt/phpstorm-coverage/project@phpunit_xml.xml --configuration /var/www/phpunit.xml --cache-result-file=/var/www/.phpunit.result.cache
PHPUnit 8.5.0 by Sebastian Bergmann and contributors.

..F.................                                              20 / 20 (100%)

Time: 6.66 seconds, Memory: 32.00 MB

There was 1 failure:

1) Foo\Bar\Aspect\LoggingAspectTest::testLogEvent
Failed asserting that false is true.

/var/www/tests/Aspect/LoggingAspectTest.php:69

FAILURES!
Tests: 20, Assertions: 61, Failures: 1.

Generating code coverage report in Clover XML format ... done [235 ms]
```
Without coverage enabled, the test suite passes:
```sh
/var/www # php -dxdebug.coverage_enable=1 /var/www/vendor/phpunit/phpunit/phpunit --configuration /var/www/phpunit.xml --cache-result-file=/var/www/.phpunit.result.cache
PHPUnit 8.5.0 by Sebastian Bergmann and contributors.

....................                                              20 / 20 (100%)

Time: 1.97 seconds, Memory: 32.00 MB

OK (20 tests, 61 assertions)
```
After some debugging, it seems like the culprit is line 953 in CodeCoverage.php:
```php
foreach ($this->filter->getWhitelist() as $file) {
    if ($this->filter->isFile($file)) {
        include_once $file;
    }
}
```
All classes in the whitelist are included, and as far as I can tell, this causes the autoloader to be skipped because the class can already be found. If I comment out line 955 `include_once $file;`, my test passes and the coverage report seems fine, the autoloader loads the proxy class and the test suite uses the correct class.

Any ideas on how to solve this?

**Comment by sebastianbergmann** [comment]
> Any ideas on how to solve this?

My advice would be to not rely on magic that hooks into the autoloader mechanism for performing sourcecode transformations on the fly.

That being said, try setting `processUncoveredFilesFromWhitelist="false"` in your PHPUnit XML configuration file in case you currently have `processUncoveredFilesFromWhitelist="true"` set there. See https://phpunit.readthedocs.io/en/8.5/code-coverage-analysis.html#whitelisting-files for details.

**Comment by bartvanhoutte** [comment]
Thanks @sebastianbergmann, that works.
