### ISSUE TITLE
theseer/tokenizer not tested on latest PHP 7.4

### ISSUE THREAD

**Issue by GrahamCampbell** [sebastianbergmann/php-code-coverage#716]
`theseer/tokenizer` is a dependency of this package, and we should make sure that all the dependencies are tested on a newish version PHP 7.4. I would send a PR to that package, but the author blocked my account at least a year ago, which is kinda odd, since I've never submitted a PR or issue to that repo before...

**Comment by theseer** [comment]
Fixed.

**Comment by GrahamCampbell** [comment]
👍 Happy new year, too!
