### ISSUE TITLE
Code Coverage results with floating point

### ISSUE THREAD

**Issue by kaktusas2598** [sebastianbergmann/php-code-coverage#718]
I have been using code coverage HTML reports to produce KPIs for our PHP app and one issue I have with provided metrics is lack of accuracy. For example you can see code coverage of lines in floating point number, but HTML report does not show you code coverage of files in %. If I produce code coverage using PHPStorm, for some reason, I do get this metric, but there is no way to see command PHPStorm is executing to produce these metrics.

I wanted to ask you if there is an option in PHPUnit to append code coverage of files in floating point number. I have been reading through PHPUnit documentation and can't find anything about this.

**Comment by kaktusas2598** [comment]
I am sorry for confusion, I will attach some screenshots and try to explain it better this time. So when I call php-unit with coverage-html option, this is code coverage report I see:

![codeCoverageReport](https://user-images.githubusercontent.com/4400363/71964572-c203d100-31f5-11ea-8ca3-a31628b239d4.png)

As you can see, it provides code coverage of lines as a floating point number. That I would like to see here also is code coverage of files in floating point number. I do get these stats when running code coverage from PHP Storm, but it only shows approximations:

![phpStormCoverageReport](https://user-images.githubusercontent.com/4400363/71964727-1c049680-31f6-11ea-8aa1-594ffda3a76d.png)

I am curious to know if it is possible to customize code coverage HTML report to get coverage of files or some other way to get these metrics from PHP Unit.

**Comment by sebastianbergmann** [comment]
I do not think that percentages for directories or files are useful enough to try to squeeze them into the report. You should only care about line level, method level, and class level.
