### ISSUE TITLE
Empty coverage, 0% summary

### ISSUE THREAD

**Issue by jeff1326** [sebastianbergmann/php-code-coverage#729]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 6.1.4
| PHP version               | 7.2.27-6+ubuntu19.10.1+deb.sury.org+1 or 7.3.14-6+ubuntu19.10.1+deb.sury.org+1
| Driver                    | PCOV 1.0.6
| Xdebug version  | N/A
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version | 8.5.0, 8.5.2 or 9.0.0 with composer

With a base phpunit.xml with a whitelist like this
```
        <whitelist processUncoveredFilesFromWhitelist="true">
            <directory suffix=".php">./modules</directory>
            <exclude>
                <directory>modules/*/*/routes</directory>
                <directory>modules/*/*/Database</directory>
                <directory>modules/*/*/Tests/Fixtures</directory>
                <directory>modules/*/*/resources/views</directory>
            </exclude>
        </whitelist>
```

I get this result
```
Code Coverage Report:     
  2020-02-12 13:07:14     
                          
 Summary:                 
  Classes:  0.00% (0/259) 
  Methods:  0.00% (0/721) 
  Lines:    0.00% (0/5700)
```

If i add `<directory suffix=".php">./app</directory>` in whitelist, i get some result that is only in app folder
```
Code Coverage Report:       
  2020-02-12 13:33:05       
                            
 Summary:                   
  Classes:  2.59% (6/232)   
  Methods:  2.99% (22/736)  
  Lines:    2.06% (118/5732)
```

I expect at least 1 lines tested in modules folders...
And i get the same behavior with --coverage-html

I found something similar here : https://github.com/krakjoe/pcov/issues/42
The guy use php-code-coverage 7.0.10 and phpunit/phpunit 8.5.0 via composer.

**Comment by sebastianbergmann** [comment]
`--coverage-text` is useless, please use (screenshots from) the HTML code coverage report to show what is wrong.

**Comment by jeff1326** [comment]
![image](https://user-images.githubusercontent.com/12941529/74374033-a1f29f00-4dab-11ea-97c7-20dd47b77038.png)

**Comment by jeff1326** [comment]
Maybe this is what you wanted :

![image](https://user-images.githubusercontent.com/12941529/74374374-44128700-4dac-11ea-933c-31c7e9f8b13d.png)

**Comment by jeff1326** [comment]
A work-around has been found here : https://github.com/krakjoe/pcov/issues/42
