### ISSUE TITLE
Confusing footer in the HTML report

### ISSUE THREAD

**Issue by yguedidi** [sebastianbergmann/php-code-coverage#731]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 7.0.10
| PHP version               | 7.3.14
| Driver                    | Xdebug and PCOV
| Xdebug version  | 2.9.2
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 8.5.2

![image](https://user-images.githubusercontent.com/1480128/74675124-2c277280-51b3-11ea-8d68-7d1e4700c787.png)

I have both XDebug and PCOV installed, but as you can see the HTML report footer shows them both.
According to the code it seems to display the runtime.

Should it show the code coverage driver used instead?

**Comment by sebastianbergmann** [comment]
I think it should show the code coverage driver used instead.
