### ISSUE TITLE
Feature request: LCOV report

### ISSUE THREAD

**Issue by teohhanhui** [sebastianbergmann/php-code-coverage#735]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | N/A
| PHP version               | N/A
| Driver                    | N/A
| Xdebug version (if used)  | N/A
| Installation Method       | N/A
| Usage Method              | N/A
| PHPUnit version (if used) | N/A

For example, it'd be really useful for https://github.com/coverallsapp/github-action which only supports an LCOV file.

**Comment by sebastianbergmann** [comment]
I do not need this and will not work on this. I will, of course, consider a pull request that implements this.

**Comment by sebastianbergmann** [comment]
https://github.com/php-coveralls/php-coveralls/ does not look abandoned to me, I see regular commits from @jrfnl and @keradus, for instance.

I am inclined to reject (sorry for the strong word) https://github.com/sebastianbergmann/php-code-coverage/pull/869 and https://github.com/sebastianbergmann/phpunit/pull/4787 because it seems that LCOV can be generated from Clover XML.

**Comment by mlocati** [comment]
> https://github.com/php-coveralls/php-coveralls/ does not look abandoned to me

When I wrote that comment, the repo was very silent (no commits for almost an year).

I'll take a look at the updates of it.

**Comment by jrfnl** [comment]
As a frequent user (and occasional contributor) of `php-coveralls`, I can only say that a PHPUnit native format is always preferable as it would eliminate the need for another external dependency, including the need for switching PHP versions during test jobs (needed if the minimum supported PHP version of a project is lower than that of `php-coveralls`).

Having said that, as the format has not been included with PHPUnit so far and the first version in which it _would_ be included would likely be 10.0.0 (?) with a PHP 8.1 minimum, it would still be quite a a while before projects which still support older PHP versions would benefit from a PHPUnit native version.

`php-coveralls` works well enough in the mean time.

**Comment by sebastianbergmann** [comment]
> a PHPUnit native format is always preferable as it would eliminate the need for another external dependency

I understand that. However, I am reluctant to add support for new formats as I may end up having to maintain them.

> would likely be 10.0.0 (?) with a PHP 8.1 minimum

It would definitely be 10.0.0.

**Comment by jrfnl** [comment]
> I am reluctant to add support for new formats as I may end up having to maintain them.

@sebastianbergmann I totally understand. Respect.

**Comment by sebastianbergmann** [comment]
Thank you for your contribution. I appreciate the time you invested in preparing this pull request. However, I have decided not to merge it.
