### ISSUE TITLE
How to cover multiple directories?

### ISSUE THREAD

**Issue by HenkPoley** [sebastianbergmann/php-code-coverage#741]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 8.0.1
| PHP version               | 7.3.17 (and 7.4.5, but same problem)
| Driver                    | pcov
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 9.1.4

I'd like to have code coverage in PhpStorm, on a Laravel 6.x project, on _multiple_ directories.

This is sort of a combination of these closed tickets that _seems_ to have been closed unsatisfactory:
* https://github.com/sebastianbergmann/phpunit/issues/3322
* https://github.com/sebastianbergmann/phpunit/issues/3100#issuecomment-383464973

It shows there are 2 boolean toggles that are supposed to influence what is included in the report. `addUncoveredFilesFromWhitelist` (default: true) and `processUncoveredFilesFromWhitelist` (default: false). As an example:

```
        <whitelist
                addUncoveredFilesFromWhitelist="true"
                processUncoveredFilesFromWhitelist="true">
            <directory suffix=".php">./app</directory>
            <directory suffix=".php">./BrandName</directory>
        </whitelist>
```

I have toggle them in all the 4 possible states. And `./BrandName/` is never included. I can literally put a `dump("hello");` in one of the "0% covered" functions in that directory, and phpunit will keep greeting me over and over. Inside PhpStorm it's shown as 0% covered.

There is a slightly open-ended / vague remark on one ticket:

> because you likely include files that not only contain class/interface/trait declarations

I've tried coding the whole directory structure inside `./BrandName` directory so I can individually toggle them on or off (maybe all of them disappear if 1 has a problem). But it didn't do anything. So either all of these directories contain "not class/interface/trait declarations", or something else is happening.

I've also tried just `<directory suffix=".php">./</directory>` and then `<exclude>` a whole bunch of things. It seems to increase the 'boot time' of phpunit a lot, and it still shows the coverage of the extra directory as 0%, and `./app` as some coverage, it additionally also notes the routes that I'm using as 0% covered.

How do I debug this?

Is it in, pcov, phpunit, this package, phpstorm, anything else. Where/how do I start?

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry.

**Comment by HenkPoley** [comment]
Is there a discussion or support forum for phpunit ?

**Comment by HenkPoley** [comment]
As you may or may not be interested in: The issue is in the interfacing between `php-code-coverage` and `pcov`. They both have their own disagreeing opinion on directory filtering.

**Comment by HenkPoley** [comment]
It would be nice if PhpUnit warned that none of the set up directories are covered by the installed/configured pcov.

**Comment by iwasherefirst2** [comment]
I encountered a similar issue, which I discussed [here](https://stackoverflow.com/questions/79222614/why-does-code-coverage-for-custom-modules-fail-in-laravel/79232251#79232251). After some investigation, I discovered that the problem could be resolved by disabling PCOV while generating the code coverage report. This allowed the coverage tool to handle multiple root directories correctly.
