### ISSUE TITLE
phpunit multiline built in php functions require escaping

### ISSUE THREAD

**Issue by MattNunnBud** [sebastianbergmann/php-code-coverage#743]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.1.4
| PHP version         | PHP 7.4.4
| Installation Method | Composer

#### Summary
Php built in functions on new lines require name spacing otherwise they are not recognised as being covered.

#### Current behavior
```
 array_merge( <--######### not counted as covered
                    ["a","b"],
                    $object->asArrayMethod()
);
```

```
 \array_merge( <--######### IS covered
                    ["a","b"],
                    $object->asArrayMethod()
);
```

```
 array_merge(["a","b"], $object->asArrayMethod()); <--######### IS covered
```
#### How to reproduce

see examples above

#### Expected behavior

IMHO phpunit should not require php fuctions to be namespace escaped

**Comment by sebastianbergmann** [comment]
There can be many reasons why a specific line is not covered. Each of them is likely a different issue. In order to be able to reproduce *anything* and not get bogged down with details, you need to provide the following **in ONE new issue per case**.

That means:

- The exact versions of (this is what the template requires too, but more):
  - PHP
  - PHP Code Coverage
  - PCOV or Xdebug
  - PHPUnit
- ```php -v``` output
- Either a ```.tar.gz``` archive or a GitHub repository with a reproduce case. With **one** file that shows the problem and **one** test case file (with the exception that sometimes, you might need **two** source files to show a problem.

This information should be filed as **one specific case per issue**.

**Comment by MattNunnBud** [comment]
@sebastianbergmann I will provide a sample of code where i have been able to reproduce the issue shortly, it appears to be when you do a php method when providing data to a constructor.
Would you like it attached to this issue description/comment? or somewhere else?

**Comment by MattNunnBud** [comment]
[phpunit-bug-743.zip](https://github.com/sebastianbergmann/php-code-coverage/files/4609650/phpunit-bug-743.zip)

```
PHP 7.4.5 (cli) (built: Apr 19 2020 07:36:30) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.5, Copyright (c), by Zend Technologies
    with Xdebug v2.9.3, Copyright (c) 2002-2020, by Derick Rethans
```

everything else is in the lock file in the above zip

**Comment by MattNunnBud** [comment]
Sorry to bother you, but is there any update on this? even a "i'm very busy and will get round to it in due time" will be fine

**Comment by sebastianbergmann** [comment]
I did not have time yet to look into this. All I can see is that in all the code I regularly work on, I have never experienced the bug you are describing. I may be wrong, but this makes me think that it is unlikely that there is a bug in php-code-coverage or Xdebug here, but something "special" in the environment where you experience this problem.

Are you still experiencing this problem with the latest versions of Xdebug, PHPUnit, and php-code-coverage?

**Comment by MattNunnBud** [comment]
As far as I'm aware, yes. I'll get back to you today with more information and an updated zip file.

**Comment by alexualbu** [comment]
hi @sebastianbergmann, @MattNunnBud 

I experience the same issue when migrating between the versions below. It appears for `json_encode`, `sprintf` and `array_in`
Not sure if there has been no progress, but please let me know if you'd like a sample piece of code.

Thanks


`php-code-coverage 5.3.2 using PHP 7.3.7-1+ubuntu18.04.1+deb.sury.org+1 with Xdebug 2.7.1 and PHPUnit 6.5.14`

` php-code-coverage 8.0.2 using PHP 7.4.5 with Xdebug 2.9.3 and PHPUnit 9.2.5 `

**Comment by MattNunnBud** [comment]
Just did a composer update to get the latest version and it seems to be fixed with the following combination: 
`php-code-coverage 8.0.2 using PHP 7.4.8 with Xdebug 2.9.6 and PHPUnit 9.2.6`

i am no longer receiving the errors on my test code.

**Comment by alexualbu** [comment]
thanks @MattNunnBud !

I can confirm, and, just for the record, the culprit seems to be `Xdebug 2.9.3` - works for me too with 2.9.6
