### ISSUE TITLE
expectException works but test still does not pass, code coverage still not 100%

### ISSUE THREAD

**Issue by pavrip** [sebastianbergmann/php-code-coverage#744]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | x.y.z
| PHP version               | x.y.z
| Driver                    | Xdebug / PHPDBG
| Xdebug version (if used)  | x.y.z
| Installation Method       | Composer / PHPUnit PHAR
| Usage Method              | PHPUnit / other
| PHPUnit version (if used) | x.y.z

I have just started trying out code coverage with my unit test.
I have a method which is supposed to throw an exception if a key is not found in an array.

I am trying the expectException() method, which works when I expect it to fail and it fails, but it does not pass when the exception is actually thrown. As in the exception simply gets thrown and there is no pass or fail

In coverage it says I have only covered 28% of the method and the part where the exception should be thrown is covered in red

Here is the code example:

//Query::class

/**
* @param string $param: The key for a matching param in the params array
* @throws QueryException
* @return array $this->params[$param]
*/
public function get_param(string $param):IQueryParameter
{
	try {
	     if (!array_key_exists($param, $this->params)) {
		   throw new QueryException(
			"Statement Param: $param not found!",
		);
	     }
	    return $this->params[$param];

	} catch (QueryException $e) {
		$e->display_exception();
	}
}

//test method:
/**
* @expectedException QueryException
*/
public function test_get_param_throws_query_exception($value='')
{
	$query = new Query();
	$this->expectException(QueryException::class);
	$param = $query->get_param('mother');
}
Result shows the test does not pass:
![Screenshot 2020-05-12 at 19 20 39](https://user-images.githubusercontent.com/45601322/81730583-ab140a80-9485-11ea-86cf-49407c6416b4.png)

In code coverage:
![Screenshot 2020-05-12 at 19 21 25](https://user-images.githubusercontent.com/45601322/81730664-c7b04280-9485-11ea-91de-22f2b98d4908.png)

![Screenshot 2020-05-12 at 19 21 52](https://user-images.githubusercontent.com/45601322/81730710-d7c82200-9485-11ea-8ef6-88e27ec9d23e.png)

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by pavrip** [comment]
I created a small project which reproduces the main issue which throws exception, test still fails , but I cant get code coverage to work so I cannot see if Line coverage is 100%.

I am really sorry I have not done this before or worked properly with GitHub, so I had to research what producing a reproducible problem means,

I created a small project with autoload and phpunit and compressed it and attached it to this comment, I am not sure If I should be uploading a repository?

Please let me know what you would like me to do

[exception-test.zip](https://github.com/sebastianbergmann/php-code-coverage/files/4620498/exception-test.zip)

**Comment by pavrip** [comment]
Please ignore, I got the code coverage to work, 
Test still fails when exception is thrown, but the code coverage is 100% this time

The problem is that when I call the expectException() method, I expect the test to pass, should it not pass?

And more importantly why is the code coverage not showing that I have covered those lines of code in my real project

I have attached the zip of the small project here as I did not know how else to upload not really used this before
[exception-test.zip](https://github.com/sebastianbergmann/php-code-coverage/files/4620542/exception-test.zip)
,
Please accept my apologies
