### ISSUE TITLE
Run tests for each driver

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/php-code-coverage#769]
This library supports

* `phpdbg`
* `php` with `pcov` extension
* `php` with `xdebug` extension version 2
* `php` with `xdebug` extension version 3

In our GitHub Actions CI pipeline, however, we only test with PCOV.

**Comment by sebastianbergmann** [comment]
Maybe @localheinz likes to work on this? :-)

**Comment by localheinz** [comment]
Will take a look this evening!

**Comment by sebastianbergmann** [comment]
@shivammathur Hi! Does `shivammathur/setup-php` have nightly builds of Xdebug 3?

**Comment by shivammathur** [comment]
@sebastianbergmann Yes, for `ubuntu`, Till next release specify `xdebug` in extensions without coverage input and it will enable `Xdebug 3.0.0-dev`. Here is a [test workflow](https://github.com/shivammathur/test-setup-php/actions/runs/137086008/workflow).

**Comment by sebastianbergmann** [comment]
@shivammathur Thanks!

**Comment by localheinz** [comment]
Thank you, @shivammathur!
