### ISSUE TITLE
CodeUnitFindingVisitor cannot process anonymous classes

### ISSUE THREAD

**Issue by xepozz** [sebastianbergmann/php-code-coverage#786]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | master
| PHP version               | 7.4.8
| Driver                    | Xdebug 
| Xdebug version (if used)  | 2.9.6
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 9.2

I've researched  fails while code coverage and got some information.

I found four bugs: [one](https://github.com/sebastianbergmann/php-code-coverage/blob/master/src/StaticAnalysis/CodeUnitFindingVisitor.php#L184), [two](https://github.com/sebastianbergmann/php-code-coverage/blob/master/src/StaticAnalysis/CodeUnitFindingVisitor.php#L185), [three](https://github.com/sebastianbergmann/php-code-coverage/blob/master/src/StaticAnalysis/CodeUnitFindingVisitor.php#L227) and [four](https://github.com/sebastianbergmann/php-code-coverage/blob/master/src/StaticAnalysis/CodeUnitFindingVisitor.php#L228)

It fails because we have an [inlined anonymous class](https://github.com/yiisoft/yii-web/blob/master/src/MiddlewareDispatcher.php#L97) and others.

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by sebastianbergmann** [comment]
I am also confused by the fact that [you write you use PHPUnit 9.2](https://github.com/sebastianbergmann/php-code-coverage/issues/786#issue-669026272) and then [provide a patch](https://github.com/xepozz/php-code-coverage/commit/6a60f142eb04ef20915be216edec1d9bc17a587e) for the unreleased PHPUnit 9.3.

**Comment by sebastianbergmann** [comment]
Nevermind, I was able to reproduce the issue.
