### ISSUE TITLE
PHPDBG + php-code-coverage 9.0.0: Interface methods marked as uncovered

### ISSUE THREAD

**Issue by zlodes** [sebastianbergmann/php-code-coverage#788]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 9.0.0
| PHP version               | 7.4.8
| Driver                    | PHPDBG
| Xdebug version (if used)  | 2.9.6
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 9.3.2

After update phpunit (9.2.6 -> 9.3.2) I saw that coverage has been decreased.
I found uncovered interfaces methods in the report, but there are classes with covered implemented methods.

But with XDebug it works fine.

![image](https://user-images.githubusercontent.com/1114387/89638404-6ba66000-d8b4-11ea-8ddf-6bd4c37a518d.png)

**Comment by sebastianbergmann** [comment]
I am sorry to say this, but PHPDBG is not a priority for me anymore and support for it will likely be removed in the future. I will not investigate this issue, but -- of course -- will consider a pull request that fixes this.

**Comment by sebastianbergmann** [comment]
Maybe @dvdoug has an idea what might be going on here.

**Comment by dvdoug** [comment]
@zlodes can you please attach a minimal testcase that reproduces this? I'm happy to take a look but I've just run a quick test on a random codebase and PHPDBG was reporting all interfaces as being 100% non-executable which is what I would expect.

**Comment by sebastianbergmann** [comment]
No feedback, closing.
