### ISSUE TITLE
Merge coverage is not working correctly

### ISSUE THREAD

**Issue by pvsaintpe** [sebastianbergmann/php-code-coverage#792]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | ^7
| PHP version               | 7.3.*
| Driver                    | PCOV (Krakjoe)
| Xdebug version (if used)  | no
| PHPUnit version (if used) | ^8.5

![image](https://user-images.githubusercontent.com/16900171/89959349-e2d94c80-dc44-11ea-9749-504e6550ed9d.png)

**Comment by pvsaintpe** [comment]
![image](https://user-images.githubusercontent.com/16900171/89960871-cc34f480-dc48-11ea-8075-c4706a0344c9.png)

**Comment by sebastianbergmann** [comment]
Please avoid posting screenshots.

> ![image](https://user-images.githubusercontent.com/16900171/89959349-e2d94c80-dc44-11ea-9749-504e6550ed9d.png)

The output from phpcov, which by the way is out of scope for this issue tracker, reads:
```
Required argument for option "--text" is missing
```
While cleaning up `phpcov`, I decided to not fall back to `php://stdout` anymore when `--text` is used without an argument.

> ![image](https://user-images.githubusercontent.com/16900171/89959349-e2d94c80-dc44-11ea-9749-504e6550ed9d.png)

The error message tells you that the code in `group_1.cov` is not compatible with php-code-coverage 9 and phpcov 8. 

You wrote that you use

> php-code-coverage version 	^7
> PHPUnit version (if used) 	^8.5

This is your problem. You must use a version of phpcov < 9 if you have code coverage data from php-code-coverage 7.

**Comment by pvsaintpe** [comment]
Thanks.
