### ISSUE TITLE
Custom HTMP report generation fails

### ISSUE THREAD

**Issue by dartemiev** [sebastianbergmann/php-code-coverage#796]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 9.1.4
| PHP version               | 7.4.8
| Driver                    | PCOV
| Xdebug version (if used)  | -
| Installation Method       | Composer
| Usage Method              | Custom
| PHPUnit version (if used) | 9.3.7

During execution of functional tests (by using Codeception) - collected data from PCOV driver is stored in custom files 
by 
```
...
$data = $this->getDriver()->stop()->lineCoverage();
file_put_contents(
    '/tmp/coverage/files/' . $testName . '.php',
    sprintf("<?php\n return %s;\n", var_export($data, true))
);
```

After migration to the latest versions of PhpUnit and Code Coverage libraries there is change in HTML report generation where drive is mandatory param in constructor and by trying 
```
$coverage = new CodeCoverage(new NullDriver(), CoverageFilter::createFilter());
foreach ($files as $file) {
    $coverageData = include($file);
    $coverageData = RawCodeCoverageData::fromXdebugWithoutPathCoverage($coverageData);
    $coverage->append($coverageData, basename($file));
}

$htmlReport = new Facade();
$htmlReport->process($coverage, '/tmp/coverage/report');
```

But it gives next errors
```
 [ FAILURE ] Call to undefined method PhpParser\Node\Stmt\Declare_::getComments()
 [ FAILURE ] #0 /www/onyx/backend/tests/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(159): SebastianBergmann\LinesOfCode\LineCountingVisitor->enterNode(Object(PhpParser\Node\Stmt\Declare_))
#1 /www/onyx/backend/tests/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85): PhpParser\NodeTraverser->traverseArray(Array)
#2 /www/onyx/backend/vendor/phpunit/php-code-coverage/src/StaticAnalysis/ParsingCoveredFileAnalyser.php(142): PhpParser\NodeTraverser->traverse(Array)
#3 /www/onyx/backend/vendor/phpunit/php-code-coverage/src/StaticAnalysis/ParsingCoveredFileAnalyser.php(103): SebastianBergmann\CodeCoverage\StaticAnalysis\ParsingCoveredFileAnalyser->analyse('/www/onyx/backe...')
#4 /www/onyx/backend/vendor/phpunit/php-code-coverage/src/CodeCoverage.php(501): SebastianBergmann\CodeCoverage\StaticAnalysis\ParsingCoveredFileAnalyser->ignoredLinesFor('/www/onyx/backe...')
#5 /www/onyx/backend/vendor/phpunit/php-code-coverage/src/CodeCoverage.php(268): SebastianBergmann\CodeCoverage\CodeCoverage->applyIgnoredLinesFilter(Object(SebastianBergmann\CodeCoverage\RawCodeCoverageData))
#6 /www/onyx/backend/vendor/phpunit/php-code-coverage/src/CodeCoverage.php(238): SebastianBergmann\CodeCoverage\CodeCoverage->append(Object(SebastianBergmann\CodeCoverage\RawCodeCoverageData), 'XenForo2Test', true, Array, Array)
```

If it's important - by using PHP 7.4.x - code contains many typed properties like 
```
private CustomObjectType $ptoperty;
```

without comments above

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by dartemiev** [comment]
I hope https://github.com/dartemiev/coverage_issue will help to reproduce it

Steps
```
mkdir -p /tmp/coverage/files/
php -dpcov.enabled=1 -dpcov.directory=<full_path_to_root> codecept run unit unit/Coverage/ClassCTest.php -v
ls /tmp/coverage/files ----> should show ClassCTest
php ./scripts/generate_report.php
```

**Comment by sebastianbergmann** [comment]
It appears that you want to process, for instance merge, code coverage results. Please use the provided ways for that instead of custom solutions. Use `SebastianBergmann\CodeCoverage\Report\PHP` for exporting `SebastianBergmann\CodeCoverage\CodeCoverage` objects as PHP code. Then use `SebastianBergmann\CodeCoverage\CodeCoverage::merge()`, for instance, to merge `SebastianBergmann\CodeCoverage\CodeCoverage` objects, for instance.

You might also want to have a look at [PHPCOV](https://github.com/sebastianbergmann/phpcov), a tool that, among other things, implements merging of code coverage stored in files created by `SebastianBergmann\CodeCoverage\Report\PHP`.

**Comment by dartemiev** [comment]
I have updated repo by suggestion, but now by running 
```
php -dpcov.enabled=1 -dpcov.directory=<full_path_to_root> codecept run unit unit/Coverage/ClassCTest.php -v
```

I received
```
1) ClassCTest: Get name
 Test  unit/Coverage/ClassCTest.php:testGetName

  [Error] Call to undefined method PhpParser\Node\Stmt\Declare_::getComments()

#1  /user/project/vendor/sebastian/lines-of-code/src/LineCountingVisitor.php:47
#2  /user/project/tests/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:159
#3  /user/project/tests/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:85
#4  /user/project/tests/unit/Coverage/ClassCTest.php:25
```
