### ISSUE TITLE
Uncovered new line at end of file

### ISSUE THREAD

**Issue by davidgrayston** [sebastianbergmann/php-code-coverage#799]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 9.1.4
| PHP version               | 7.4
| Driver                    | Xdebug
| Xdebug version | 2.9.6
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version | 9.3.7

Since upgrading from PHPUnit `9.2`, new lines at the end of files are being reported as uncovered in the XML report, e.g.
```
<line num="32" type="stmt" count="0"/>
```

It seems to be caused by the removal of this workaround (as reinstating it fixes the clover report): https://github.com/sebastianbergmann/php-code-coverage/commit/d9c9b7b62bbfdd2c503f96fc3af831b8a8cba191

The report is being consumed by SonarCloud - should the last line of files be ignored regardless of the uploaded XML report? If that's the case, I can raise an issue with SonarCloud.

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by sebastianbergmann** [comment]
> Should a newline at the end of the file be considered a source code line or not? Does the file have 13 or 14 lines?

How about considering empty lines to be not executable in general?

**Comment by remorhaz** [comment]
Seems that this bug is reintroduced in 9.1.7 - I look into `--coverage-clover` report and see uncovered EOF strings again (same picture occured before 9.1.6).

**Comment by sebastianbergmann** [comment]
Of course, the whole point of 9.1.7 was to revert this (so that it can be properly fixed later).
