### ISSUE TITLE
HTML CodeCoverage doesn't sort files/dirs anymore

### ISSUE THREAD

**Issue by Slamdunk** [sebastianbergmann/php-code-coverage#803]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 9.1.5
| PHP version               | 7.4.9
| Driver                    | PCOV
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 9.3.8

| Until 9.1.4 | 9.1.5 |
| - | - |
| ![image](https://user-images.githubusercontent.com/152236/91527847-d4f31f00-e906-11ea-88f7-f859f21ce3b0.png) | ![image](https://user-images.githubusercontent.com/152236/91527888-ec320c80-e906-11ea-8566-d9d12ab7bc7d.png) |

**Comment by sebastianbergmann** [comment]
There is no obvious change in https://github.com/sebastianbergmann/php-code-coverage/compare/9.1.4...9.1.5 that would explain this. TBH, I do not remember that there ever was an explicit sorting in place for this.

**Comment by sebastianbergmann** [comment]
@dvdoug Could this be related to #801 and 7e9109986c772257f839230e3a869bb6a9638bf0, too, somehow?

**Comment by dvdoug** [comment]
If the files in the filter list are naturally alphabetical from the directory iteration, then it makes sense that the covered files list may have been previously been initialised as an alphabetical list due to preloading.
