### ISSUE TITLE
T_FN constant is used on PHP 7.3 where it is not available

### ISSUE THREAD

**Issue by dvdoug** [sebastianbergmann/php-code-coverage#811]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 9.1.10
| PHP version               | 7.3.22
| Driver                    | PCOV
| Xdebug version (if used)  | N/A
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 9.3.10

T_FN on PHP 7.3 results in an undefined constant warning. Similar to #808 I assume. The CI run that shows the error is here: https://github.com/dvdoug/behat-code-coverage/runs/1134780400

Weirdly, the error is only shown when running under PCOV on CI, although I can reproduce locally when using Xdebug too.

```
Generating code coverage report in HTML format ... 
Fatal error: Uncaught Error: Undefined constant 'T_FN' in /code/vendor/phpunit/php-code-coverage/src/Report/Html/Renderer/File.php:1094
Stack trace:
#0 /code/vendor/phpunit/php-code-coverage/src/Report/Html/Renderer/File.php(1052): SebastianBergmann\CodeCoverage\Report\Html\File::keywordTokens()
#1 /code/vendor/phpunit/php-code-coverage/src/Report/Html/Renderer/File.php(938): SebastianBergmann\CodeCoverage\Report\Html\File->isKeyword(379)
#2 /code/vendor/phpunit/php-code-coverage/src/Report/Html/Renderer/File.php(418): SebastianBergmann\CodeCoverage\Report\Html\File->loadFile('/code/src/Contr...')
#3 /code/vendor/phpunit/php-code-coverage/src/Report/Html/Renderer/File.php(132): SebastianBergmann\CodeCoverage\Report\Html\File->renderSourceWithLineCoverage(Object(SebastianBergmann\CodeCoverage\Node\File))
#4 /code/vendor/phpunit/php-code-coverage/src/Report/Html/Facade.php(103): SebastianBergmann\CodeCoverage\Report\Html\File->render(Object(SebastianBergmann\CodeCoverage\Node\File), '/code/build/cov...')
#5 /code/vendor/php in /code/vendor/phpunit/phpunit/src/TextUI/Command.php on line 103
```

**Comment by dvdoug** [comment]
I cannot reproduce this on php-code-coverage's own test suite, only when using it as a consuming application.

I have a hypothesis that it's to do with `$parser = (new ParserFactory)->create(ParserFactory::PREFER_PHP7)` in `sebastian/lines-of-code` and `sebastian/complexity`. Although this library was changed to use non-emulative lexing, those 2 sub-libraries are still using it and I think might be acting as an accidental compatibility layer in some (but not) circumstances depending on the order things are executed in.

**Comment by dvdoug** [comment]
On further debugging, I reliably see the error on my own project when using `<coverage cacheDirectory="...">`. Removing the cache makes the error disappear.

Therefore, I think it's safe to say that it's parsing (at all) that is triggering the compatibility layer and allowing T_FN to work on PHP7.3, and was previously allowing T_MATCH to work on 7.3/7.4. When using the cache, no parsing is done and the compat layer is not loaded resulting in the undefined constant errors appearing.

That's why it only triggered on the pcov testing on my test suite - the pcov test there is part of the same build and runs after the Xdebug test...using the cache.

**Comment by sebastianbergmann** [comment]
> I have a hypothesis that it's to do with `$parser = (new ParserFactory)->create(ParserFactory::PREFER_PHP7)` in `sebastian/lines-of-code` and `sebastian/complexity`. 

This library (php-code-coverage) only uses the actual visitor objects, `SebastianBergmann\Complexity\ComplexityCalculatingVisitor` and `SebastianBergmann\LinesOfCode\LineCountingVisitor`, from the dependencies you mention. The `$parser = (new ParserFactory)->create(ParserFactory::PREFER_PHP7);` code in `SebastianBergmann\Complexity\Calculator` and `SebastianBergmann\LinesOfCode\Counter` is not used. PHP-Parser is therefore only used with non-emulative lexing.

**Comment by sebastianbergmann** [comment]
As of ebce86199dd58ccf8e0e3de01497846435ad1adb, the `T_FN` constant is no longer used on PHP 7.3. And while this change solves the issue at hand, I would like to understand what is going on here with regard to the static analysis cache, etc.

**Comment by sebastianbergmann** [comment]
Ah, of course: even when non-emulative lexing is used, PHP-Parser [conditionally defines](https://github.com/nikic/PHP-Parser/blob/v4.9.1/lib/PhpParser/Lexer.php#L407) `T_FN` and `T_MATCH`.

See https://github.com/sebastianbergmann/php-code-coverage/issues/798#issuecomment-677244883 and https://github.com/nikic/PHP-Parser/issues/701#issue-682556448.

**Comment by dvdoug** [comment]
Thanks
