### ISSUE TITLE
php-parse error. not compatible version.

### ISSUE THREAD

**Issue by iamrekas** [sebastianbergmann/php-code-coverage#813]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.3.10
| PHP version         | 7.4.9
| Installation Method | Composer

#### Summary

PHP-Parser error. Is not compatible. Maybe it's has error inside self package.

Workaround downgrade "nikic/php-parse" to 4.9.1

#### Showing error:

SebastianBergmann\CodeCoverage\ParserException: Cannot parse /workspace/SomeFile.php: Syntax error, unexpected T_ATTRIBUTE on line 3

/workspace/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php:315
/workspace/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php:158
/workspace/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php:51
/workspace/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php:32

The file:
```
1: <?php
2: 
3: namespace Some\Name\Space;
4: 
```

**Comment by iamrekas** [comment]
I was not able after update using PHPUnit cause i getting this error. so i investigate what's wrong. then try downgrade packages it's working. so i am reporting failure.

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by iamrekas** [comment]
Just you need update to latest phpunit without custom installed "nikic/php-parse" package and try run the phpunit tests... 
(i don't remmeber, cause a lot of options i was tryed this all day, so maybe you need to try with and without --coverage-text flag)

i am thinking about php-parse has bug in latest version.

**Comment by sebastianbergmann** [comment]
I cannot reproduce this in any of my projects, with and without code coverage reporting.

**Comment by iamrekas** [comment]
Tryed now remove custom installed "nikic/php-parse" package and it's upgrade as phpunit required to 4.9.10, tryed phpunit --coverage-text file.php have got same issue. so error not have gone. as downgrade to smae version as told above, working as normal. 

i am telling cuz need limit version of nikic/php-parse while them doesn't resolve this error.

P.S. i have got some errors about serialize then using the latest version of php-parse package (fatal error), terminal shutdown so can't show to you.
