### ISSUE TITLE
Conditional yield has no code paths covered

### ISSUE THREAD

**Issue by internalsystemerror** [sebastianbergmann/php-code-coverage#824]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 9.2.0
| PHP version               | 7.4.3
| Driver                    | Xdebug
| Xdebug version (if used)  | 2.9.2
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 9.4.0

Any `yield` operator behind a conditional statement is marked as having no code paths covered by any test. I believe this to be in error. I've put together the following repository that reproduces the issue: https://github.com/internalsystemerror/phpunit-test.

Note that I've tried many different combinations of yielding both sides of the condition, only one side, yielding null vs array vs string etc etc. It seems that this entire method is marked as having no code paths covered, yet removing the condition it works as expected.

I'm not against the idea that I'm doing something wrong here, however I'm unable to follow what it is, and it may be this is a bug in xdebug instead.

**Comment by sebastianbergmann** [comment]
@derickr Is this a bug in Xdebug?

**Comment by derickr** [comment]
I don't fully understand the problem here, but I do see that in their "paths" overview line 19 isn't shown. That's not because of a bug in Xdebug, but rather because PHP generates the `yield` opcode on line 20 (and not line 19):

```
line      #* E I O op                           fetch          ext  return  operands
-------------------------------------------------------------------------------------
   16     0  E >   RECV                                             !0      
          1        GENERATOR_CREATE                                         
   18     2      > JMPZ                                                     !0, ->4
   20     3    >   YIELD                                                    <array>
   26     4    > > GENERATOR_RETURN                                         

```

**Comment by internalsystemerror** [comment]
I set up your VLD extension and I'm using it to try and debug this further. I tried the following unsuccessfully also:
![image](https://user-images.githubusercontent.com/1626298/95692370-23415080-0c1d-11eb-9901-bb64015f0644.png)

Though the VLD output for the above does at least show the yield on line 19.
![image](https://user-images.githubusercontent.com/1626298/95692425-964ac700-0c1d-11eb-8efb-11fe74ba91f9.png)

Also the following shows the same VLD output (yield on line 19) but does not show as being covered:
![image](https://user-images.githubusercontent.com/1626298/95692404-6e5b6380-0c1d-11eb-97fb-8e9dabcb8a66.png)

**Comment by sebastianbergmann** [comment]
I am going ahead and close this issue as it does not appear to be an issue in this library.

**Comment by internalsystemerror** [comment]
Forgive me for misunderstanding but I thought we were highlighting that this was an issue in this library and not xdebug? Where should this issue be tracked?

**Comment by sebastianbergmann** [comment]
> That's not because of a bug in Xdebug, but rather because PHP generates the `yield` opcode on line 20 (and not line 19):

This means that while it is not an issue in Xdebug itself, Xdebug reports incorrect data. That is the data this library has to work with.

**Comment by internalsystemerror** [comment]
Thanks, I'm not sure I still understand as I showed even with the yield opcode on line 19 it still has the same issue. Should I open an issue on xdebug instead?
