### ISSUE TITLE
Explore SQLite for static analysis cache storage

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/php-code-coverage#826]
@johannes mentioned:

> As this seems to cache multiple files I however would think about going a different route and using SQLite as a cache file. See https://sqlite.org/fasterthanfs.html and https://sqlite.org/appfileformat.html

**Comment by sebastianbergmann** [comment]
@Slamdunk What do you think?

**Comment by Slamdunk** [comment]
I have no experience on SQLive vs FS performance comparison.
If you ask me to vote right here right now, I'd say no to add a so much more complex external dependency before squeezing FS as much as possible, and in that regard we still have a lot of margin.

**Comment by sebastianbergmann** [comment]
Thanks!
