### ISSUE TITLE
PHP Coverage Summary JSON output

### ISSUE THREAD

**Issue by everton-nasc** [sebastianbergmann/php-code-coverage#829]
**Feature Request**
I'd like to suggest a phpunit coverage report output on `JSON` format.
Similar as we already have with `--coverage-text` output, the suggested JSON format could be like:

Commands: 
--> Entire project: `./bin/phpunit --coverage-json [FileName.json]`
--> Folder specific: `./bin/phpunit --coverage-json [FileName.json] app/Folder/Feature`

**JSON output file**
```json
{
  "PHP Coverage Report": {
    "Time": "2020-10-22 21:55:08",
    "Summary": {
      "ProjectName": "XPTO",
      "Folder": "/app/[Folder]/[Feature]",
      "Classes": {
        "pct": "51.70",
        "qty": "(4276/8271)"
      },
      "Methods": {
        "pct": "70.87",
        "qty": "(31059/43823)"
      },
      "Lines": {
        "pct": "66.84",
        "qty": "(364915/545954)"
      }
    },
    "Classes List": {
      "FeatureXpto": {
        "Methods": {
          "pct": "7.14",
          "qty": "(1/14)"
        },
        "Lines": {
          "pct": "7.14",
          "qty": "(156/347)"
        }
      },
      "FeatureXptoTest": {
        "Methods": {
          "pct": "13.65",
          "qty": "(12/45)"
        },
        "Lines": {
          "pct": "55.14",
          "qty": "(126/127)"
        }
      },
      "FeatureXYZ": {
        "Methods": {
          "pct": "100.00",
          "qty": "(10/10)"
        },
        "Lines": {
          "pct": "100.00",
          "qty": "(200/200)"
        },
        {...}
      }
    }
  }
}
```
With the JSON format will be a good approach and less time consuming when we need to create custom internal reports, such as notify the coverage via slack or something else.

Any suggestion or thoughts will very appreciated.

**Comment by jonyen** [comment]
Just want to also add that I am interested in this feature as well.

**Comment by sebastianbergmann** [comment]
I do not think that such functionality should be added.

**Comment by philip-crawford** [comment]
I would also be interested in having JSON coverage output.  

@sebastianbergmann could you please explain your stance on the issue?

**Comment by christhomas** [comment]
I'm also curious why this isn't a good idea. It's easy to parse and requires no special tools, command line tools like jq can be used easily and it's simple.

**Comment by ollieno** [comment]
I actually need it now for agentic coding so that the agent can easily check if code coverage is at the configured levels. JSON is less token burns and it should be added as an output format.

**Comment by turkeryildirim** [comment]
Hi,

I ran into the same limitation regarding JSON output for coverage data and ended up implementing a small solution as a PHPUnit extension.

It accesses the raw coverage data at runtime (instead of converting from XML) and exports it as structured JSON.

If anyone is looking for a JSON-based coverage output, this might be useful:

https://github.com/turkeryildirim/phpunit-json-coverage-report
