### ISSUE TITLE
Clover Report - XML does not include coveredClasses value in metrics element

### ISSUE THREAD

**Issue by everton-nasc** [sebastianbergmann/php-code-coverage#830]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 6.1.4
| PHP version               | 7.3
| Driver                    | Xdebug
| Xdebug version (if used)  | 2.9.6
| Installation Method       | Composer 
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 7.5.20

Couple days ago I've started to dig into the clover report in order to get the coverage values from the entire project through the `<project><metrics></></project>` and I noticed there's just the value `classes=`.
I'm not a Clover report specialist, but I didn't find any information about coverage values for classes in XML output (like methods: `coveredmethods="[INT]"`.

Questions:
1. Does Clover report provide classes coverage output values?
2. Is there a specific formula to collect the classes/traits coverage from the XML report?

XML Output
```xml
<?xml version="1.0" encoding="UTF-8"?>
<coverage generated="1605287047">
  <project timestamp="1605287047">
    <package name="Lib\[Feature]\Application\Command">
      <edited>....</edited>
    <metrics files="354" loc="39069" ncloc="32781" classes="329" methods="1458" coveredmethods="1125" conditionals="0" coveredconditionals="0" statements="13984" coveredstatements="12866" elements="15442" coveredelements="13991"/>
  </project>
</coverage>
```
Thanks!

**Comment by sebastianbergmann** [comment]
Neither PHPUnit 7.5 nor php-code-coverage 6.1 are supported anymore. Does the problem exist in a supported version of this library?

**Comment by everton-nasc** [comment]
Just found another solution using `--coverage-xml` command. Closing this issue - thanks!
