### ISSUE TITLE
Support XDEBUG_MODE environment variable

### ISSUE THREAD

**Issue by derickr** [sebastianbergmann/php-code-coverage#834]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.4.3
| PHP version         | 7.4.11
| Installation Method | Composer

#### Summary

PHPUnit only understands Xdebug modes set in `php.ini` when checking for coverage availability.

When running:

```
$ XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-text
```
It is not recognised that the mode is set.

#### Current behavior

PHPUnit shows a warning:

```
Warning:       xdebug.mode=coverage has to be set in php.ini
```

#### How to reproduce

- Any repository with phpunit available in `vendor/bin/phpunit`.
- Run: `XDEBUG_MODE=coverage php -n -dzend_extension=xdebug vendor/bin/phpunit --coverage-text`

#### Expected behavior

Code coverage should have been run, as it would have been with:

```
php -n -dzend_extension=xdebug -dxdebug.mode=coverage ./vendor/bin/phpunit --coverage-text
```

**Comment by sebastianbergmann** [comment]
From reading

> Besides setting the mode with xdebug.mode, you can also set the mode with the XDEBUG_MODE environment variable. If this environment variable is active, it overrides the mode as set through xdebug.mode.

I understand that Xdebug looks at the `XDEBUG_MODE` environment variable and changes its mode based on that. As far as I can see, though, Xdebug does not provide an API for querying its mode apart from using `ini_get('xdebug.mode')` (or using `xdebug_info()`, capturing its output through output buffering, and then parsing the generated HTML).

For a short term solution, this library can fall back to looking for/at the `XDEBUG_MODE` environment variable. If it is set, its string contents will be treated like the string contents of `ini_get('xdebug.mode')` is right now:

```php
if (!ini_get('xdebug.mode') || !in_array('coverage', explode(',', ini_get('xdebug.mode')), true)) {
    throw new Xdebug3NotEnabledException;
}
```

The message of `Xdebug3NotEnabledException`, of course, needs to be adapted.

In the long run, though, I would really like for Xdebug to provide a function that returns information about which mode(s) is/are currently active.

**Comment by sebastianbergmann** [comment]
Created https://bugs.xdebug.org/view.php?id=1898 for tracking my feature request for Xdebug.

**Comment by AyrtonRicardo** [comment]
Is this supposed to work when configuring the xdebug variable via `phpunit.xml.dist` file?

Because if so, then the file below is not working: it's not generating reporting and showing me the warning mentioned in the issue.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- https://phpunit.readthedocs.io/en/latest/configuration.html -->
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="vendor/phpunit/phpunit/phpunit.xsd"
         bootstrap="tests/bootstrap.php"
>
    <php>
        <ini name="error_reporting" value="-1" />
        <ini name="xdebug.mode" value="coverage" />
        <env name="XDEBUG_MODE" value="coverage" />
    </php>

    <testsuites>
        <testsuite name="Main Test Suite">
            <directory>tests</directory>
        </testsuite>
    </testsuites>

    <coverage processUncoveredFiles="true">
        <include>
            <directory suffix=".php">src</directory>
        </include>
        <report>
            <clover outputFile="./reports/coverage_clover.xml"/>
        </report>
    </coverage>

    <logging>
        <junit outputFile="reports/junit.xml"/>
    </logging>
</phpunit>
```

Version code coverage: phpunit/php-code-coverage (9.2.5)
Version Phpunit: phpunit/phpunit (9.4.4)
Installation via: composer
PHP Version: PHP 7.3.21

**Comment by sebastianbergmann** [comment]
No, this cannot work when `XDEBUG_MODE` is set using PHPUnit's XML configuration file. It has to be set at PHP startup, "long" before the code that parses the XML configuration file is parsed.

**Comment by AyrtonRicardo** [comment]
@sebastianbergmann thanks for clarify it.
I will stick to this command then `XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-text `.

**Comment by nelson6e65** [comment]
As a Composer script, you can use `"@putenv XDEBUG_MODE=coverage"`:

```json
"test:coverage": [
  "@putenv XDEBUG_MODE=coverage",
  "phpunit --color=always --coverage-clover=\"output/code-coverage/clover.xml\""
],
"test:coverage-html": [
  "@putenv XDEBUG_MODE=coverage",
  "phpunit --color=always --coverage-html=\"output/code-coverage\""
],
```

**Comment by SukhrobNuraliev** [comment]
xdebug.mode=coverage has to be set in php.ini
