### ISSUE TITLE
Xdebug TypeError explode()

### ISSUE THREAD

**Issue by Benjaminhu** [sebastianbergmann/php-code-coverage#835]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.5.10
| PHP version         | 7.2.24
| Installation Method | PHAR

#### Summary

```
PHP Fatal error:  Uncaught TypeError: explode() expects parameter 2 to be string, boolean given in phar:///bin/phpunit/php-code-coverage/Driver/Xdebug.php:39
Stack trace:
#0 phar:///bin/phpunit/php-code-coverage/Driver/Xdebug.php(39): explode(',', false)
sebastianbergmann/phpunit#1 phar:///bin/phpunit/php-code-coverage/CodeCoverage.php(702): PHPUnit\SebastianBergmann\CodeCoverage\Driver\Xdebug->__construct(Object(PHPUnit\SebastianBergmann\CodeCoverage\Filter))
sebastianbergmann/phpunit#2 phar:///bin/phpunit/php-code-coverage/CodeCoverage.php(127): PHPUnit\SebastianBergmann\CodeCoverage\CodeCoverage->selectDriver(Object(PHPUnit\SebastianBergmann\CodeCoverage\Filter))
sebastianbergmann/phpunit#3 phar:///bin/phpunit/phpunit/TextUI/TestRunner.php(363): PHPUnit\SebastianBergmann\CodeCoverage\CodeCoverage->__construct(NULL, Object(PHPUnit\SebastianBergmann\CodeCoverage\Filter))
sebastianbergmann/phpunit#4 phar:///bin/phpunit/phpunit/TextUI/Command.php(97): PHPUnit\TextUI\TestRunner-> in phar:///bin/phpunit/php-code-coverage/Driver/Xdebug.php on line 39
```

I downgrade to `PHPUnit 8.5.9` and no problem.

**Comment by sebastianbergmann** [comment]
The PHPUnit 8.5.10 PHAR does not have the php-code-coverage 7.0.12 version of `Xdebug.php` (see https://github.com/sebastianbergmann/php-code-coverage/blob/7.0.12/src/Driver/Xdebug.php) bundled in it.

Can you please check if the problem still exists in php-code-coverage 7.0.12 by installing PHPUnit 8.5 using Composer instead of from a PHAR? If php-code-coverage 7.0.12 does not have this issue then I just need to roll a new PHPUnit 8.5 release to update its PHAR.

**Comment by sebastianbergmann** [comment]
CC @hollodotme

**Comment by Benjaminhu** [comment]
> The PHPUnit 8.5.10 PHAR does not have the php-code-coverage 7.0.12 version of `Xdebug.php` (see https://github.com/sebastianbergmann/php-code-coverage/blob/7.0.12/src/Driver/Xdebug.php) bundled in it.
> 
> Can you please check if the problem still exists in php-code-coverage 7.0.12 by installing PHPUnit 8.5 using Composer instead of from a PHAR? If php-code-coverage 7.0.12 does not have this issue then I just need to roll a new PHPUnit 8.5 release to update its PHAR.

I installed it `./bin/composer require --dev phpunit/phpunit ^8.5` and it works, no `Xdebug` problem! Thx.

**Comment by hollodotme** [comment]
Can also confirm that the error is gone when I install PHPUnit 8.5.10 via composer instead of PHAR.

**Comment by sebastianbergmann** [comment]
Thank you!

**Comment by hollodotme** [comment]
Thank you! 😊 Builds are green again with v8.5.11.

**Comment by Benjaminhu** [comment]
Thank you!
