### ISSUE TITLE
XDEBUG_CC_UNUSED does not exist in Xdebug 3

### ISSUE THREAD

**Issue by Bilge** [sebastianbergmann/php-code-coverage#838]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 6.1.4
| PHP version               | 7.4.13
| Driver                    | Xdebug
| Xdebug version (if used)  | 3.0.0
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 7.5.20

All of my [builds](https://travis-ci.com/github/Porter-connectors/HttpConnector/jobs/452115837), that have automatically been upgraded to use Xdebug 3 by Travis, are now failing with:

>Use of undefined constant XDEBUG_CC_UNUSED - assumed 'XDEBUG_CC_UNUSED' (this will throw an Error in a future version of PHP)

That is, `XDEBUG_CC_UNUSED` does not exist any more.

**Comment by lfkwtz** [comment]
fwiw - fixed this temporarily by running `sudo pecl install -f xdebug-2.7.0` on my circleci box

**Comment by dvdoug** [comment]
see https://bugs.xdebug.org/view.php?id=1903

**Comment by lfkwtz** [comment]
thanks @dvdoug  -  looks like it'll be fixed in the next release https://github.com/xdebug/xdebug/pull/699
