### ISSUE TITLE
PHP Warning:  Uncaught require_once(autoload.php): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by GeneralBouLi** [sebastianbergmann/php-code-coverage#839]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 7.0.14
| PHP version               | 7.4.12
| Driver                    | Xdebug 
| Xdebug version (if used)  | 2.9.8
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 8.5.13

Hi,
I used `vendor/bin/phpunit --testsuite="modules"` to test my drupal custom modules.
I use this code un phpunit.xml :
```
<testsuite name="modules">
        <directory>./drupal/modules/custom</directory>
</testsuite>

<filter>
    <whitelist processUncoveredFilesFromWhitelist="true">
      <directory suffix=".module">./drupal/modules/custom</directory>
      <directory suffix=".php">./drupal/modules/custom</directory>
```
I got this error :
`PHP Warning:  Uncaught require_once(autoload.php): failed to open stream: No such file or directory`
The stack trace :
`PHP Fatal error:  SebastianBergmann\CodeCoverage\CodeCoverage::main(): Failed opening required 'autoload.php' (include_path='/home/jerome/www/skeleton/vendor/pear/archive_tar:/home/jerome/www/skeleton/vendor/pear/console_getopt:/home/jerome/www/skeleton/vendor/pear/pear-core-minimal/src:/home/jerome/www/skeleton/vendor/pear/pear_exception:.:/usr/share/php') in /home/jerome/www/skeleton/drupal/core/modules/statistics/statistics.php on line 13`

There might be a mistake I made in the configuration but if not do you have a solution?

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry.
