### ISSUE TITLE
Coverage is not processing uncovered files and is not marking them as 0%

### ISSUE THREAD

**Issue by ibrunotome** [sebastianbergmann/php-code-coverage#840]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.0
| PHP version         | 7.4.10
| Installation Method | Composer

#### Summary

Coverage is not processing uncovered files and is not marking them as 0%. The total of folder should not be 100%

#### Current behavior

<img width="1417" alt="Screen Shot 2020-12-11 at 16 11 51" src="https://user-images.githubusercontent.com/4256471/101944639-cf76c780-3bcb-11eb-82a9-d3e107e19189.png">

The same problem that this guy has 3 years ago: https://stackoverflow.com/questions/41852906/phpunit-is-effectively-marking-an-untested-class-0-coverage-as-being-covered

#### How to reproduce

I'm using Laravel, this is my phpunit.xml

```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/9.3/phpunit.xsd" backupGlobals="false"
         backupStaticAttributes="false" bootstrap="vendor/autoload.php" colors="true" convertErrorsToExceptions="true"
         convertNoticesToExceptions="true" convertWarningsToExceptions="true" processIsolation="false"
         stopOnFailure="true">
    <coverage processUncoveredFiles="true">
        <include>
            <directory suffix=".php">./app</directory>
        </include>
        <exclude>
            <directory>./app/Nova</directory>
            <directory>./app/Policies</directory>
        </exclude>
        <report>
            <clover outputFile="./tests/coverage/coverage.xml"/>
            <html outputDirectory="./tests/coverage" lowUpperBound="50" highLowerBound="80"/>
        </report>
    </coverage>
    <testsuites>
        <testsuite name="Unit">
            <directory suffix="Test.php">./tests/Unit</directory>
        </testsuite>
        <testsuite name="Feature">
            <directory suffix="Test.php">./tests/Feature</directory>
        </testsuite>
        <testsuite name="Integration">
            <directory suffix="Test.php">./tests/Integration</directory>
        </testsuite>
        <testsuite name="Regression">
            <directory suffix="Test.php">./tests/Regression</directory>
        </testsuite>
    </testsuites>
    <php>
        <server name="APP_ENV" value="testing"/>
    </php>
</phpunit>

```

#### Expected behavior

Mark all the files with 0% (except Handler) and recalculate the total value

**Comment by sebastianbergmann** [comment]
There can be many reasons why a specific line is not covered. Each of them is likely a different issue. In order to be able to reproduce *anything* and not get bogged down with details, you need to provide the following **in ONE new issue per case**.

That means:

- The exact versions of (this is what the template requires too, but more):
  - PHP
  - PHP Code Coverage
  - Xdebug
  - PHPUnit
- ```php -v``` output
- Either a ```.tar.gz``` archive or a GitHub repository with a reproduce case. With **one** file that shows the problem and **one** test case file (with the exception that sometimes, you might need **two** source files to show a problem.

This information should be filed as **one specific case per issue**.

**Comment by HoangLongTrinh** [comment]
@sebastianbergmann please help me check it, i have same issue:
+ PHP 7.2.34
+ Xdebug 3.0.4
+ PHPUnit 8.5.21
+ PHP Code Coverage: 7.0.15
![Selection_036](https://user-images.githubusercontent.com/15134903/143001900-bb1bee88-6bd6-4719-8ba5-70b161085687.png)

**Comment by sebastianbergmann** [comment]
No feedback, closing.
