### ISSUE TITLE
Coverage file filtering does not handle symlink loops well

### ISSUE THREAD

**Issue by anomiex** [sebastianbergmann/php-code-coverage#849]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 9.2.5
| PHP version               | 7.3.27, 7.4.15, 8.0.2
| Driver                    | PHPDBG
| Xdebug version (if used)  | N/A
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 9.5.2

### Test case

Use `docker run --rm -it debian:buster` or `docker run --rm -it debian:sid` to start with a clean environment. Inside the container, execute the following:

```
apt-get update
apt-get install -y php-cli php-phpdbg php-xml composer
# Alternatively with debian:sid, do
# apt-get install -y php8.0-cli php8.0-phpdbg php8.0-mbstring php8.0-xml composer

mkdir /tmp/test
cd /tmp/test
cat <<EOF > phpunit.xml.dist
<?xml version="1.0"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/9.3/phpunit.xsd">
  <coverage processUncoveredFiles="false">
    <include>
      <directory suffix=".php">.</directory>
    </include>
    <exclude>
      <directory suffix=".php">tests</directory>
      <directory suffix=".php">vendor</directory>
    </exclude>
  </coverage>
  <testsuites>
    <testsuite name="main">
      <directory prefix="test" suffix=".php">tests</directory>
    </testsuite>
  </testsuites>
</phpunit>
EOF
touch foo.php
mkdir tests
composer require phpunit/phpunit

time phpdbg -qrr ./vendor/bin/phpunit --coverage-clover clover.xml

ln -s $PWD tests/loop
time phpdbg -qrr ./vendor/bin/phpunit --coverage-clover clover.xml
```

### Expected results

Both executions of `time phpdbg -qrr ./vendor/bin/phpunit --coverage-clover clover.xml` take about the same amount of time, probably about 0.1s.

### Actual results

The second execution, after creating the loop symlink, takes much longer. Around 25s locally.

### Analysis

It seems that all included directories are scanned for files, _without_ any loop detection, before any of the exclusion rules are applied. The only reason it doesn't run forever is that PHP's iterators seems to give up after a sufficient depth.

**Comment by sebastianbergmann** [comment]
I do not think that we should add complexity to this library so that symlink situations that lead to infinite loops are properly handled.
