### ISSUE TITLE
Make static analysis cache usable during CI

### ISSUE THREAD

**Issue by sanmai** [sebastianbergmann/php-code-coverage#850]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 7.0.14 

It isn't new that getting a coverage report is kind of slow in recent versions of the package, as explored in #789 in great detail. Yet we can't get any benefits from the cache during CI, looking at about 40-50% elevated times. For a medium-sized project it could be additional 5 minutes for CI to pass, even more for larger projects.

### The root of the issue

Static analysis cache uses modification time to validate cache, yet during CI we have a fresh checkout which has all timestamps reset to current time. That's what Git does. Which event, in turn, invalidates all cache no matter what effort we make to restore it.

https://github.com/sebastianbergmann/php-code-coverage/blob/0b4ce85a86040303d93beddf4f31f2ab07775e9a/src/StaticAnalysis/Cache.php#L36-L49

On the other hand, we truly shouldn't be using stale caches, so we can't just reset all `mtimes` in cache.

### Possible solution

Static analysis cache storage can use a hash of a whole file as a part of a final hash, thus ensuring caches are busted if a file was modified. This can be done by default, or on an opt-in basis, keeping old `mtime` logic intact. 

(I don't think if we'd read a file twice would matter much because chances are it'll be a cached read. So it might be just as good to introduce a new behavior forgetting the old.)

**Comment by sanmai** [comment]
Please let me know if this is a good problem to work on.

**Comment by sebastianbergmann** [comment]
@Slamdunk @dvdoug What do you think? Should we use a hash of a file's contents instead of its `filemtime()`?

**Comment by sanmai** [comment]
Fixed in db1c691dac2b21f449b4c21d219be090c5adcc12

**Comment by dvdoug** [comment]
> @Slamdunk @dvdoug What do you think? Should we use a hash of a file's contents instead of its `filemtime()`?

Seems like a good idea to me
