### ISSUE TITLE
Traits should not be marked as executable code

### ISSUE THREAD

**Issue by CJDennis** [sebastianbergmann/php-code-coverage#857]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 9.2.6
| PHP version               | 7.3.13
| Driver                    | Xdebug
| Xdebug version (if used)  | 2.8.0
| Installation Method       | Composer
| Usage Method              | other
| PHPUnit version (if used) | n./.a

The following code has the `use MP3Size;` line incorrectly marked as not covered when explicit method `@covers` annotations are used in the unit tests, e.g. `/** @covers ID3::parse */`, causing the whole file to be 100% covered except for lines, which should be impossible. Since traits get "compiled" into the class, any `use TraitName;` lines should be left as non-executable code, the same as the `class ID3 {` line is.

`src/ID3.php`:
```php
<?php

class ID3 {
  use MP3Size;  // <-- This line is incorrectly marked as covered/not covered instead of non-executable/unmarked

  public function parse() {
    return null;
  }
}
```
`src/MP3Size.php`:
```php
<?php

trait MP3Size {
}
```
`tests/unit/ID3Test.php`:
```php
<?php

use Codeception\Test\Unit;

class ID3Test extends Unit {
  /** @var UnitTester */
  protected $tester;

  protected function _before() {
  }

  protected function _after() {
  }

  // tests

  /**
   * @covers ID3::parse
   */
  public function testShouldDoNothing() {
    $id3 = new ID3();
    self::assertNull($id3->parse());
  }
}
```

**Comment by sebastianbergmann** [comment]
Please open a new ticket in case you still see this problem in php-code-coverage 9.2.11.
