### ISSUE TITLE
Generating code coverage report in Clover XML format ... syntax error, unexpected '-', expecting '{'

### ISSUE THREAD

**Issue by lordisp** [sebastianbergmann/php-code-coverage#858]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | PHPUnit 9.5.5
| PHP version         | PHP 7.4.16
| Installation Method | Composer 

#### Current behavior

`Generating code coverage report in HTML format ... syntax error, unexpected '-', expecting '{'`

and 

`Generating code coverage report in Clover XML format ... syntax error, unexpected '-', expecting '{'`

I've posted this issue also on [stackoverflow](https://stackoverflow.com/questions/68169837/generating-code-coverage-report-in-clover-xml-format-syntax-error)

#### How to reproduce

`.\vendor\bin\phpunit --coverage-html ./coverage.html`

#### Expected behavior

getting a coverage report

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by lordisp** [comment]
@sebastianbergmann , I believe the tests itself  are irrelevant. I'm not sure where else I shall troubleshoot this issue. Here a minimal test:

```php
class MinimalTest extends TestCase
{
    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function test_example()
    {
        $response = $this->get('https://google.com');

        $response->assertStatus(200);
    }
}
```

Executed by `❯ .\vendor\bin\phpunit --filter MinimalTest --coverage-html ./coverage.html`

Result:
```
❯ .\vendor\bin\phpunit --filter MinimalTest --coverage-html ./coverage.html
PHPUnit 9.5.5 by Sebastian Bergmann and contributors.

.                                                                   1 / 1 (100%)

Time: 00:01.234, Memory: 42.00 MB

OK (1 test, 1 assertion)

Generating code coverage report in HTML format ... syntax error, unexpected '-', expecting '{'
```

**Comment by sebastianbergmann** [comment]
Where does `$this->get()` come from? In other words: this is not self-contained.

**Comment by lordisp** [comment]
@sebastianbergmann , guess I'm not sure how to deal with self-contained tests, since I'm new with unit testing but I found I had to exclude the `app/View` directory of `Laravel` for now. Then the coverage report can be generated. If you don't mind, I would close this and post my final findings out of the `app/View` files in case someone else hit the same issue.

Anyhow, thanks for your time!

**Comment by lordisp** [comment]
I finally found the issue. I isolated the root cause by excluding directories of Laravel. The bad directory was actually the `app/View` due too an early mistake I made by generating `laravel` `components` Laravel generates `view` and
 `controller` files for a component. It's not always needed to touch the controller if you don't need php logic, which is why I did not see the issue.

I've created the components these times with a wrong pattern, which led Laravel to generate broken classes (my bad, not Laravel's). By cleaning those out, the coverage report was successfully generated without any exclusions.

**Comment by LocalHeroPro** [comment]
I have similar issue.
Test:
```php
<?php

declare(strict_types=1);

namespace Tests\Unit;

use PHPUnit\Framework\TestCase;

class ExampleTest extends TestCase
{
    /**
     * A basic test example.
     */
    public function testBasicTest(): void
    {
        $this->assertTrue(true);
    }
}

```
output:
```shell
PHPUnit 9.6.0 by Sebastian Bergmann and contributors.



Time: 00:00.055, Memory: 12.00 MB

OK (1 test, 1 assertion)

Generating code coverage report in Clover XML format ... syntax error, unexpected token ")"

Process finished with exit code 2
```
Standard test working as expected.
Test with coverage 100% fails ;/

**Comment by LocalHeroPro** [comment]
In my case resolution was very simply and silly.

Run on ALL code some scanner, rector or something similar. Then check some errors in your code.
In me case it was, for example
```php
$variable = ;
```
Content of uncommited file - WIP.

Maybe in your case, you will find some similar?
