### ISSUE TITLE
.assert($type instanceof Identifier || $type instanceof Name || $type instanceof ComplexType)

### ISSUE THREAD

**Issue by stepozer** [sebastianbergmann/php-code-coverage#878]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 9.2.8
| PHP version               | 8.0.11
| Installation Method       | Symfony Bridge
| Usage Method              | PHPUnit 
| PHPUnit version (if used) | 9.5.10

Our CI/CD system installed latest version of `php-code-coverage` and after that I get this error. And I also checked all other versions PHP (9.5.0 - 9.5.10) unit and it also does not work, seems to be some issue with php-code-coverage.

Can you please downgrade php-code-coverage version in PHPUnit, because I am not sure how to fix it...

Command:

```
php -dpcov.enabled=1 -dpcov.directory=.  -dpcov.exclude="~vendor~" /application/bin/phpunit --coverage-html /application/tmp/coverage-report
```

**Comment by stepozer** [comment]
I checked php-code-coverage version 9.2.7 and everything working well.

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by stepozer** [comment]
Hello,

After some research, I found the issue. I have nikic/php-parser v4.11.0 in my project composer.json file. After update this library everything working well. So you can close this issue. Maybe it can be helpful for somebody.

You asked me about the error, it was all error message:

![image](https://user-images.githubusercontent.com/3325965/139599505-a8c05b7e-b198-4907-bdc5-95d6db705a93.png)

So I think to assert it not always a good idea for this kind of messages. I spend 2 hours trying to understand why my CI/CD stop working when I don't update any library in my project. I suggest changing asserts into exceptions.

**Comment by sebastianbergmann** [comment]
> I spend 2 hours trying to understand why my CI/CD stop working when I don't update any library in my project.

Sorry, but that is your problem. The `composer.json` of this library has `"nikic/php-parser": "^4.13.0"`. This is what it requires, this is what it expects, because this is what it depends/relies on.

**Comment by stepozer** [comment]
Yes, but when I locked phpunit I expected that all libraries will be locked. But php-code-coverage was updated without any actions from my side. That is was surprised for me, when I rollback PHPUnit to previous version and it does not help.

**Comment by stepozer** [comment]
My CI/CD working on phpunit 9.5 2-3 months without any errors. This version was locked. After updating php-code-coverage you break all PHPUnit versions for my project from 9.5.0 to 9.5.5. Where was my mistake? How do you break PREVIOUS version of your library? If you update PHPUnit version please don't touch old one.

**Comment by stepozer** [comment]
This line break me everything https://github.com/sebastianbergmann/phpunit/blob/9.5/composer.json#L36, because you don't fix the version of php-code-coverage

**Comment by GPHemsley-RELX** [comment]
The assert in question here was recently changed in 12856cc6e3827ed187c588fff59baa011bab328d. That change is apparently not playing well with other things.

**Comment by GPHemsley-RELX** [comment]
OK, I don't think this is a problem with php-code-coverage directly; it just so happened that the change I mentioned triggered the problem.

I _think_ this is a problem having to do with the app being tested using an earlier version of nikic/php-parser than the phpunit running the tests against it. For some reason, the phpunit running is using the wrong instance of php-parser and is thus failing to find the ComplexType class required to run (and pass) the assert.

This is clearly a bug somewhere, but I can't figure out _where_. I can't even reproduce this issue in all environments to be able to whittle it down.

@stepozer A few questions for you:
* What version of symfony/phpunit-bridge are you using in your app?
* Are you using Docker to run the tests? If so, are you able to reproduce outside of Docker?
* What version of Composer are you using?

**Comment by stepozer** [comment]
@GPHemsley-RELX sorry for long answer. Right now I properly understand what happened because two days ago I get similar issue with phpdocumenter

```
Fatal error: Class phpDocumentor\Reflection\PseudoTypes\List_ may not inherit from final class (phpDocumentor\Reflection\Types\Array_) in /builds/dev/lms-api/lms-api/bin/.phpunit/phpunit-9.5.10-0/vendor/phpdocumentor/type-resolver/src/PseudoTypes/List_.php on line 27
```

I think good description was given by @sebastianbergmann in this tweet https://mobile.twitter.com/s_bergmann/status/999635212723212288. Two times I got very strange bugs without updating anything. Right now I know what to do - just make composer update. Maybe we will find some solution in future, it is not bug it PHPUnit, it is issue in our library manager.

Sorry for the noise and thanks for great library that I use every day @sebastianbergmann !

**Comment by sebastianbergmann** [comment]
> it is issue in our library manager

No, this is not an issue in Composer. You are just using Composer wrong. Sorry for being blunt.

**Comment by stepozer** [comment]
@sebastianbergmann Can you give some suggestions how to avoid this type of error in the future in case PHPUnit? RIght now I use symfony PHPUnit bridge (https://symfony.com/doc/current/components/phpunit_bridge.html) so I am not sure how do it into "right way"

**Comment by sebastianbergmann** [comment]
No, I cannot help you with Symfony Bridge. Please take your question to the vendor of that PHPUnit extension.
