### ISSUE TITLE
pcov segmentation fault

### ISSUE THREAD

**Issue by nuernbergerA** [sebastianbergmann/php-code-coverage#879]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 9.2.8
| PHP version               | 8.0.12
| Driver                    | Pcov
| Installation Method       | Composer
| Usage Method              | pest with parallel
| PHPUnit version (if used) | 9.5.10

Unfortunately, there is no real code to reproduce the error nor there is a propper error due to the layers in between.

The suite has 1421 test with many assertions and runs with pest in parallel mode.
All tests are green the error occurs only if we run with coverage reports.

I found this only via try and error that if we fix the version to `9.2.7` the error is gone.

```bash
Aborted (core dumped)

Script ./vendor/bin/pest --parallel --processes=6 --log-junit reports/phpunit-test-report.xml --coverage-clover reports/coverage/phpunit-coverage-report.xml --coverage-html=reports/coverage handling the jenkins:test-coverage event returned with error code 134
```

**Comment by sebastianbergmann** [comment]
Please report bugs in the PCOV extension on the [PCOV project](https://github.com/krakjoe/pcov/issues). CC @krakjoe

**Comment by nuernbergerA** [comment]
@sebastianbergmann maybe i was not clear enough:

The issue is caused by #877 if I revert the changes in the file all errors are gone.

Note that `clear() ` was called every time before.

I don't see why this should be addressed in the pcov repo, but feel free to correct me.

**Comment by sebastianbergmann** [comment]
No matter whether the PHP code in this library is wrong or not, @krakjoe can comment on that, if it causes a segfault in PHP then that is a bug in PHP. And if it causes a segfault in PCOV, then that is a bug in PCOV.
