### ISSUE TITLE
[Support] Coverage for version-specific code?

### ISSUE THREAD

**Issue by donquixote** [sebastianbergmann/php-code-coverage#883]
I am writing a package that contains lots of code that is specific to a PHP version.

```php
// Line-by-line version switch.
if (PHP_VERSION_ID < 80000) {
  // These lines will have zero coverage in PHP 8.
  [..]
} else {
  // These lines will have zero coverage in PHP 7.
  [..]
}

// File-by-file version switch:
if (PHP_VERSION_ID < 80000) {
  // The included file will have zero coverage in PHP 8.
  include __FILE__ . '.php8';
  [..]
} else {
  // The included file will have zero coverage in PHP 7.
  include __FILE__ . '.php7';
}
```

The ideal way to determine coverage would be to generate separate reports for php 7 and php 8, and then combine the two reports to determine full coverage.

Is there any existing solution or trick for this?

Another option would be to split the package, so that I would have one package for php7 and another for php8. But I don't know if I want to do this.

**Comment by sebastianbergmann** [comment]
Run the tests with both versions, collect the coverage using `--coverage-php` and then merge coverage from both runs using `phpcov`.

**Comment by donquixote** [comment]
Thanks, I will try this.

**Comment by donquixote** [comment]
It does work!
For anyone finding this, here is a shell script I currently use for this. Based on https://stackoverflow.com/questions/29039343/how-to-run-php-unit-multiple-times-and-concatenate-the-coverage-report
```sh
mkdir -p build/coverage/parts
/usr/bin/php7.4 ./vendor/bin/phpunit --coverage-clover build/coverage/parts/php7.4.xml
/usr/bin/php8.0 ./vendor/bin/phpunit --coverage-clover build/coverage/parts/php8.0.xml
/usr/bin/php8.0 ./vendor/bin/phpcov merge --clover build/coverage/clover.xml build/coverage/parts
```

Prerequisites:
- Different php versions installed in the system.
- phpcov installed in the project, e.g. by `composer require phpunit/phpcov`. (system-wide install would also work)

In phpunit.xml the location of the file can be specified like so:
```xml
  <coverage>
    <report>
      <clover outputFile="build/coverage/clover.xml"/>
```

In PhpStorm, use "Run | Show coverage data" and click the "+" to add the custom xml file.
https://youtrack.jetbrains.com/issue/WI-64063
