### ISSUE TITLE
Inconsistent line coverage leaves some lines marked as uncovered in merged report.

### ISSUE THREAD

**Issue by donquixote** [sebastianbergmann/php-code-coverage#884]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 9.2.8
| PHP version               | 7.4.26 and 8.0.13
| Driver                    | pcov 1.0.9, installed with apt.
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 9.5.10

### Basics
For every line of code, a coverage report can do one of 3 things:
1. mark as covered
2. mark as uncovered
3. skip (no entry in clover.xml), because it is not considered a relevant line of code.

If a line is uncovered in one report, and skipped in another report, it will be marked as uncovered in the merged report.
This can be a problem, if there the "skip" behavior is inconsistent between the merged reports.

### My use case

I have some code that runs only in PHP 7.4. See #883.
The code contains if / else, with `else` on a separate line (Drupal convention).
It also contains some multi-line array assignment, where the first line typically does not count for coverage.
See below for code samples.

I am generating two coverage reports which are later merged.
For debug purposes I am creating the partial reports as clover and as `.cov`.

I then did some experiments to determine where the differences are coming from.

```sh
mkdir -p build/coverage/parts
/usr/bin/php7.4 ./vendor/bin/phpunit --coverage-php build/coverage/parts/php7.4.cov
/usr/bin/php8.0 ./vendor/bin/phpunit --coverage-php build/coverage/parts/php8.0.cov
/usr/bin/php7.4 ./vendor/bin/phpunit --coverage-clover build/coverage/parts/php7.4.xml
/usr/bin/php8.0 ./vendor/bin/phpunit --coverage-clover build/coverage/parts/php8.0.xml
/usr/bin/php8.0 ./vendor/bin/phpcov merge --clover build/coverage/clover.xml build/coverage/parts
```

(I tried some variations of this, e.g. using `-d pcov.enabled=1`, but the observations below seem consistent)

Now here is what happens:
- Coverage for 7.4 skips some lines as irrelevant for coverage.
- Coverage for 8.0 marks some of these lines with `<line num="***" type="stmt" count="0"/>`.
- In the merged report, these lines are marked as not covered, if they had a "0" in report A and were skipped in report B.

### Observation: Coverage inconsistencies in detail

Lines with `else`:
```php
        if ($qn !== NULL) {
          $fqn = '\\' . $qn . $fqn;
        }
        else {  // Marked as uncovered in php 8.0, if the entire file is never included.
```

Multi-line arrays:
```php
    $x = [  // skipped in php7.4, marked in 8.0
      5,  // skipped in 8.0 if file not included
      $b,  // skipped in 8.0 if file not included
      6,  // skipped in 8.0 if file not included
    ];
    $x = [  // skipped in php7.4
      ...[5],  // skipped in 8.0 if file not included
      ...$x,  // skipped in 8.0 if file not included
      ...[6],  // skipped in all cases
    ];
    $y = [  // skipped in php7.4
      ...[5],  // skipped in 8.0
    ];
```

So it seems the decision which line to skip depends on:
- php version
- whether the file is included or not
- possibly which driver was used? e.g. xdebug, pcov, other?

At least the first two are undesirable when merging reports.

### Solution / question
I don't know yet if this should be a support issue or a feature request or bug report.

As a support issue, I would ask: Is there a way to achieve consistent line skipping between runs? E.g. a config option somewhere? Or using a specific driver?

Or could the merging be more smart?
I think this would be too late, because once we are merging, we are no longer looking at code.

**Comment by donquixote** [comment]
> There is nothing we can do about this, I'm afraid.

Sad :(

Are you aware of known differences between these drivers? Is this documented somewhere?
I remember in xdebug it is sometimes surprising where you can put a break point and where you can't. Probably it is similar here.

**Comment by mikkorantalainen** [comment]
I think the only thing PHPUnit *could* do is to have (hardcoded?) list of commonly mis-interpreted code. For example, always ignore the whole row if it only contains one or more of "{", "else", "}" and comments, regardless of what the actual PHP coverage statistics claim.

The issue with array initialization syntax probably cannot be fixed at PHPUnit level.

That said, it probably makes more sense to fix the actual driver.

**Comment by donquixote** [comment]
I don't think any "always ignore xyz" is a solution.
What we would need to do is to post-process the coverage data, with an operation that is aware of the code. Then the coverage data would be saved in a "canonical" format. These canonical files could then be merged safely.
