### ISSUE TITLE
Files that have only \r (CR, 0x0d) EOL characters are not handled correctly

### ISSUE THREAD

**Issue by kolesar-andras** [sebastianbergmann/php-code-coverage#885]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 9.2.9
| PHP version               | 7.4.3
| Driver                    | Xdebug
| Xdebug version (if used)  | 2.9.2
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 9.5.10

Files that have only \r (CR, 0x0d) characters on line ends and having at least two comment lines cause failure:

    Generating code coverage report in HTML format ... $nonCommentLinesOfCode must not be negative

Linux command `wc -l` shows 0 for these files beacuse it counts LF characters. Number of lines is 1 because no LF characters are in the file. `$nonCommentLinesOfCode = 1-2 = -1` triggers the bug.

Macintosh files before OS X had this type of line endings.

Similar to previously fixed issue #831.

**Comment by kolesar-andras** [comment]
Example file: [source_without_lf_only_cr.php.txt](https://github.com/sebastianbergmann/php-code-coverage/files/7587964/source_without_lf_only_cr.php.txt)

**Comment by sebastianbergmann** [comment]
Do you still see this problem in php-code-coverage 9.2.11?

**Comment by kolesar-andras** [comment]
Yes, unfortunately.

```
  - Upgrading phpunit/php-code-coverage (9.2.9 => 9.2.11): Extracting archive
  - Upgrading phpunit/phpunit (9.5.10 => 9.5.14): Extracting archive
[...]
$ phpunit
PHPUnit 9.5.10 by Sebastian Bergmann and contributors.

No tests executed!

Generating code coverage report in HTML format ... $nonCommentLinesOfCode must not be negative
```

**Comment by sebastianbergmann** [comment]
It appears that you have different installations of PHPUnit mixed up.

For instance, you may have used Composer to install PHPUnit and have configured the autoloader generated by Composer as PHPUnit's bootstrap script but then you invoke PHPUnit using an executable other than `vendor/bin/phpunit`, for example.

`$ phpunit` implies that you are invoking PHPUnit from your `$PATH`, not from `./vendor/bin/phpunit` where you upgraded to phpunit/php-code-coverage 9.2.11 and phpunit/phpunit 9.5.14. `phpunit` also prints `PHPUnit 9.5.10` as version information.
