### ISSUE TITLE
syntax error, unexpected '}', expecting ';' on coverage-text

### ISSUE THREAD

**Issue by danielzzz** [sebastianbergmann/php-code-coverage#886]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.9
| PHP version         | 7.4.25
| Installation Method | Composer 
#### Summary

Syntax error on coverage-text

#### Current behavior

I am getting a syntax error when trying to get code coverage

#### How to reproduce
```
php vendor/bin/phpunit --coverage-text
PHPUnit 9.5.9 by Sebastian Bergmann and contributors.

..................                                                18 / 18 (100%)

Time: 00:03.835, Memory: 60.50 MB

OK (18 tests, 30 assertions)
syntax error, unexpected '}', expecting ';'
```

#### Expected behavior

no error, show coverage

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by sebastianbergmann** [comment]
No feedback, closing.
