### ISSUE TITLE
CodeCoverage depends on autoload order

### ISSUE THREAD

**Issue by Slamdunk** [sebastianbergmann/php-code-coverage#889]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 9.2.10
| PHP version               | 8.1.2
| Driver                    | Tested on both PCOV & Xdebug
| Xdebug version  | 3.1.2
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version | 9.5.13

Hi, currently CodeCoverage depends on code execution order.
I created a self contained repo that shows this behavior in https://github.com/Slamdunk/phpunit_codecoverage_bug#readme

Basically, given the following code:

```php
/* 1 */ class A
/* 2 */ {
/* 3 */     public function inArray(): bool
/* 4 */     {
/* 5 */         return \in_array(1, [
/* 6 */             AType::OPT,
/* 7 */         ], true);
/* 8 */     }
/* 9 */ }
```

1. lines 6 and 7 are **not** considered `LOC` if `AType` was already loaded and parsed before the `A` is used in the test
2. otherwise if `AType` is unknown to PHP during `inArray` call, lines 6 and 7 **are** considered `LOC`.

This messes CodeCoverage merging in context like ParaTest where test execution is isolated but not deterministic.

Merging two CC reports coming from different tests run in different processes can result in something like this:

![image](https://user-images.githubusercontent.com/152236/152554933-1380932c-f27a-4e77-99c3-d473cbcb620d.png)

Which doesn't make much sense

I don't know if this library can do much about this, maybe @krakjoe and @derickr could help

**Comment by dvdoug** [comment]
Can you try changing `processUncoveredFiles="true"` to `processUncoveredFiles="false"` and see if that helps?

**Comment by dvdoug** [comment]
Noting that it's class constants involved here which form part of to class definition , I'm thinking for Xdebug, this relates to/is another example of https://bugs.xdebug.org/view.php?id=1798 which affects `extends` and `implements`

**Comment by sebastianbergmann** [comment]
CC @krakjoe @derickr

**Comment by Slamdunk** [comment]
> Can you try changing `processUncoveredFiles="true"` to `processUncoveredFiles="false"` and see if that helps?

This has no effect on the underlying issue

> Noting that it's class constants involved here which form part of the class definition, I'm thinking that for Xdebug this might relate to/be another example of https://bugs.xdebug.org/view.php?id=1798 which affects `extends` and `implements`?

That's likely a similar issue: the solution I proposed in https://github.com/sebastianbergmann/php-code-coverage/pull/892 should also cover your https://github.com/sebastianbergmann/php-code-coverage/pull/775 indeed

**Comment by Slamdunk** [comment]
With the merge of #892, IIRC, the todo list now is:

1. Unify `ParsingCoveredFileAnalyser` and `ParsingUncoveredFileAnalyser`
2. Add memory level cache, both to speed things and *and* address Windows filesystem issues

**Comment by sebastianbergmann** [comment]
Agreed. Do you want to work on this, Filippo? Otherwise I'll try to work on this over the weekend.

**Comment by Slamdunk** [comment]
As soon as I'm able to code something, I'll open a PR *on draft*: if you don't see any it means I haven't started it yet so you can take that chance

**Comment by sebastianbergmann** [comment]
Cheers!

**Comment by sebastianbergmann** [comment]
@Slamdunk I just pushed 569819597e8a5b48dc392c62480173106e3a7905 to the `refactor-static-analysis` branch. It should work, but one test currently fails.

**Comment by sebastianbergmann** [comment]
Should be taken care of in 115a62bef64bb71788888f4b6ffccfbe2fb6b263.

**Comment by sebastianbergmann** [comment]
@Slamdunk I have pushed a67e7750d141beb07560b4ada3ade7542b23585c to `9.2` and will merge it to `master` ASAP.

**Comment by Slamdunk** [comment]
With your pushes and https://github.com/sebastianbergmann/php-code-coverage/pull/893 merged, I think this can be closed now.

Once released, I guess other `ExecutableLinesFindingVisitor` missing cases will emerge from userland code, but I like that we now have much more control over the reliability and determinability of what is and what isn't a Line of Code.

**Comment by mvorisek** [comment]
in
```
PHP 7.4.19 (cli) (built: May  4 2021 14:24:16) ( NTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.19, Copyright (c), by Zend Technologies
    with Xdebug v3.0.4, Copyright (c) 2002-2021, by Derick Rethans
```
and test script:
```
<?php

$file = realpath(__DIR__ . '/code.php');

xdebug_start_code_coverage(XDEBUG_CC_UNUSED);
require $file;
print_r(xdebug_get_code_coverage()[$file]);
```
and `code.php`:
```
<?php

class AType {
    const OPT = 5;
}

class Foo
{
    public function xxx(): string
    {
        $v3
            =
            AType::OPT
            . ''
        ;

        return 'y';
    }
}

var_dump((new Foo())->xxx());
```
(if file is ended with one or more NL, an extra/last line is reported)
I get:
```
string(1) "y"
Array
(
    [14] => 1
    [17] => 1
    [18] => -1
    [21] => 1
)
```

but if I change the `''` in concat to `'u'` I get:
```
string(1) "y"
Array
(
    [13] => 1
    [14] => 1
    [17] => 1
    [21] => 1
)
```

if I change then (after the previous change) the `return 'y';` to `return $v3` I get:
```
string(2) "5u"
Array
(
    [14] => 1
    [17] => 1
    [18] => -1
    [21] => 1
)
```

NOTICE THE COVERAGE IS UNSTABLE: sometimes I get if `[18] => -1`, sometimes `[18] => 1`, for example when I change `'u'` quickly to `'uu'` and run test script quickly again I get:
```
string(3) "5uu"
Array
(
    [14] => 1
    [17] => 1
    [18] => -1
    [21] => 1
)
```

but after a short time I get:

```
string(3) "5uu"
Array
(
    [13] => 1
    [14] => 1
    [17] => 1
    [21] => 1
)
```

(which seems to be stable then, at least for several consequent runs)

---

and I confirm the reported problem, when I move the `AType` class declaration to bottom like:
```
<?php

class Foo
{
    public function xxx(): string
    {
        $v3
            =
            AType::OPT
            . 'u'
        ;

        return $v3;
    }
}

class AType {
    const OPT = 5;
}

var_dump((new Foo())->xxx());
```
I get:
```
string(2) "5u"
Array
(
    [9] => 1
    [10] => 1
    [13] => 1
    [14] => -1
    [21] => 1
)
```
and next run I get:
```
string(2) "5u"
Array
(
    [9] => 1
    [10] => 1
    [13] => 1
    [21] => 1
)
```

**Comment by Slamdunk** [comment]
You can easily get the result on your own with the PHP Docker images, so you can speed this process up.
Btw, here are the result for 1, 2, 3 and 6, where the *before*s are your output, and the *after*s are mine with PHP 8.1:

:one: 
```diff
 string(1) "y"
 Array
 (
-    [14] => 1
+    [11] => 1
     [17] => 1
     [18] => -1
     [21] => 1
+    [22] => 1
 )
```
:two: 
```diff
 string(1) "y"
 Array
 (
-    [13] => 1
-    [14] => 1
+    [11] => 1
     [17] => 1
+    [18] => -1
     [21] => 1
+    [22] => 1
 )
```
:three: 
```diff
 string(2) "5u"
 Array
 (
-    [14] => 1
+    [11] => 1
     [17] => 1
     [18] => -1
     [21] => 1
+    [22] => 1
 )
```
:six: 
```diff
 string(2) "5u"
 Array
 (
+    [7] => 1
     [9] => 1
     [10] => 1
     [13] => 1
     [14] => -1
     [21] => 1
+    [22] => 1
 )
```

**Comment by mvorisek** [comment]
another "unstable" coverage output: https://github.com/sebastianbergmann/php-code-coverage/issues/774
