### ISSUE TITLE
declare(strict_types=1) line in interfaces and enum cases are being marked as uncovered lines of code

### ISSUE THREAD

**Issue by davidbyoung** [sebastianbergmann/php-code-coverage#897]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 9.2.11
| PHP version               | 8.1.2
| Driver                    | Xdebug
| Xdebug version (if used)  | 3.1.2
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 9.5.14

I have tried for several hours to create a simple, self-contained example of what is broken, but am really struggling.  When I run with `php-code-coverage` version `9.2.10`, everything works fine and I get 100% test coverage in my monorepo.  However, when updating to `9.2.11`, I am getting lines like `declare(strict_types=1);` and enum cases being marked as uncovered for a few interfaces and enums.

Because I am having a hard time reproducing, I thought I'd at least share links to some coverage difference examples.  For reference, the only difference in the following is what version of `php-code-coverage` I'm running:

* [9.2.10](https://coveralls.io/builds/46714327/source?filename=src%2FConsole%2Fsrc%2FInput%2FArgumentType.php#L11)
* [9.2.11](https://coveralls.io/builds/46714332/source?filename=src%2FConsole%2Fsrc%2FInput%2FArgumentType.php#L11)

[Here is my PhpUnit config](https://github.com/aphiria/aphiria/blob/b9c32a14567eb205cdc8c8f2b59c012a34e35c88/phpunit.xml.dist).  If there is any other useful info I can give you, let me know and I'll be glad to assist.  I'll keep trying to reproduce this with a simple example, but copy-pasting the broken interfaces and enums into a new, empty project doesn't repro the issue for some reason.

**Comment by sebastianbergmann** [comment]
CC @Slamdunk
