### ISSUE TITLE
unclear error source: Generating code coverage report in Clover XML format ... Call to a member function getModelInstance() on null

### ISSUE THREAD

**Issue by Flyingmana** [sebastianbergmann/php-code-coverage#902]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 9.2.11
| PHP version               | 7.4.3
| Driver                    | pcov (channel://pecl.php.net/pcov-1.0.11)
| Xdebug version (if used)  | x.y.z
| Installation Method       | Composer 
| Usage Method              | PHPUnit 
| PHPUnit version (if used) | 9.5.0

mostly see https://github.com/sebastianbergmann/php-code-coverage/issues/862 (great timing 😅)
not really sure, where the error comes from, or what is causing it, as I only have a single very simple test, so I guess it runs something else from the code when generating the coverage.

I was able to reproduce it local with `./vendor/bin/phpunit --configuration ./dev/phpunit.xml.dist --testsuite=Unit -vvv --debug`
which did output
```
$ ./vendor/bin/phpunit --configuration ./dev/phpunit.xml.dist --testsuite=Unit -vvv --debug
PHPUnit 9.5.0 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.4.3 with PCOV 1.0.11
Configuration: ./dev/phpunit.xml.dist

Test 'OpenMage\Tests\Unit\Base\ClassLoadingTest::testClassExists' started
Test 'OpenMage\Tests\Unit\Base\ClassLoadingTest::testClassExists' ended
Test 'OpenMage\Tests\Unit\Base\ClassLoadingTest::testClassDoesNotExists' started
Test 'OpenMage\Tests\Unit\Base\ClassLoadingTest::testClassDoesNotExists' ended


Time: 00:26.517, Memory: 16.00 MB

OK (2 tests, 3 assertions)

Generating code coverage report in Clover XML format ... Call to a member function getModelInstance() on null
```

you can also see it for this commit: https://github.com/Flyingmana/magento-lts/commit/209b27cab987a72aa710cb673f7f2e112c8741c2
in a github action: https://github.com/Flyingmana/magento-lts/runs/5281111827?check_suite_focus=true

in the previous run I also got
```
OK (2 tests, 3 assertions)

PHP Fatal error:  Declaration of Mage_Admin_Model_Acl_Assert_Ip::assert(Mage_Admin_Model_Acl $acl, ?Mage_Admin_Model_Acl_Role $role = NULL, ?Mage_Admin_Model_Acl_Resource $resource = NULL, $privilege = NULL) must be compatible with Zend_Acl_Assert_Interface::assert(Zend_Acl $acl, ?Zend_Acl_Role_Interface $role = NULL, ?Zend_Acl_Resource_Interface $resource = NULL, $privilege = NULL) in /home/runner/work/magento-lts/magento-lts/app/code/core/Mage/Admin/Model/Acl/Assert/Ip.php on line 46
Generating code coverage report in Clover XML format ... 
```
Which is likely unrelated to my current error, but makes me wonder if it happens as part of the same functionality, as it also only happened when code coverage was generated.

**Comment by Flyingmana** [comment]
I was at least able to pinpoint it to the setting `processUncoveredFiles="true"` which makes sense for this error.
But getting somehow output about which file this triggered (how about a trace?) or at least some --debug output which lists files before they are processed, like it exists for Test started/ended

**Comment by sebastianbergmann** [comment]
Unrelated: Why do you use PHPUnit 9.5.0? There are so many bugfixes in PHPUnit 9.5.14.

**Comment by sebastianbergmann** [comment]
In php-code-coverage 9, we still [include](https://github.com/sebastianbergmann/php-code-coverage/blob/9.2.11/src/CodeCoverage.php#L547) sourcecode files that are on the code coverage include list but that have not been covered by a test. Since 2da4cf5ad8c78e70e3c14077681aa7a678b91b4e, we no longer do this. However, this change has not made it into a release yet. Until then, you need to configure `processUncoveredFiles="false"`, which is the [default](https://github.com/sebastianbergmann/phpunit/blob/9.5/phpunit.xsd#L35).
