### ISSUE TITLE
Line with only "return [" is not recognized as executable

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/php-code-coverage#907]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 9.2.14
| PHP version               | 8.1.3
| Driver                    | PCOV
| PCOV version (if used)  | 1.0.11
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 9.5.16

![grafik](https://user-images.githubusercontent.com/25218/156604560-1584438e-e366-4470-9009-f80b790ac8eb.png)

#### `Example.php`
```php
<?php declare(strict_types=1);

namespace example;

final class Example
{
    public function one(): array
    {
        return [
            '...',
        ];
    }

    public function two(): array
    {
        return ['...',
        ];
    }


    public function three(): array
    {
        return ['...',];
    }
}
```
#### `ExampleTest.php`
```php
<?php declare(strict_types=1);

namespace example;

use PHPUnit\Framework\TestCase;

/**
 * @covers \example\Example
 */
final class ExampleTest extends TestCase
{
    public function testOne(): void
    {
        $this->assertSame(['...'], (new Example)->one());
    }
}
```

**Comment by Slamdunk** [comment]
Yes I have: xDebug & PCOV consider `'...'` the LoC, while our visitor only watch for the `return` statement.

I can fix this, but not within days

**Comment by sebastianbergmann** [comment]
Thanks! Take your time.

**Comment by Slamdunk** [comment]
This is what xDebug reports:

```php
<?php

class Foo
{
    public function one(): array
    {
        return [
            '...',                // <---
            '...',
        ];
    }

    public function two(): array
    {
        return ['...',            // <---
            '...',
        ];
    }

    public function three(): array
    {
        return ['...',];          // <---
    }

    public function four(): bool
    {
        return in_array('...', [  // <---
            '...',
            '...',
        ], true);
    }
}
```

The fourth example changes its predictability. Let's see if I can get everything working
