### ISSUE TITLE
0th level coverage statistics and proportional coverage bars

### ISSUE THREAD

**Issue by idontusenumbers** [sebastianbergmann/php-code-coverage#914]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 9.2.15
| PHP version               | 8.1.5
| Driver                    | PCOV
| PCOV version (if used)    | 1.0.11
| Installation Method       | PHPUnit PHAR
| Usage Method              | https://github.com/sebastianbergmann/phpcov .phar

Two things I'd love to see in the coverage reports:
* ~~An overall lines-covered statistic for the current directory. Currently the report shows for directories one level deeper, but not the current level, leaving out 0th level (as far as I can tell).~~ (I see now this is at the top of the list; might be worth making it easier to find. I looked for it specifically and missed it about 10 times.)
* Coverage percentage bars proportional to largest directory/file in the current directory. For example, the coverage bar for a 5 line file should not be as large as a directory that has 2000 lines of code within it. Maybe similar to JaCoCo:
![image](https://user-images.githubusercontent.com/1175031/167069066-eab78024-c2a6-41d1-99fc-255fc056b0fd.png)

**Comment by sebastianbergmann** [comment]
I do not think that this would be useful, sorry.

**Comment by idontusenumbers** [comment]
The reports already have progress bars so it seems you already feel visual indicators have some value. I'm curious why you don't see the value in the weighted ones. At least two people do, me and whomever created them for JaCoCo =)
