### ISSUE TITLE
CodeUnitFindingVisitor::unionOrIntersectionAsString() does not handle PHP 8 unions types

### ISSUE THREAD

**Issue by AymDev** [sebastianbergmann/php-code-coverage#917]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 9.2.15
| PHP version               | 8.0.12
| Driver                    | Xdebug
| Xdebug version (if used)  | 3.1.1
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 9.5.20

I have a method with a union type for its argument:
```php
public function getFilename(Invoice|Quote $document): string
```

In CI I run my test suite with coverage (a Symfony project using the PHPUnit bridge):
```shell
XDEBUG_MODE=coverage ./bin/phpunit --coverage-text
```
And I get the following error printed:
>SebastianBergmann\CodeCoverage\StaticAnalysis\CodeUnitFindingVisitor::unionOrIntersectionAsString(): Argument #1 ($type) must be of type PhpParser\Node\ComplexType, PhpParser\Node\UnionType given, called in /srv/app/bin/.phpunit/phpunit-9.5.20-0/vendor/phpunit/php-code-coverage/src/StaticAnalysis/CodeUnitFindingVisitor.php on line 183

I don't really know what's hapenning here, I switched to PHPDoc as a temporary workaround and it works:
```p
/**
 * @param Invoice|Quote $document
 */
public function getFilename($document): string
```

**Comment by sebastianbergmann** [comment]
I cannot reproduce this. Could it be that, for some reason, you do not have PHP-Parser >= 4.13.0 (which introduced `PhpParser\Node\ComplexType`)?

**Comment by AymDev** [comment]
Hi Sebastian,

That was it, I did not realize that it was related to **nikic/php-parser**. It works now using version **4.14**.
Sorry for the inconvenience. Have a nice day and thanks for your great work.
