### ISSUE TITLE
Missing code coverage on objects within @dataProvider methods

### ISSUE THREAD

**Issue by pionl** [sebastianbergmann/php-code-coverage#920]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 9.2.15
| PHP version               | 8.1.7
| Driver                    | PCOV  (same result in XDebug - Github actions
| PCOV version (if used)    |1.0.11
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 9.5.21

Hi,

I have an issue while collecting code coverage only when objects are constructed in `@dataProvider` method.

<img width="998" alt="Snímek obrazovky 2022-06-29 v 13 52 20" src="https://user-images.githubusercontent.com/1878831/176430453-e958556c-d72a-4586-b243-8c86f3da2055.png">

The code coverage will collect code coverage in test methods.

I'm constructing objects within the dataProvider to allow different "checks" based on "closure" I'm passing to the object.

Is this desired functionality?

## Verification

Repository: https://github.com/wrk-flow/php-get-typed-value 

```bash
vendor/bin/phpunit --coverage-text
```

If I add new test to `ArrayTransformerTest` file then the code coverage for ArrayTransformer is collected.

```php
    public function testCoverage(): void
    {
        $test = new ArrayTransformer(closure: fn () => []);
        $this->assertNotNull($test);
    }
```php

**Comment by sebastianbergmann** [comment]
This is intentional: a data provider method is not considered to be part of the test, as such it does not contribute to code coverage.

**Comment by pionl** [comment]
thank you for the info, then I need to tweak the tests.

**Comment by mvorisek** [comment]
Is it possible to exclude the data providers from coverage completely?

Currently, when coverage is computed for a test itself, the data providers are shown as uncovered:
![image](https://user-images.githubusercontent.com/2228672/177552024-251ad051-7cc5-4c82-8beb-3e6a88995c81.png)
