### ISSUE TITLE
`@doesNotPerformAssertions` removes coverage

### ISSUE THREAD

**Issue by mvorisek** [sebastianbergmann/php-code-coverage#921]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 9.2.15
| PHP version               | 8.0.20
| Driver                    | Xdebug
| Xdebug version  | 3.1.5
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 9.5.21

`@doesNotPerformAssertions` [1] annotation silences risky warning when no assertion is performed, but it does not skip the test.

Currently, it removes the test coverage. But as the test is run, coverage must be collected as if this annotation was not present.

![image](https://user-images.githubusercontent.com/2228672/177578199-66d06888-f20a-41e6-aa93-8cd53abfe8df.png)

[1] https://phpunit.readthedocs.io/en/9.5/annotations.html#doesnotperformassertions

**Comment by sebastianbergmann** [comment]
This is intentional: a test that does not perform assertions should not contribute to code coverage.

**Comment by mvorisek** [comment]
Why is such test present then?

We have some tests annotated `@doesNotPerformAssertions` that do not perform any assertions, but tests if some usecase pass /wo any exception.

**Comment by mvorisek** [comment]
The issue is not the annotation. The problem present when a test does not perform any assertion.

This example does collect a coverage:

```
    /**
     * @doesNotPerformAssertions
     */
    public function testPassively(): void
    {
        $m = new FactoryDiMock2();
        $m->setDefaults([], true);

        $this->assertTrue(true);
    }
```

but this one doesn't:

```
    /**
     * @doesNotPerformAssertions
     */
    public function testPassively(): void
    {
        $m = new FactoryDiMock2();
        $m->setDefaults([], true);
    }
```

Notice, the only difference is the `$this->assertTrue(true);` line is present/not present.

If no assertion is made is reported by phpunit correctly and such warning should not affect the coverage. Coverage is either enabled or disabled, but it should not depend on the test result.
