### ISSUE TITLE
`TestCase::markTestIncomplete` call is removed from coverage

### ISSUE THREAD

**Issue by mvorisek** [sebastianbergmann/php-code-coverage#922]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 9.2.15
| PHP version               | 8.0.20
| Driver                    | Xdebug
| Xdebug version  | 3.1.5
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 9.5.21

We collect coverage for tests too to detect dead code.

For some reasons, `$this->markTestIncomplete()` line [1]  (and other throwing calls like `$this->fail()`) are excluded from the coverage, althrough the lines are reached.

I would expect the coverage to be collected for these lines. (and no line after, but that works correctly)

It seems the coverage collection is stopped too early, ie. before the coverage for the throwing call is stored.

[1] example https://app.codecov.io/gh/atk4/data/compare/1017/tree/tests/Util/DeepCopyTest.php#D1L251

**Comment by sebastianbergmann** [comment]
Collecting code coverage for test code is a use case that is not supported.

**Comment by mvorisek** [comment]
Maybe not completely supported, but it works for the standard test code.

Do you know why does this happend and if it can be fixed easily and where? I might look into the fix. Thank you.

**Comment by mvorisek** [comment]
The following code fixes this issue from the developer side for incomplete/skipped test results:
```
use PHPUnit\Runner\BaseTestRunner;
use PHPUnit\Util\Test as TestUtil;
use SebastianBergmann\CodeCoverage\CodeCoverage;


    protected function tearDown(): void
    {
        parent::tearDown();

        // fix coverage for skipped/incomplete tests
        // https://github.com/sebastianbergmann/phpunit/blob/9.5.21/src/Framework/TestResult.php#L830
        // https://github.com/sebastianbergmann/phpunit/blob/9.5.21/src/Framework/TestResult.php#L857
        if (in_array($this->getStatus(), [BaseTestRunner::STATUS_SKIPPED, BaseTestRunner::STATUS_INCOMPLETE], true)) {
            $coverage = $this->getTestResultObject()->getCodeCoverage();
            if ($coverage !== null) {
                $coverageId = \Closure::bind(fn () => $coverage->currentId, null, CodeCoverage::class)();
                if ($coverageId !== null) { // @phpstan-ignore-line https://github.com/sebastianbergmann/php-code-coverage/pull/923
                    $linesToBeCovered = TestUtil::getLinesToBeCovered(static::class, $this->getName(false));
                    $linesToBeUsed = TestUtil::getLinesToBeUsed(static::class, $this->getName(false));
                    $coverage->stop(true, $linesToBeCovered, $linesToBeUsed);
                    $coverage->start($coverageId);
                }
            }
        }
```
