### ISSUE TITLE
File view nearly impossible to work with due to the layout

### ISSUE THREAD

**Issue by CJDennis** [sebastianbergmann/php-code-coverage#924]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 7.0.15
| PHP version               | 7.4.24
| Driver                    | PCOV
| PCOV version    | 7.4.13.0
| Installation Method       | Composer
| Usage Method              | Codeception 4.1 / 4.2

I'm going to focus on a class called SmsService to illustrate this issue.

![image](https://user-images.githubusercontent.com/1551236/177888619-2ff8d3d0-88cc-4a3e-bc7d-4692e611f4b5.png)

As you can see, it is 69.57% covered (which is coloured yellow on my setup) with 32 out of 46 lines covered.

![image](https://user-images.githubusercontent.com/1551236/177888746-a847ef02-90c7-4536-acce-450ced6720ab.png)

However, clicking on the class changes its colour to red, and now no stats are easily available. The colour should remain yellow (on my setup) and the number of lines covered should appear next to each method name. I should not have to look at the other side of the screen to try and work out what the coverage is.

![image](https://user-images.githubusercontent.com/1551236/177888922-b113e63b-b397-409d-a7a8-29acb1fa0199.png)

This is only a small class. Imagine doing this with a class with 20 or more methods and trying to line up each class with the number of lines covered per method. Maybe you have widescreen eyes capable of reading both sides of the screen at the same time, but I only have regular aspect ratio eyes and I can only read one side of the screen at a time. I am forced to look at a different part of the screen if I want to read it. I've asked doctors if they can perform an update on my human physiology to make it compatible with your software but they say it can't be done with today's technology.

The class totals are completely useless on the left. If I have a 1000 line class with only one line not covered, guess what? The entire class is not counted as covered (0.00%) and will always be red! It's currently impossible for a class to appear yellow, no matter how you have your settings. In terms of usefulness, lines are 100%, methods are 60%, and classes are 20%. I need the most useful information first: "method, 100%, 60%, 20%", not "method, 20%, 60%, 100%".

Please move the lines to the left, and classes to the right to be consistent with the rest of the project.

**Comment by sebastianbergmann** [comment]
This has been implemented in https://github.com/sebastianbergmann/php-code-coverage/pull/900 for newer versions.
