### ISSUE TITLE
File view has wrong colouring for the first column

### ISSUE THREAD

**Issue by CJDennis** [sebastianbergmann/php-code-coverage#926]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 9.2.15
| PHP version               | 7.4.24
| Driver                    | PCOV
| PCOV version (if used)    | 7.4.13
| Installation Method       | Composer
| Usage Method              | Codeception

The file coverage report still has the method names coloured the same as what is now the last column: Classes and Traits. It should be coloured the same as the second column: Lines.

![image](https://user-images.githubusercontent.com/1551236/185724951-cfa11787-32c7-4924-b9f2-5ce325a43fc2.png)

![image](https://user-images.githubusercontent.com/1551236/185724962-79c3a484-95c0-44ef-82fd-b35ecace9593.png)

In the example screenshot, `medium_method` should be coloured yellow, just like "Lines" is. This will make "file view" fully consistent with "directory view" where the first column can be any colour, not just red or green. Note that "Total" and the file name / class name lines are currently inconsistent too, being yellow in the directory view and red in the file view. "Total" can't be both red and yellow at the same time!

P.S. The last column (Classes and Traits) possibly shouldn't have any colour for method lines since methods aren't classes or traits. I can make that a separate issue though.

**Comment by sebastianbergmann** [comment]
I am sorry, but I do not understand what you want to report.

**Comment by sebastianbergmann** [comment]
@hemberger Is this related to #900? Thanks!

**Comment by hemberger** [comment]
I'm happy to take a look and will submit a PR if I can corroborate the issue being reported.

**Comment by CJDennis** [comment]
@sebastianbergmann @hemberger I've updated the issue with screenshots now.

**Comment by sebastianbergmann** [comment]
> @sebastianbergmann @hemberger I've updated the issue with screenshots now.

Thank you!
