### ISSUE TITLE
Coverage not working on closures in PHPDBG

### ISSUE THREAD

**Issue by Ocramius** [sebastianbergmann/php-code-coverage#945]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 9.2.17
| PHP version               | 8.1.10
| Driver                    | PHPDBG
| PCOV version (if used)    | 1.0.11
| Xdebug version (if used)  | 
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 9.5.25

As investigated in https://github.com/infection/infection/issues/1736, coverage for closures doesn't seem to be picked up correctly, when using PHPDBG.

Specifically, `PCOV` works as expected:

![Selection_1052](https://user-images.githubusercontent.com/154256/195045584-0162f874-bdf3-4f10-a770-a8683debdba2.png)

A coverage report done with `phpdbg -qrr` will instead produce partial coverage:

![Selection_1051](https://user-images.githubusercontent.com/154256/195045738-6a8925ee-f87e-44ed-8dbb-4c393b0926f0.png)

## Reproducible example

```php
<?php

declare(strict_types=1);

final class Foo
{
    /** @return callable(): int */
    function make(): callable
    {
        return static function (): int {
            return 1;
        };
    }
}
```

```php
<?php

declare(strict_types=1);

require_once __DIR__ . '/../../src/Foo.php';

/** @covers Foo */
final class FooTest extends \PHPUnit\Framework\TestCase
{
    function testClosure(): void
    {
        self::assertSame(1, (new Foo())->make()());
    }
}
```

### PHPDBG output

```
❯ phpdbg -qrr ./vendor/bin/phpunit --coverage-html=coverage --filter=Foo
PHPUnit 9.5.25 #StandWithUkraine

.                                                                   1 / 1 (100%)

Time: 00:00.140, Memory: 50.00 MB

OK (1 test, 1 assertion)

Generating code coverage report in HTML format ... done [00:00.812]
```

![Selection_1053](https://user-images.githubusercontent.com/154256/195046392-ce8d075c-a976-49d5-9685-b567795bfa19.png)

### PCOV output

```
❯ ./vendor/bin/phpunit --coverage-html=coverage --filter=Foo
PHPUnit 9.5.25 #StandWithUkraine

.                                                                   1 / 1 (100%)

Time: 00:00.053, Memory: 40.00 MB

OK (1 test, 1 assertion)

Generating code coverage report in HTML format ... done [00:00.708]
```

![Selection_1054](https://user-images.githubusercontent.com/154256/195046635-12c6c313-3977-471a-a0aa-c6b838818505.png)

## PHPDBG + PCOV = :boom: 

Note: running `phpdbg` with `pcov` installed will lead to a segfault:

```
❯ phpdbg -qrr ./vendor/bin/phpunit --coverage-html=coverage --filter=Foo
PHPUnit 9.5.25 #StandWithUkraine

Segmentation fault (core dumped)
```

**Comment by Ocramius** [comment]
Note: I reported this here, because I don't know if the problem is in `phpdbg` or in `phpunit/php-code-coverage`.

I don't really know the underlying protocol, so any help is welcome :+1:

**Comment by Ocramius** [comment]
Makes sense: I used phpdbg because it comes with php-src, and I didn't want to add more dependencies to my stack (in general), but I can live with this decision, and adapt to it long-term :+1:

**Comment by sebastianbergmann** [comment]
Removed support for PHPDBG in c304be7d8aa00a71cf8fe763a4b92e14d3f67f4d for php-code-coverage v10 (to be released alongside PHPUnit 10 in February 2023).

**Comment by Ocramius** [comment]
That was quick and decisive :muscle: 

I'll make sure to upgrade my downstream projects before PHPUnit 10 hits us :)
