### ISSUE TITLE
Method with "return with multiline constant expr only" is not generating any coverage lines

### ISSUE THREAD

**Issue by mvorisek** [sebastianbergmann/php-code-coverage#946]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 9.2.17 / latest
| PHP version               | 8.0.24
| Driver                    | Xdebug
| Xdebug version  | 3.2.0RC1
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version | 9.5.25

code:

https://github.com/atk4/data/blob/0c6bce5c2ac53589934b02bc0832a4753c283f15/src/Persistence/Sql/Oracle/PlatformTrait.php#L104-L109

is not generating any coverage line:

```
...
    <file name="/__w/data/data/src/Persistence/Sql/Oracle/PlatformTrait.php">
      <class name="Atk4\Data\Persistence\Sql\Oracle\PlatformTrait" namespace="global">
        <metrics complexity="7" methods="5" coveredmethods="5" conditionals="0" coveredconditionals="0" statements="24" coveredstatements="24" elements="29" coveredelements="29"/>
      </class>
      <line num="12" type="method" name="getVarcharTypeDeclarationSQL" visibility="public" complexity="1" crap="1" count="209"/>
      <line num="14" type="stmt" count="209"/>
      ...
      <line num="74" type="stmt" count="231"/>
      <line num="94" type="stmt" count="231"/>
      <line num="95" type="stmt" count="231"/>
      <line num="96" type="stmt" count="231"/>
      <line num="99" type="stmt" count="231"/>
      <line num="101" type="stmt" count="231"/>
      <metrics loc="121" ncloc="101" classes="1" methods="5" coveredmethods="5" conditionals="0" coveredconditionals="0" statements="24" coveredstatements="24" elements="29" coveredelements="29"/>
    </file>
...
```

![image](https://user-images.githubusercontent.com/2228672/196032561-e4b11815-cb89-4475-a465-b04e251cb594.png)

I would expect at least one coverage line for the `getListDatabasesSQL` method to be able to tell if called or not

**Comment by mvorisek** [comment]
Hi @Slamdunk, do you think this can be fixed?

**Comment by Slamdunk** [comment]
It definitively should

**Comment by mvorisek** [comment]
here is minimalistic code to reproduce:

```
class Cl
{
    public function getSql(): string
    {
        return 'select 1 from' . ' from dual';
    }
}
```

generates a coverage line, but

```
class Cl
{
    public function getSql(): string
    {
        return 'select 1 from'
            . ' from dual';
    }
}
```

does not, notice same AST, for some reasons, no coverage is generated if the the string is concat across multiple lines

**Comment by sebastianbergmann** [comment]
I was able to reproduce this.
#### `src/C.php`
```php
<?php declare(strict_types=1);
final class C
{
    public function one(): string
    {
        return 'foo' . 'bar';
    }

    public function two(): string
    {
        return 'foo'
            . 'bar';
    }
}
```
#### `tests/CTest.php`
```php
<?php declare(strict_types=1);
use PHPUnit\Framework\TestCase;

/**
 * @covers C
 */
final class CTest extends TestCase
{
    public function testOne(): void
    {
        $this->assertSame('foobar', (new C)->one());
    }

    public function testTwo(): void
    {
        $this->assertSame('foobar', (new C)->two());
    }
}
```
#### Code Coverage Report
![grafik](https://user-images.githubusercontent.com/25218/197120628-6aed84cf-23c9-4356-b8dc-0261bfb9f86f.png)

**Comment by Slamdunk** [comment]
I'm going to look at this as soon as I can

**Comment by sebastianbergmann** [comment]
Once again: thank you so much, @Slamdunk!
