### ISSUE TITLE
Empty method does not generate any line/method coverage

### ISSUE THREAD

**Issue by mvorisek** [sebastianbergmann/php-code-coverage#954]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 9.2.18 / latest
| PHP version               | 8.0.24
| Driver                    | Xdebug
| Xdebug version  | 3.2.0RC1
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version | 9.5.25

code: https://github.com/atk4/ui/blob/02596615ea82131cd903d6095eec7fe53e541aef/src/Form/Control/DropdownCascade.php#L116-L119

is not generating any coverage line:

```
...
    <file name="/__w/ui/ui/src/Form/Control/DropdownCascade.php">
      <class name="Atk4\Ui\Form\Control\DropdownCascade" namespace="global">
        <metrics complexity="14" methods="5" coveredmethods="1" conditionals="0" coveredconditionals="0" statements="34" coveredstatements="19" elements="39" coveredelements="20"/>
      </class>
      ...
      <line num="103" type="method" name="getJsValues" visibility="private" complexity="3" crap="3.58" count="2"/>
      <line num="105" type="stmt" count="2"/>
      <line num="106" type="stmt" count="2"/>
      <line num="107" type="stmt" count="0"/>
      <line num="109" type="stmt" count="0"/>
      <line num="113" type="stmt" count="2"/>
      <line num="121" type="method" name="renderView" visibility="protected" complexity="1" crap="1" count="2"/>
      <line num="124" type="stmt" count="2"/>
      <line num="126" type="stmt" count="2"/>
      <metrics loc="129" ncloc="98" classes="1" methods="5" coveredmethods="1" conditionals="0" coveredconditionals="0" statements="34" coveredstatements="19" elements="39" coveredelements="20"/>
    </file>
...
```

![image](https://user-images.githubusercontent.com/2228672/199475435-dbe7a663-5dd6-4887-95ea-f2b32aabc98f.png)

I would expect at least one coverage line for the `htmlRenderValue` method to be able to tell if it was called or not

**Comment by mvorisek** [comment]
xdebug outputs coverage line for method's closing body bracket (line 119 in the example)

**Comment by Slamdunk** [comment]
Fixed in https://github.com/mvorisek/php-code-coverage/pull/2/commits/40b82a19021b79c976c2b9af8f1f6c99ff091807
