### ISSUE TITLE
Statement below class does not generate any coverage line

### ISSUE THREAD

**Issue by mvorisek** [sebastianbergmann/php-code-coverage#958]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 9.2.18, 9.2.19 / latest
| PHP version               | 8.0.24
| Driver                    | Xdebug
| Xdebug version  | 3.2.0RC1
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version | 9.5.25

code: https://github.com/atk4/data/blob/e091b675d32a17d839e918557f3e24ab6211b563/bootstrap-types.php#L49

```
<?xml version="1.0" encoding="UTF-8"?>
<coverage generated="1668794616">
  <project timestamp="1668794616">
...
    <file name="/__w/data/data/bootstrap-types.php">
      <class name="Atk4\Data\Types\Types" namespace="global">
        <metrics complexity="0" methods="0" coveredmethods="0" conditionals="0" coveredconditionals="0" statements="0" coveredstatements="0" elements="0" coveredelements="0"/>
      </class>
      <class name="Atk4\Data\Types\MoneyType" namespace="global">
        <metrics complexity="8" methods="5" coveredmethods="5" conditionals="0" coveredconditionals="0" statements="8" coveredstatements="8" elements="13" coveredelements="13"/>
      </class>
      <line num="17" type="method" name="getName" visibility="public" complexity="1" crap="1" count="12"/>
      <line num="19" type="stmt" count="12"/>
...
      <line num="43" type="method" name="requiresSQLCommentHint" visibility="public" complexity="1" crap="1" count="12"/>
      <line num="45" type="stmt" count="12"/>
      <metrics loc="50" ncloc="50" classes="1" methods="5" coveredmethods="5" conditionals="0" coveredconditionals="0" statements="8" coveredstatements="8" elements="13" coveredelements="13"/>
    </file>
...
```

![image](https://user-images.githubusercontent.com/2228672/202814053-26ad1def-240c-452f-956f-4af9f5280a72.png)

simple repro code:
```
<?php

class Foo
{
    public function x(): void
    {
        phpversion(); // must be covered (currently covered)
    }
}

phpversion(); // must be covered too (currently NOT covered)
```

does not generate any coverage line (in clover output)

when the statement is added into method body, the coverage is generated, but for some reasons, coverage for statement outside/below method does not - maybe related to clover only, not sure

**Comment by Slamdunk** [comment]
[`9.2.21`](https://github.com/sebastianbergmann/php-code-coverage/releases/tag/9.2.21) fixed this

**Comment by mvorisek** [comment]
How is that possible, what condition was missing before that release?

**Comment by mvorisek** [comment]
You mean by https://github.com/sebastianbergmann/php-code-coverage/pull/964? Why it was not covered before - what condition was missing - and is it tested now?

**Comment by Slamdunk** [comment]
> You mean by #964?

Yes

> Why it was not covered before - what condition was missing

Have no idea

> and is it tested now?

Yes, by:

1. https://github.com/sebastianbergmann/php-code-coverage/blob/9.2.21/tests/_files/source_for_branched_exec_lines.php#L12
2. https://github.com/sebastianbergmann/php-code-coverage/blob/9.2.21/tests/_files/source_for_branched_exec_lines.php#L387

**Comment by mvorisek** [comment]
retested with the latest version of this repo using https://github.com/atk4/data/commit/f59e169f33f7aa53587a76e0647efa0df5521fb9:

![image](https://user-images.githubusercontent.com/2228672/221412618-b185ddfb-2d10-4235-80cd-875db8a00730.png)

issue is still present

**Comment by Slamdunk** [comment]
I'll have a look on this next week

**Comment by Slamdunk** [comment]
As far as I can tell, no issue is present.

In the original post of this topic https://github.com/sebastianbergmann/php-code-coverage/issues/958#issue-1445802093 you reported that line `49` has not been marked as executable. `9.2.21` fixed that, and this issue should be closed.

https://github.com/sebastianbergmann/php-code-coverage/issues/958#issuecomment-1445359631 instead reports that lines `12` and `13` are not marked as covered. This has nothing to do with `sebastianbergmann/php-code-coverage`, which simply reports correctly that those two lines need to be tracked for code-coverage.
Code-coverage that is missing by your tests.

**Comment by mvorisek** [comment]
(original) l`49` is not different than the current `12`/`13`. The code is always included here: https://github.com/atk4/data/blob/f59e169f33f7aa53587a76e0647efa0df5521fb9/composer.json#L71, ie. definitely executed.

**Comment by Slamdunk** [comment]
> (original) l`49` is not different than the current `12`/`13`.

Of course they are the same, but the issue you are reporting is different.
`49` was white, so they were not considered as executable until `9.2.21`.
`12`/`13` are instead red, which means they *are* considered as executable.

> https://github.com/atk4/data/blob/f59e169f33f7aa53587a76e0647efa0df5521fb9/composer.json#L71, ie. definitely executed.

It doesn't surprise me at all that they are marked as red: composer autoloads `src/bootstrap-types.php` much earlier than any code-coverage is activated by PHPUnit

**Comment by sebastianbergmann** [comment]
I think we should stop worrying about code that is outside of classes and functions.

**Comment by mvorisek** [comment]
maybe in the future
