### ISSUE TITLE
New body font-size is way too big

### ISSUE THREAD

**Issue by LordSimal** [sebastianbergmann/php-code-coverage#960]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 9.2.19
| PHP version               | 8.1.10
| Driver                    | Xdebug
| Xdebug version  | 3.1.5
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version | 9.5.26

I just updated to the current latest version, regenerated the Code coverage page and was very confused why the text was so big.

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/9105243/202868188-a45a23d7-9d95-4fb8-9cda-3cafbe1a5b90.png">

Just compare the URL font-size compared to the rest of the text.

This especially is way to wasteful when looking at code lines

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/9105243/202868231-ae3683ed-9b24-4fdb-b86a-4573fb1453c2.png">

As you can see here without any zooming I can only see 18 lines of code.

Compared to the old (`front-size: 1em`) I am able to read 37 lines of code in 1 page.

What was the reason to change the default body font-size to 2em in [HERE](https://github.com/sebastianbergmann/php-code-coverage/commit/aa0971fe8c9de5423670c6cd5954f27b89274f2f)?

**Comment by gemal** [comment]
yes it's almost unusable now :(

**Comment by sebastianbergmann** [comment]
I am not a frontend developer, sorry. Setting `font-size` to `2em` in aa0971fe8c9de5423670c6cd5954f27b89274f2f was motivated by the fact that I wanted the code coverage report to be readable (for me) without having to zoom.

**Comment by LordSimal** [comment]
Thanks for the fix and the quick release 😄 

Regarding your problem:
Depending on your monitor size, resolution and the UI scaling setting in your OS the text can definitely be very small. I can understand that.
The proper solution to this problem would be to add a body font-size changer element (maybe at the top right) with `+` and `-` buttons. If you want I can provide a PR for that.

**Comment by sebastianbergmann** [comment]
> If you want I can provide a PR for that.

Yes, please.
