### ISSUE TITLE
Undefined method in 9.2.21

### ISSUE THREAD

**Issue by jaikdean** [sebastianbergmann/php-code-coverage#966]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 9.2.21
| PHP version               | 7.4.33
| Driver                    | PCOV
| PCOV version (if used)    | 1.0.11
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 9.5.27

After updating to 9.2.21, we receive the following error when running PHPUnit:

> Call to undefined method SebastianBergmann\CodeCoverage\RawCodeCoverageData::markExecutableLineByBranch()

This error is not present with 9.2.20.

Our PHPUnit coverage configuration is as follows:

```
    <coverage
        includeUncoveredFiles="true"
        processUncoveredFiles="true"
        pathCoverage="false"
        ignoreDeprecatedCodeUnits="true"
        disableCodeCoverageIgnore="true">
        <include>
            <directory suffix=".php">src</directory>
        </include>

        <report>
            <cobertura outputFile=".reports/cobertura-coverage.xml"/>
        </report>
    </coverage>
```

**Comment by sebastianbergmann** [comment]
@Slamdunk Can you have a look?

**Comment by sebastianbergmann** [comment]
The `SebastianBergmann\CodeCoverage\RawCodeCoverageData::markExecutableLineByBranch()` method exists. Could it be that you have a mixed-up installation where you updated only some (`CodeCoverage.php`, for instance) files but not others (`RawCodeCoverageData.php`, for instance)?

**Comment by jaikdean** [comment]
@sebastianbergmann I agree, it looks like it should be fine from the code. It's being installed and executed by [symfony/phpunit-bridge](https://github.com/symfony/phpunit-bridge) so there might be an issue there. I'll dig into it further to figure out what's going on.

**Comment by jaikdean** [comment]
It appears this was caused by using the `simple-phpunit` script from `symfony/phpunit-bridge` with PHPUnit installed in `vendor` as well as the bridge package's `bin/.phpunit` directory. I'm pulling the bridge package out of this project as it does more harm than good, and the test suite is now running correctly.

Apologies for the false bug report.

**Comment by crbanman** [comment]
We just ran into this on one of our projects just today. The issue appears to be that we had `phpunit/phpunit` as well as `symfony/phpunit-bridge` as dev dependencies.

Removing `phpunit/phpunit` from our dev dependencies fixed it.
