### ISSUE TITLE
CI fails for PHP 8.2 on Windows

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/php-code-coverage#972]
See

* https://github.com/sebastianbergmann/php-code-coverage/actions/runs/3755984100/jobs/6381555006
* https://github.com/sebastianbergmann/php-code-coverage/actions/runs/3755984100/jobs/6381555076

for example.

@localheinz @shivammathur Do you have any idea why PHP 8.2 on Windows has issues with PCOV and Xdebug? Thanks!

**Comment by shivammathur** [comment]
@sebastianbergmann 
Fixed in https://github.com/shivammathur/setup-php/commit/e51e662ef000d1712ee7fbd2c7a4ea56889f1483, I will create a release this weekend.

**Comment by sebastianbergmann** [comment]
Thank you so much, @shivammathur!
