### ISSUE TITLE
More executable lines of code counted with 9.2.21

### ISSUE THREAD

**Issue by oliworx** [sebastianbergmann/php-code-coverage#975]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 9.2.21
| PHP version               | 7.4.33
| Driver                    | PCOV
| PCOV version (if used)    | 1.0.6
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 9.5.26

I make code coverage reports for some larger projects every month, but suddenly thousends more LOC are reported and this totally breaks the statistics numbers.

Turns out now lines are counted as executable code wich where not counted before:

Old behaviour:
![image](https://user-images.githubusercontent.com/1712684/209411546-a39df6ad-cc0c-4fb9-bbf9-d69cf787d74a.png)

New behaviour:
![image](https://user-images.githubusercontent.com/1712684/209411632-99a159cb-3388-4e0f-bcf3-6a88afe36ca0.png)

It would be grat to have at least an option to bring back the old lines counting behaviour.

**Comment by sebastianbergmann** [comment]
CC @Slamdunk

**Comment by sebastianbergmann** [comment]
This is likely caused by the changes discussed in #959 and #964.

**Comment by Slamdunk** [comment]
This is by design

> It would be grat to have at least an option to bring back the old lines counting behaviour.

I'm sorry this is not possible, it would also bring back all the bugs the new solution fixes

**Comment by oliworx** [comment]
@Slamdunk This change of measure is a **breaking change** and should not happen in a patch version, you should release a new major version for this!  
The only job of this package is to measure something.  
How can we trust the result numbers, if suddenly the methods or definitions of the measurements are changed, out of nowhere?
Even if you think the new method is more correct, **you have to keep the measure consistent!**. 
Everything else is just unprofessional and unscientific.

**Comment by Slamdunk** [comment]
Yes the logic changed drastically, but it had to be done in the same major becase previous results were just wrong.
Keeping consistency over erroneous results has no value.

I can assure you consistency and determinism is the core goal of the new implementation, even though it makes no sense to me to trust a metric that can be easily tricked with refactoring and code formatting.
