### ISSUE TITLE
Coverage on sibling directory

### ISSUE THREAD

**Issue by YspMark** [sebastianbergmann/php-code-coverage#978]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 9.2.24
| PHP version               | 8.1.2
| Driver                    | PCOV
| PCOV version (if used)    | 1.0.11
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 9.5.28

We are using a code structure with some shared code in a sibling directory, shared across multiple app-projects. Both this App-project and the shared directory are covered with PHPunit tests that are located in their folders. These tests are included in the App-project phpunit.xml file since the project bootstrap is located there. Running the tests like this works well. The tests of both App and the Shared tests are run, however the code coverage on the Shared tests is not covered in the results.

```
~/Projects/phpunit-coverage-shared-tests/app$ ./vendor/bin/phpunit --coverage-html html
PHPUnit 9.5.28 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.1.2-1ubuntu2.10 with PCOV 1.0.11
Configuration: ~/Projects/phpunit-coverage-shared-tests/app/phpunit.xml
Random Seed:   1674726494

..                                                                  2 / 2 (100%)

Time: 00:00.017, Memory: 10.00 MB

OK (2 tests, 2 assertions)

Generating code coverage report in HTML format ... done [00:00.010]
```

![image](https://user-images.githubusercontent.com/55830693/214808501-f425d84f-59b7-474c-9b5c-ad75822bd9db.png)

Attached is a small project setup with the issue demonstrated, the above test-report is from this project:
https://github.com/YspMark/phpunit-coverage-shared-tests

**Comment by lucabecchetti** [comment]
any news?

**Comment by AdamPDotty** [comment]
I suppose you should at least add your phpunit.xml for insights. Have you given both directories under <source>?

**Comment by YspMark** [comment]
> I suppose you should at least add your phpunit.xml for insights. Have you given both directories under ?

It is inside of the app folder: https://github.com/YspMark/phpunit-coverage-shared-tests/blob/main/app/phpunit.xml

**Comment by dvdoug** [comment]
You haven't configured PCOV properly, it's falling back to defaults, see https://github.com/krakjoe/pcov

> The recommended defaults for development should be:
> 
> ```
>     pcov.enabled = 1
>     pcov.directory = /path/to/your/source/directory
> ```
> 
> When pcov.directory is left unset, PCOV will attempt to find src, lib or, app in the current working directory, in that order; If none are found the current directory will be used, which may waste resources storing coverage information for the test suite.

**Comment by YspMark** [comment]
Thanks that's it, when running with 
`php -dpcov.enabled=1 -dpcov.directory=/var/www/ -dpcov.exclude="~vendor~" vendor/bin/phpunit --coverage-html html` the coverage gets included. Although it doesn't pick up when you try to set the ini settings using the phpunit.xml
```
<ini name="pcov.enabled" value="1" />
<ini name="pcov.directory" value="/var/www/" />
<ini name="pcov.exclude" value="~vendor~" />
```

**Comment by dvdoug** [comment]
> Although it doesn't pick up when you try to set the ini settings using the phpunit.xml

It's not a runtime-configurable setting
