### ISSUE TITLE
Coverage is empty

### ISSUE THREAD

**Issue by tieceng** [sebastianbergmann/php-code-coverage#980]
<!DOCTYPE html><figure class="md-table-fig" cid="n8" mdtype="table" style="box-sizing: border-box; margin: 1.2em 0px; overflow-x: auto; max-width: calc(100% + 16px); padding: 0px; cursor: default; caret-color: rgb(184, 191, 198); color: rgb(184, 191, 198); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: rgb(54, 59, 64); text-decoration: none;">

Q | A
-- | --
php-code-coverage version | ^9.2
PHP version | 7.3.33
Driver | Xdebug
Xdebug | 3.1.6
Installation Method | Composer
Usage Method | PHPUnit
PHPUnit version (if used) | 9.6.3

</figure><pre class="md-fences md-end-block ty-contain-cm modeLoaded" spellcheck="false" lang="" cid="n74" mdtype="fences" style="box-sizing: border-box; overflow: visible; font-family: Monaco, Consolas, &quot;Andale Mono&quot;, &quot;DejaVu Sans Mono&quot;, monospace; margin-top: 0px; margin-bottom: 20px; font-size: 0.9rem; display: block; break-inside: avoid; text-align: left; white-space: normal; background-color: rgb(51, 51, 51); position: relative !important; padding: 10px 10px 10px 30px; width: inherit; caret-color: rgb(184, 191, 198); color: rgb(184, 191, 198); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;">I run the code, but there is no coverage. </span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;">I don’t know if it’s the system environment problem or the test case I wrote is wrong. </span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;">Please help me.</span></pre><h4 cid="n82" mdtype="heading" class="md-end-block md-heading" style="box-sizing: border-box; break-after: avoid-page; break-inside: avoid; orphans: 4; font-size: 1.12rem; margin: 0px 0px 1.5rem; font-family: &quot;Lucida Grande&quot;, Corbel, sans-serif; font-weight: normal; clear: both; word-wrap: break-word; padding: 0px; color: white; line-height: 1.375rem; white-space: pre-wrap; position: relative; font-style: normal; font-variant-caps: normal; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(54, 59, 64); text-decoration: none;"><span md-inline="plain" class="md-plain" style="box-sizing: border-box;">phpunit.xml</span></h4><pre class="md-fences md-end-block ty-contain-cm modeLoaded" spellcheck="false" lang="" cid="n79" mdtype="fences" style="box-sizing: border-box; overflow: visible; font-family: Monaco, Consolas, &quot;Andale Mono&quot;, &quot;DejaVu Sans Mono&quot;, monospace; margin-top: 0px; margin-bottom: 20px; font-size: 0.9rem; display: block; break-inside: avoid; text-align: left; white-space: normal; background-color: rgb(51, 51, 51); position: relative !important; padding: 10px 10px 10px 30px; width: inherit; caret-color: rgb(184, 191, 198); color: rgb(184, 191, 198); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;">&lt;?xml version="1.0" encoding="UTF-8"?&gt;</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;">&lt;phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp; &nbsp; &nbsp; &nbsp; xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/9.5/phpunit.xsd"</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp; &nbsp; &nbsp; &nbsp; bootstrap="test/Ainit.php"</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp; &nbsp; &nbsp; &nbsp; executionOrder="depends,defects"</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp; &nbsp; &nbsp; &nbsp; beStrictAboutCoversAnnotation="true"</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp; &nbsp; &nbsp; &nbsp; beStrictAboutOutputDuringTests="true"</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp; &nbsp; &nbsp; &nbsp; beStrictAboutTodoAnnotatedTests="true"</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp; &nbsp; &nbsp; &nbsp; convertDeprecationsToExceptions="true"</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp; &nbsp; &nbsp; &nbsp; failOnRisky="true"</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp; &nbsp; &nbsp; &nbsp; failOnWarning="true"</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp; &nbsp; &nbsp; &nbsp; verbose="true"</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp; &nbsp; &nbsp; &nbsp; colors="true"&gt;</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp;  &lt;testsuites&gt;</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp; &nbsp; &nbsp;  &lt;testsuite name="default"&gt;</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  &lt;directory&gt;test/app&lt;/directory&gt;</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp; &nbsp; &nbsp;  &lt;/testsuite&gt;</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp;  &lt;/testsuites&gt;</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"><span cm-text="" cm-zwsp="" style="box-sizing: border-box;">​</span></span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp;  &lt;coverage</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  includeUncoveredFiles="true"</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  processUncoveredFiles="false"</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  pathCoverage="false"</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  ignoreDeprecatedCodeUnits="true"</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  disableCodeCoverageIgnore="true"&gt;</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp; &nbsp; &nbsp;  &lt;include&gt;</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;">&lt;!-- &nbsp; &nbsp; &nbsp;  &lt;directory suffix=".php"&gt;./application/common/service/huati/&lt;/directory&gt;--&gt;</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  &lt;file&gt;application/common/service/huati/QueryManageService.php&lt;/file&gt;</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  &lt;file&gt;application/common/service/huati/QueryShieldService.php&lt;/file&gt;</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp; &nbsp; &nbsp;  &lt;/include&gt;</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp; &nbsp; &nbsp;  &lt;report&gt;</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  &lt;cobertura outputFile="./tmp/cobertura.xml"/&gt;</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  &lt;html outputDirectory="tmp" lowUpperBound="50" highLowerBound="90"/&gt;</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  &lt;text outputFile="php://stdout" showUncoveredFiles="false" showOnlySummary="true"/&gt;</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp; &nbsp; &nbsp;  &lt;/report&gt;</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp;  &lt;/coverage&gt;</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"><span cm-text="" cm-zwsp="" style="box-sizing: border-box;">​</span></span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp;  &lt;logging&gt;</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  &lt;junit outputFile="./tmp/junit.xml"/&gt;</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  &lt;testdoxXml outputFile="./tmp/testdox.xml"/&gt;</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  &lt;text outputFile="php://stdout"/&gt;</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp;  &lt;/logging&gt;</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;">&lt;/phpunit&gt;</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"><span cm-text="" cm-zwsp="" style="box-sizing: border-box;">​</span></span></pre><h4 cid="n80" mdtype="heading" class="md-end-block md-heading" style="box-sizing: border-box; break-after: avoid-page; break-inside: avoid; orphans: 4; font-size: 1.12rem; margin: 0px 0px 1.5rem; font-family: &quot;Lucida Grande&quot;, Corbel, sans-serif; font-weight: normal; clear: both; word-wrap: break-word; padding: 0px; color: white; line-height: 1.375rem; white-space: pre-wrap; position: relative; font-style: normal; font-variant-caps: normal; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(54, 59, 64); text-decoration: none;"><span md-inline="plain" class="md-plain" style="box-sizing: border-box;">QueryShieldServiceTest.php</span></h4><pre class="md-fences md-end-block ty-contain-cm modeLoaded" spellcheck="false" lang="" cid="n84" mdtype="fences" style="box-sizing: border-box; overflow: visible; font-family: Monaco, Consolas, &quot;Andale Mono&quot;, &quot;DejaVu Sans Mono&quot;, monospace; margin-top: 0px; margin-bottom: 20px; font-size: 0.9rem; display: block; break-inside: avoid; text-align: left; white-space: normal; background-color: rgb(51, 51, 51); position: relative !important; padding: 10px 10px 10px 30px; width: inherit; caret-color: rgb(184, 191, 198); color: rgb(184, 191, 198); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;">&lt;?php</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"><span cm-text="" cm-zwsp="" style="box-sizing: border-box;">​</span></span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;">use PHPUnit\Framework\TestCase;</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;">use app\common\service\huati\QueryShieldService;</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;">class QueryShieldServiceTest extends TestCase</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;">{</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"><span cm-text="" cm-zwsp="" style="box-sizing: border-box;">​</span></span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp;  public function testCoverage(){</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp; &nbsp; &nbsp;  $QueryShieldService = new QueryShieldService();</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp; &nbsp; &nbsp;  $res = $QueryShieldService-&gt;coverage();</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp; &nbsp; &nbsp;  $equals = true;</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp; &nbsp; &nbsp;  $this-&gt;assertEquals($equals, $res);</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp;  }</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"><span cm-text="" cm-zwsp="" style="box-sizing: border-box;">​</span></span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;">}</span></pre><h4 cid="n85" mdtype="heading" class="md-end-block md-heading" style="box-sizing: border-box; break-after: avoid-page; break-inside: avoid; orphans: 4; font-size: 1.12rem; margin: 0px 0px 1.5rem; font-family: &quot;Lucida Grande&quot;, Corbel, sans-serif; font-weight: normal; clear: both; word-wrap: break-word; padding: 0px; color: white; line-height: 1.375rem; white-space: pre-wrap; position: relative; font-style: normal; font-variant-caps: normal; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(54, 59, 64); text-decoration: none;"><span md-inline="plain" class="md-plain" style="box-sizing: border-box;">QueryShieldService.php</span></h4><pre class="md-fences md-end-block ty-contain-cm modeLoaded" spellcheck="false" lang="" cid="n88" mdtype="fences" style="box-sizing: border-box; overflow: visible; font-family: Monaco, Consolas, &quot;Andale Mono&quot;, &quot;DejaVu Sans Mono&quot;, monospace; margin-top: 0px; margin-bottom: 20px; font-size: 0.9rem; display: block; break-inside: avoid; text-align: left; white-space: normal; background-color: rgb(51, 51, 51); position: relative !important; padding: 10px 10px 10px 30px; width: inherit; caret-color: rgb(184, 191, 198); color: rgb(184, 191, 198); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;">&lt;?php</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"><span cm-text="" cm-zwsp="" style="box-sizing: border-box;">​</span></span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"><span cm-text="" cm-zwsp="" style="box-sizing: border-box;">​</span></span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;">namespace app\common\service\huati;</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"><span cm-text="" cm-zwsp="" style="box-sizing: border-box;">​</span></span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;">class QueryShieldService</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;">{</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"><span cm-text="" cm-zwsp="" style="box-sizing: border-box;">​</span></span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp;  public function coverage(){</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"><span cm-text="" cm-zwsp="" style="box-sizing: border-box;">​</span></span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp; &nbsp; &nbsp;  $a = [123];</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp; &nbsp; &nbsp;  /**</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp; &nbsp; &nbsp; &nbsp; * var_dump(123);  //This code can run the output, I commented out</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp; &nbsp; &nbsp; &nbsp; */</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp; &nbsp; &nbsp;  if(is_array($a)){</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  return true;</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp; &nbsp; &nbsp;  }</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp; &nbsp; &nbsp;  return $a;</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp;  }</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;">}</span></pre><h4 cid="n89" mdtype="heading" class="md-end-block md-heading" style="box-sizing: border-box; break-after: avoid-page; break-inside: avoid; orphans: 4; font-size: 1.12rem; margin: 0px 0px 1.5rem; font-family: &quot;Lucida Grande&quot;, Corbel, sans-serif; font-weight: normal; clear: both; word-wrap: break-word; padding: 0px; color: white; line-height: 1.375rem; white-space: pre-wrap; position: relative; font-style: normal; font-variant-caps: normal; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(54, 59, 64); text-decoration: none;"><span md-inline="plain" class="md-plain" style="box-sizing: border-box;">command line </span></h4><pre class="md-fences md-end-block ty-contain-cm modeLoaded" spellcheck="false" lang="" cid="n125" mdtype="fences" style="box-sizing: border-box; overflow: visible; font-family: Monaco, Consolas, &quot;Andale Mono&quot;, &quot;DejaVu Sans Mono&quot;, monospace; margin-top: 0px; margin-bottom: 20px; font-size: 0.9rem; display: block; break-inside: avoid; text-align: left; white-space: normal; background-color: rgb(51, 51, 51); position: relative !important; padding: 10px 10px 10px 30px; width: inherit; caret-color: rgb(184, 191, 198); color: rgb(184, 191, 198); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;">[root@8b82686751d5]# ./vendor/bin/phpunit</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> </span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> PHPUnit 9.6.3 by Sebastian Bergmann and contributors.</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"><span cm-text="" cm-zwsp="" style="box-sizing: border-box;">​</span></span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;">Runtime: &nbsp; &nbsp; &nbsp; PHP 7.3.33 with Xdebug 3.1.6</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;">Configuration: /data1/nginx/htdocs/admin.s.weibo.com/phpunit.xml</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"><span cm-text="" cm-zwsp="" style="box-sizing: border-box;">​</span></span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;">. &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 1 / 1 (100%). &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 1 / 1 (100%)</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"><span cm-text="" cm-zwsp="" style="box-sizing: border-box;">​</span></span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;">Time: 00:00.518, Memory: 10.00 MB</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"><span cm-text="" cm-zwsp="" style="box-sizing: border-box;">​</span></span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;">OK (1 test, 1 assertion)</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"><span cm-text="" cm-zwsp="" style="box-sizing: border-box;">​</span></span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;">Generating code coverage report in Cobertura XML format ... done [00:01.586]</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"><span cm-text="" cm-zwsp="" style="box-sizing: border-box;">​</span></span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;">Generating code coverage report in HTML format ... done [00:00.737]</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"><span cm-text="" cm-zwsp="" style="box-sizing: border-box;">​</span></span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"><span cm-text="" cm-zwsp="" style="box-sizing: border-box;">​</span></span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;">Code Coverage Report Summary:</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;">  Classes:  0.00% (0/2)</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;">  Methods:  0.00% (0/20)</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;">  Lines: &nbsp;  0.00% (0/396)</span></pre><h4 cid="n126" mdtype="heading" class="md-end-block md-heading md-focus" style="box-sizing: border-box; break-after: avoid-page; break-inside: avoid; orphans: 4; font-size: 1.12rem; margin: 0px 0px 1.5rem; font-family: &quot;Lucida Grande&quot;, Corbel, sans-serif; font-weight: normal; clear: both; word-wrap: break-word; padding: 0px; color: white; line-height: 1.375rem; white-space: pre-wrap; position: relative; font-style: normal; font-variant-caps: normal; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(54, 59, 64); text-decoration: none;"><span md-inline="plain" class="md-plain md-expand" style="box-sizing: border-box;">coverage-html</span></h4>
<img width="887" alt="image" src="https://user-images.githubusercontent.com/19903677/216950140-e5fdfab6-a039-4d1e-becc-55a8f124b6af.png">

**Comment by tieceng** [comment]
i found a solution
closed

**Comment by HoangLongTrinh** [comment]
@tieceng 
could you help me about this?
i got same error :(
