### ISSUE TITLE
CodeUnitFindingVisitor does not support DNF types

### ISSUE THREAD

**Issue by simPod** [sebastianbergmann/php-code-coverage#981]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 10.0.0
| PHP version               | 8.2.3
| Driver                    | PCOV
| PCOV version (if used)    | 1.0.11
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 10.0.11

The assertion started failing when I did following change

```diff
- public function foo(string $bar): A&B
+ public function foo(string $bar): (A&B)|null
    {
        ...
    }
```

https://github.com/sebastianbergmann/php-code-coverage/blob/68525fccfa74f01401c213a5e03e0549dbb92656/src/StaticAnalysis/CodeUnitFindingVisitor.php#L303

<img width="683" alt="image" src="https://user-images.githubusercontent.com/327717/221199103-fb6a91f3-3e0d-4467-9a6f-4061d99c5f90.png">

<img width="1167" alt="image" src="https://user-images.githubusercontent.com/327717/221199246-8f5b9edd-f97e-4687-a7ff-e0e6484f78f3.png">

**Comment by Dariusz385** [comment]
https://github.com/sebastianbergmann/php-code-coverage/issues/981
