### ISSUE TITLE
Not sure why, but `windows-latest` requires `openssl` to install dependencies with `composer`. Works fine on `ubuntu-latest`.

### ISSUE THREAD

**Issue by Dariusz385** [sebastianbergmann/php-code-coverage#992]
Not sure why, but `windows-latest` requires `openssl` to install dependencies with `composer`. Works fine on `ubuntu-latest`.

_Originally posted by @localheinz in https://github.com/sebastianbergmann/php-code-coverage/pull/989#discussion_r1140237396_

**Comment by sebastianbergmann** [comment]
I am not sure what to make of this ticket.
