### ISSUE TITLE
How to use php-code-coverage to collect php coverage in microservices pattern

### ISSUE THREAD

**Issue by zhuang111** [sebastianbergmann/php-code-coverage#995]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 6.0.7
| PHP version               | 7.3.29
| Driver                    | PCOV / Xdebug
| PCOV version (if used)    | x.y.z
| Xdebug version (if used)  | v3.1.6
| Installation Method       | Composer / PHPUnit PHAR
| Usage Method              | PHPUnit / other
| PHPUnit version (if used) | x.y.z

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry.
