### ISSUE TITLE
Unable to generate report with the legend of *Executed *Not Executed*Dead Code

### ISSUE THREAD

**Issue by raine-alegnor** [sebastianbergmann/php-code-coverage#999]
| Q     
I am unable to generate the report with the format that have *Executed *Not Executed*Dead Code

[php-code-coverage 9.2.26] using [PHP 8.1.10] and [PHPUnit 9.6.8] Xdebug v3.2.1,

i am trying to generate the report to check the performance of laravel application creating a command. the command run well but i didnt get the report that i expected. 

this is my laravel command code :

**Comment by raine-alegnor** [comment]
<?php
namespace App\BC\Console\Commands;

use Illuminate\Console\Command;
use SebastianBergmann\CodeCoverage\CodeCoverage;
use SebastianBergmann\CodeCoverage\Filter;
use SebastianBergmann\CodeCoverage\Report\Html\Facade as HtmlReport;
use SebastianBergmann\CodeCoverage\Driver\Xdebug3Driver;
use PHPUnit\Framework\TestSuite;
use PHPUnit\TextUI\TestRunner;

class GenerateCoverageReport extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'generate-coverage';
    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Generate coverage report';
    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {

        $filter = new Filter;

        $filter->includeDirectory(base_path('app'));


        $driver = new Xdebug3Driver($filter);

        $coverage = new CodeCoverage($driver, $filter);

        $coverage->processUncoveredFiles(); // Enable processing of uncovered files
        $coverage->
        $coverage->start('coverage');

        // Run PHPUnit tests


        $coverage->stop();


        $htmlReport = new HtmlReport();
        $htmlReport->process($coverage, storage_path('app/public/code-coverage-report'));


        $this->line('');
        $this->line('Code coverage report generated.');

        $this->output->writeln('');
        $this->output->writeln('Done.');
    }

}

**Comment by raine-alegnor** [comment]
$filter = new Filter;

        $filter->includeDirectory(base_path('app'));


        $driver = new Xdebug3Driver($filter);

        $coverage = new CodeCoverage($driver, $filter);

        $coverage->processUncoveredFiles(); // Enable processing of uncovered files
        $coverage->
        $coverage->start('coverage');

        // Run PHPUnit tests


        $coverage->stop();


        $htmlReport = new HtmlReport();
        $htmlReport->process($coverage, storage_path('app/public/code-coverage-report'));


        $this->line('');
        $this->line('Code coverage report generated.');

        $this->output->writeln('');
        $this->output->writeln('Done.');

**Comment by sebastianbergmann** [comment]
I do not understand what you are trying to report.

**Comment by raine-alegnor** [comment]
with the previous code i am genereting this report : https://prnt.sc/JXkW-OCOUdav

and i need this : https://prnt.sc/vWtZcaNaN3Cm

the app is on laravel and i want to get the second report @sebastianbergmann
